// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: eventsync.proto

package server

import (
	"context"

	"github.com/rezeropoint/nexlyn/service/eventsync/internal/logic"
	"github.com/rezeropoint/nexlyn/service/eventsync/internal/svc"
	"github.com/rezeropoint/nexlyn/service/eventsync/pb"
)

type AdminSyncServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedAdminSyncServer
}

func NewAdminSyncServer(svcCtx *svc.ServiceContext) *AdminSyncServer {
	return &AdminSyncServer{
		svcCtx: svcCtx,
	}
}

// 同步单个用户到Skylark
func (s *AdminSyncServer) SyncUser(ctx context.Context, in *pb.SyncUserReq) (*pb.SyncUserResp, error) {
	l := logic.NewSyncUserLogic(ctx, s.svcCtx)
	return l.SyncUser(in)
}

// 同步单个组织到Skylark（自动判断根组织或子组织）
func (s *AdminSyncServer) SyncOrganization(ctx context.Context, in *pb.SyncOrganizationReq) (*pb.SyncOrganizationResp, error) {
	l := logic.NewSyncOrganizationLogic(ctx, s.svcCtx)
	return l.SyncOrganization(in)
}

// 删除组织同步
func (s *AdminSyncServer) DeleteOrganization(ctx context.Context, in *pb.DeleteOrganizationReq) (*pb.DeleteOrganizationResp, error) {
	l := logic.NewDeleteOrganizationLogic(ctx, s.svcCtx)
	return l.DeleteOrganization(in)
}

// 健康检查
func (s *AdminSyncServer) HealthCheck(ctx context.Context, in *pb.HealthCheckReq) (*pb.HealthCheckResp, error) {
	l := logic.NewHealthCheckLogic(ctx, s.svcCtx)
	return l.HealthCheck(in)
}

// 查询用户同步状态
func (s *AdminSyncServer) GetUserSyncStatus(ctx context.Context, in *pb.GetUserSyncStatusReq) (*pb.GetUserSyncStatusResp, error) {
	l := logic.NewGetUserSyncStatusLogic(ctx, s.svcCtx)
	return l.GetUserSyncStatus(in)
}

// 查询组织同步状态
func (s *AdminSyncServer) GetOrgSyncStatus(ctx context.Context, in *pb.GetOrgSyncStatusReq) (*pb.GetOrgSyncStatusResp, error) {
	l := logic.NewGetOrgSyncStatusLogic(ctx, s.svcCtx)
	return l.GetOrgSyncStatus(in)
}

// 绑定已存在的远程组织
func (s *AdminSyncServer) BindOrganization(ctx context.Context, in *pb.BindOrganizationReq) (*pb.BindOrganizationResp, error) {
	l := logic.NewBindOrganizationLogic(ctx, s.svcCtx)
	return l.BindOrganization(in)
}

// 解绑组织映射
func (s *AdminSyncServer) UnbindOrganization(ctx context.Context, in *pb.UnbindOrganizationReq) (*pb.UnbindOrganizationResp, error) {
	l := logic.NewUnbindOrganizationLogic(ctx, s.svcCtx)
	return l.UnbindOrganization(in)
}

// 绑定已存在的远程用户
func (s *AdminSyncServer) BindUser(ctx context.Context, in *pb.BindUserReq) (*pb.BindUserResp, error) {
	l := logic.NewBindUserLogic(ctx, s.svcCtx)
	return l.BindUser(in)
}

// 解绑用户映射
func (s *AdminSyncServer) UnbindUser(ctx context.Context, in *pb.UnbindUserReq) (*pb.UnbindUserResp, error) {
	l := logic.NewUnbindUserLogic(ctx, s.svcCtx)
	return l.UnbindUser(in)
}

// 更新组织信息（支持设置管理员）
func (s *AdminSyncServer) UpdateOrganization(ctx context.Context, in *pb.UpdateOrganizationReq) (*pb.UpdateOrganizationResp, error) {
	l := logic.NewUpdateOrganizationLogic(ctx, s.svcCtx)
	return l.UpdateOrganization(in)
}

// 添加成员到组织
func (s *AdminSyncServer) AddMember(ctx context.Context, in *pb.AddMemberReq) (*pb.AddMemberResp, error) {
	l := logic.NewAddMemberLogic(ctx, s.svcCtx)
	return l.AddMember(in)
}

// 从组织移除成员
func (s *AdminSyncServer) RemoveMember(ctx context.Context, in *pb.RemoveMemberReq) (*pb.RemoveMemberResp, error) {
	l := logic.NewRemoveMemberLogic(ctx, s.svcCtx)
	return l.RemoveMember(in)
}
