// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type BaseResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

type BatchQueryTagsRequest struct {
	TenantId string   `json:"tenantId"` // 租户ID（必填）
	Scope    string   `json:"scope"`    // 作用域（必填）
	Names    []string `json:"names"`    // 标签名称列表
}

type BatchQueryTagsResponse struct {
	BaseResponse
	Data []LynxTagSummary `json:"data"`
}

type BlockSpec struct {
	BlockType    string `json:"blockType"`             // 逻辑块类型
	Version      string `json:"version"`               // 版本
	Name         string `json:"name"`                  // 显示名称
	Description  string `json:"description"`           // 描述
	Category     string `json:"category"`              // 分类
	InputSchema  string `json:"inputSchema,optional"`  // 输入Schema（JSON字符串）
	OutputSchema string `json:"outputSchema,optional"` // 输出Schema（JSON字符串）
	ConfigSchema string `json:"configSchema,optional"` // 配置Schema（JSON字符串）
}

type CreateGraphConfigData struct {
	Id string `json:"id"` // 创建的逻辑图ID
}

type CreateGraphConfigRequest struct {
	TenantId    string       `json:"tenantId"`             // 租户ID
	OrgId       string       `json:"orgId,optional"`       // 所属组织ID（可选，后端从JWT自动填充）
	Name        string       `json:"name"`                 // 图名称
	Version     string       `json:"version"`              // 版本号
	Description string       `json:"description,optional"` // 描述
	TagIds      []string     `json:"tagIds,optional"`      // 标签ID列表
	IsEnabled   bool         `json:"isEnabled,optional"`   // 是否启用（默认true）
	Icon        string       `json:"icon,optional"`        // 图标名称
	IconColor   string       `json:"iconColor,optional"`   // 图标颜色
	Nodes       []NodeConfig `json:"nodes,optional"`       // 节点列表（可选，在详情页编辑）
	Edges       []EdgeConfig `json:"edges,optional"`       // 边列表（可选，在详情页编辑）
}

type CreateGraphConfigResponse struct {
	BaseResponse
	Data CreateGraphConfigData `json:"data,omitempty"`
}

type CreateInfoAtomTypeData struct {
	Id string `json:"id"` // 创建的信息原子类型ID
}

type CreateInfoAtomTypeRequest struct {
	TenantId   string     `json:"tenantId"`        // 租户ID
	Name       string     `json:"name"`            // 类型名称
	Version    string     `json:"version"`         // 版本号
	TagIds     []string   `json:"tagIds,optional"` // 标签ID列表
	DataFormat DataFormat `json:"dataFormat"`      // 数据格式定义
}

type CreateInfoAtomTypeResponse struct {
	BaseResponse
	Data CreateInfoAtomTypeData `json:"data,omitempty"`
}

type CreateTagData struct {
	Id string `json:"id"` // 新创建的标签ID
}

type CreateTagRequest struct {
	Name        string `json:"name"`                 // 标签名称（必填）
	Description string `json:"description,optional"` // 标签描述
	Scope       string `json:"scope"`                // 标签作用域（必填）：info_atom / logic_graph
	TenantId    string `json:"tenantId"`             // 租户ID（必填）
	CreatedBy   string `json:"createdBy,optional"`   // 创建者用户ID
}

type CreateTagResponse struct {
	BaseResponse
	Data CreateTagData `json:"data,omitempty"`
}

type DataFormat struct {
	DataPlural bool          `json:"dataPlural"`          // 数据是否为数组
	FieldStart string        `json:"fieldStart,optional"` // 数组数据的起始字段路径
	Fields     []FieldConfig `json:"fields"`              // 字段列表
}

type DeleteGraphConfigRequest struct {
	Id string `path:"id"` // 逻辑图ID
}

type DeleteGraphConfigResponse struct {
	BaseResponse
}

type DeleteInfoAtomTypeRequest struct {
	Id string `path:"id"` // 信息原子类型ID
}

type DeleteInfoAtomTypeResponse struct {
	BaseResponse
}

type DeleteTagRequest struct {
	Id string `path:"id"` // 标签ID
}

type DeleteTagResponse struct {
	BaseResponse
}

type EdgeConfig struct {
	Id        string `json:"id"`                 // 边ID
	SourceID  string `json:"sourceID"`           // 源节点ID
	TargetID  string `json:"targetID"`           // 目标节点ID
	Condition string `json:"condition,optional"` // 条件表达式
}

type FieldConfig struct {
	FieldKey  string `json:"fieldKey"`  // 字段键
	FieldPath string `json:"fieldPath"` // 字段路径（支持JSONPath）
	FieldType string `json:"fieldType"` // 字段类型：string/int/float/bool
}

type GetBlockSpecsData struct {
	List []BlockSpec `json:"list"` // 逻辑块规格列表
}

type GetBlockSpecsRequest struct {
}

type GetBlockSpecsResponse struct {
	BaseResponse
	Data GetBlockSpecsData `json:"data,omitempty"`
}

type GetGraphConfigListData struct {
	List []GraphConfigMetadata `json:"list"` // 逻辑图元数据列表
}

type GetGraphConfigListRequest struct {
	Page      int      `form:"page,default=1"`
	PageSize  int      `form:"pageSize,default=10"`
	TenantId  string   `form:"tenantId"`           // 租户ID（必填）
	Name      string   `form:"name,optional"`      // 图名称筛选（模糊匹配）
	Tags      []string `form:"tags,optional"`      // 标签筛选
	IsEnabled *bool    `form:"isEnabled,optional"` // 启用状态筛选
}

type GetGraphConfigListResponse struct {
	BaseResponse
	PageParams
	Data GetGraphConfigListData `json:"data,omitempty"`
}

type GetGraphConfigRequest struct {
	Id string `path:"id"` // 逻辑图ID
}

type GetGraphConfigResponse struct {
	BaseResponse
	Data GraphConfigDetail `json:"data,omitempty"` // 逻辑图详情
}

type GetInfoAtomTypeListData struct {
	List []InfoAtomType `json:"list"` // 信息原子类型列表
}

type GetInfoAtomTypeListRequest struct {
	Page     int      `form:"page,default=1"`
	PageSize int      `form:"pageSize,default=10"`
	TenantId string   `form:"tenantId"`      // 租户ID（必填）
	Name     string   `form:"name,optional"` // 类型名称筛选（模糊匹配）
	Tags     []string `form:"tags,optional"` // 标签筛选
}

type GetInfoAtomTypeListResponse struct {
	BaseResponse
	PageParams
	Data GetInfoAtomTypeListData `json:"data,omitempty"`
}

type GetInfoAtomTypeRequest struct {
	Id string `path:"id"` // 信息原子类型ID
}

type GetInfoAtomTypeResponse struct {
	BaseResponse
	Data InfoAtomType `json:"data,omitempty"` // 信息原子类型详情
}

type GetTagRequest struct {
	Id string `path:"id"` // 标签ID
}

type GetTagResponse struct {
	BaseResponse
	Data LynxTag `json:"data,omitempty"`
}

type GraphConfigDetail struct {
	GraphConfigMetadata
	Nodes []NodeConfig `json:"nodes"` // 节点列表
	Edges []EdgeConfig `json:"edges"` // 边列表
}

type GraphConfigMetadata struct {
	Id          string           `json:"id"`                   // 逻辑图ID（UUID）
	TenantId    string           `json:"tenantId"`             // 租户ID
	OrgId       string           `json:"orgId"`                // 所属组织ID（用于权限控制）
	Name        string           `json:"name"`                 // 图名称
	Version     string           `json:"version"`              // 版本号
	Description string           `json:"description,optional"` // 描述
	Tags        []LynxTagSummary `json:"tags,optional"`        // 标签列表（Phase 2.5: 完整对象）
	IsEnabled   bool             `json:"isEnabled"`            // 是否启用
	Icon        string           `json:"icon,optional"`        // 图标名称（如 'FaRobot', 'MdSensors'）
	IconColor   string           `json:"iconColor,optional"`   // 图标颜色（可选，默认使用主题色）
	CreatedAt   int64            `json:"createdAt,optional"`   // 创建时间（Unix毫秒）
	UpdatedAt   int64            `json:"updatedAt,optional"`   // 更新时间（Unix毫秒）
	CreatedBy   string           `json:"createdBy,optional"`   // 创建人ID
	UpdatedBy   string           `json:"updatedBy,optional"`   // 更新人ID
}

type InfoAtomType struct {
	Id         string           `json:"id"`                 // 信息原子类型ID（UUID）
	TenantId   string           `json:"tenantId"`           // 租户ID
	Name       string           `json:"name"`               // 类型名称（如 sensor.temperature）
	Version    string           `json:"version"`            // 版本号（如 v1）
	Tags       []LynxTagSummary `json:"tags,optional"`      // 标签列表（Phase 2.5: 完整对象）
	DataFormat DataFormat       `json:"dataFormat"`         // 数据格式定义
	CreatedAt  int64            `json:"createdAt,optional"` // 创建时间（Unix毫秒）
	UpdatedAt  int64            `json:"updatedAt,optional"` // 更新时间（Unix毫秒）
	CreatedBy  string           `json:"createdBy,optional"` // 创建人ID
	UpdatedBy  string           `json:"updatedBy,optional"` // 更新人ID
}

type ListTagsData struct {
	List []LynxTagSummary `json:"list"`
}

type ListTagsRequest struct {
	TenantId string `form:"tenantId"`         // 租户ID（必填）
	Scope    string `form:"scope,optional"`   // 作用域筛选（可选）
	Keyword  string `form:"keyword,optional"` // 关键词搜索
	Page     int    `form:"page,default=1"`
	PageSize int    `form:"pageSize,default=10"`
}

type ListTagsResponse struct {
	BaseResponse
	PageParams
	Data ListTagsData `json:"data"`
}

type LynxTag struct {
	Id          string `json:"id"`          // 标签ID（UUID）
	Name        string `json:"name"`        // 标签名称
	Description string `json:"description"` // 标签描述
	Scope       string `json:"scope"`       // 标签作用域：info_atom / logic_graph
	TenantId    string `json:"tenantId"`    // 租户ID
	CreatedBy   string `json:"createdBy"`   // 创建者用户ID
	UpdatedBy   string `json:"updatedBy"`   // 最后修改者用户ID
	CreatedAt   int64  `json:"createdAt"`   // 创建时间（Unix秒）
	UpdatedAt   int64  `json:"updatedAt"`   // 更新时间（Unix秒）
}

type LynxTagSummary struct {
	Id          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Scope       string `json:"scope"`
	CreatedAt   int64  `json:"createdAt"`
	UpdatedAt   int64  `json:"updatedAt"`
}

type NodeConfig struct {
	Id                        string   `json:"id"`                                 // 节点ID
	Type                      string   `json:"type"`                               // 节点类型（entry/action/filter等）
	BlockType                 string   `json:"blockType"`                          // 逻辑块类型
	BlockVersion              string   `json:"blockVersion"`                       // 逻辑块版本
	IsEntryPoint              bool     `json:"isEntryPoint"`                       // 是否为入口节点
	SubscribedInfoAtomTypeIDs []string `json:"subscribedInfoAtomTypeIDs,optional"` // 订阅的信息原子类型ID列表
	SubscribedSource          string   `json:"subscribedSource,optional"`          // 订阅的数据来源
	SubscribedLabels          []string `json:"subscribedLabels,optional"`          // 订阅的标签列表
	BlockConfig               string   `json:"blockConfig,optional"`               // 逻辑块配置（JSON字符串）
	X                         float64  `json:"x,optional"`                         // 画布X坐标
	Y                         float64  `json:"y,optional"`                         // 画布Y坐标
}

type PageParams struct {
	Page     int   `json:"page"`
	PageSize int   `json:"pageSize"`
	Total    int64 `json:"total"`
}

type PageParamsRequest struct {
	Page     int `form:"page,default=1"`
	PageSize int `form:"pageSize,default=10"`
}

type UpdateGraphConfigRequest struct {
	Id          string       `path:"id"`                   // 逻辑图ID
	TenantId    string       `json:"tenantId"`             // 租户ID
	Name        string       `json:"name"`                 // 图名称
	Version     string       `json:"version"`              // 版本号
	Description string       `json:"description,optional"` // 描述
	TagIds      []string     `json:"tagIds,optional"`      // 标签ID列表
	IsEnabled   bool         `json:"isEnabled,optional"`   // 是否启用
	Icon        string       `json:"icon,optional"`        // 图标名称
	IconColor   string       `json:"iconColor,optional"`   // 图标颜色
	Nodes       []NodeConfig `json:"nodes"`                // 节点列表
	Edges       []EdgeConfig `json:"edges"`                // 边列表
}

type UpdateGraphConfigResponse struct {
	BaseResponse
}

type UpdateInfoAtomTypeRequest struct {
	Id         string     `path:"id"`              // 信息原子类型ID
	TenantId   string     `json:"tenantId"`        // 租户ID
	Name       string     `json:"name"`            // 类型名称
	Version    string     `json:"version"`         // 版本号
	TagIds     []string   `json:"tagIds,optional"` // 标签ID列表
	DataFormat DataFormat `json:"dataFormat"`      // 数据格式定义
}

type UpdateInfoAtomTypeResponse struct {
	BaseResponse
}

type UpdateTagRequest struct {
	Id          string `path:"id"` // 标签ID
	Name        string `json:"name,optional"`
	Description string `json:"description,optional"`
}

type UpdateTagResponse struct {
	BaseResponse
}
