// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.4
// source: iotquery.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// QueryTimeSeriesReq 时序数据查询请求
type QueryTimeSeriesReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 权限信息（由调用方提供，已完成验证）
	TenantId string   `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"` // 租户ID（必填）
	OrgIds   []string `protobuf:"bytes,2,rep,name=org_ids,json=orgIds,proto3" json:"org_ids,omitempty"`       // 组织ID列表（必填，包含所有子组织）
	// 查询条件
	DeviceIds  []string `protobuf:"bytes,3,rep,name=device_ids,json=deviceIds,proto3" json:"device_ids,omitempty"`    // 设备ID列表（可选，为空则查询组织下所有设备）
	FieldNames []string `protobuf:"bytes,4,rep,name=field_names,json=fieldNames,proto3" json:"field_names,omitempty"` // 查询字段列表（必填，最多10个）
	StartTime  int64    `protobuf:"varint,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`   // 开始时间（Unix时间戳，秒）
	EndTime    int64    `protobuf:"varint,6,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`         // 结束时间（Unix时间戳，秒）
	// 聚合选项
	Aggregation     string `protobuf:"bytes,7,opt,name=aggregation,proto3" json:"aggregation,omitempty"`                                 // 聚合类型：空/"avg"/"max"/"min"/"sum"/"count"/"last"
	IntervalSeconds int64  `protobuf:"varint,8,opt,name=interval_seconds,json=intervalSeconds,proto3" json:"interval_seconds,omitempty"` // 聚合时间间隔（秒），仅aggregation非空时有效
	// 分页和排序
	Limit         int32  `protobuf:"varint,9,opt,name=limit,proto3" json:"limit,omitempty"`                       // 限制返回条数（默认1000，最大10000）
	Offset        int32  `protobuf:"varint,10,opt,name=offset,proto3" json:"offset,omitempty"`                    // 偏移量（默认0）
	OrderBy       string `protobuf:"bytes,11,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`    // 排序字段："timestamp"/"device_id"
	OrderDir      string `protobuf:"bytes,12,opt,name=order_dir,json=orderDir,proto3" json:"order_dir,omitempty"` // 排序方向："asc"/"desc"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryTimeSeriesReq) Reset() {
	*x = QueryTimeSeriesReq{}
	mi := &file_iotquery_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryTimeSeriesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTimeSeriesReq) ProtoMessage() {}

func (x *QueryTimeSeriesReq) ProtoReflect() protoreflect.Message {
	mi := &file_iotquery_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTimeSeriesReq.ProtoReflect.Descriptor instead.
func (*QueryTimeSeriesReq) Descriptor() ([]byte, []int) {
	return file_iotquery_proto_rawDescGZIP(), []int{0}
}

func (x *QueryTimeSeriesReq) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *QueryTimeSeriesReq) GetOrgIds() []string {
	if x != nil {
		return x.OrgIds
	}
	return nil
}

func (x *QueryTimeSeriesReq) GetDeviceIds() []string {
	if x != nil {
		return x.DeviceIds
	}
	return nil
}

func (x *QueryTimeSeriesReq) GetFieldNames() []string {
	if x != nil {
		return x.FieldNames
	}
	return nil
}

func (x *QueryTimeSeriesReq) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *QueryTimeSeriesReq) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *QueryTimeSeriesReq) GetAggregation() string {
	if x != nil {
		return x.Aggregation
	}
	return ""
}

func (x *QueryTimeSeriesReq) GetIntervalSeconds() int64 {
	if x != nil {
		return x.IntervalSeconds
	}
	return 0
}

func (x *QueryTimeSeriesReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *QueryTimeSeriesReq) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *QueryTimeSeriesReq) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

func (x *QueryTimeSeriesReq) GetOrderDir() string {
	if x != nil {
		return x.OrderDir
	}
	return ""
}

// QueryTimeSeriesResp 时序数据查询响应
type QueryTimeSeriesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*TimeSeriesRecord    `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`                    // 数据列表
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`                       // 总记录数
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`                         // 当前页码
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // 每页数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryTimeSeriesResp) Reset() {
	*x = QueryTimeSeriesResp{}
	mi := &file_iotquery_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryTimeSeriesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTimeSeriesResp) ProtoMessage() {}

func (x *QueryTimeSeriesResp) ProtoReflect() protoreflect.Message {
	mi := &file_iotquery_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTimeSeriesResp.ProtoReflect.Descriptor instead.
func (*QueryTimeSeriesResp) Descriptor() ([]byte, []int) {
	return file_iotquery_proto_rawDescGZIP(), []int{1}
}

func (x *QueryTimeSeriesResp) GetRecords() []*TimeSeriesRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *QueryTimeSeriesResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *QueryTimeSeriesResp) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *QueryTimeSeriesResp) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// TimeSeriesRecord 时序数据记录
type TimeSeriesRecord struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Timestamp      int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                // 数据时间戳（Unix时间戳，秒）
	DeviceId       string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`                   // 设备唯一标识符
	DeviceModel    string                 `protobuf:"bytes,3,opt,name=device_model,json=deviceModel,proto3" json:"device_model,omitempty"`          // 设备型号
	DeviceCategory string                 `protobuf:"bytes,4,opt,name=device_category,json=deviceCategory,proto3" json:"device_category,omitempty"` // 设备类别
	FieldName      string                 `protobuf:"bytes,5,opt,name=field_name,json=fieldName,proto3" json:"field_name,omitempty"`                // 字段名称
	ValueJson      string                 `protobuf:"bytes,6,opt,name=value_json,json=valueJson,proto3" json:"value_json,omitempty"`                // 字段值（JSON格式，支持多种类型）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TimeSeriesRecord) Reset() {
	*x = TimeSeriesRecord{}
	mi := &file_iotquery_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeSeriesRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeSeriesRecord) ProtoMessage() {}

func (x *TimeSeriesRecord) ProtoReflect() protoreflect.Message {
	mi := &file_iotquery_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeSeriesRecord.ProtoReflect.Descriptor instead.
func (*TimeSeriesRecord) Descriptor() ([]byte, []int) {
	return file_iotquery_proto_rawDescGZIP(), []int{2}
}

func (x *TimeSeriesRecord) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TimeSeriesRecord) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *TimeSeriesRecord) GetDeviceModel() string {
	if x != nil {
		return x.DeviceModel
	}
	return ""
}

func (x *TimeSeriesRecord) GetDeviceCategory() string {
	if x != nil {
		return x.DeviceCategory
	}
	return ""
}

func (x *TimeSeriesRecord) GetFieldName() string {
	if x != nil {
		return x.FieldName
	}
	return ""
}

func (x *TimeSeriesRecord) GetValueJson() string {
	if x != nil {
		return x.ValueJson
	}
	return ""
}

// GetLatestValuesReq 最新值查询请求
type GetLatestValuesReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 权限信息
	TenantId string   `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	OrgIds   []string `protobuf:"bytes,2,rep,name=org_ids,json=orgIds,proto3" json:"org_ids,omitempty"`
	// 查询条件
	DeviceIds     []string `protobuf:"bytes,3,rep,name=device_ids,json=deviceIds,proto3" json:"device_ids,omitempty"`    // 设备ID列表（可选）
	FieldNames    []string `protobuf:"bytes,4,rep,name=field_names,json=fieldNames,proto3" json:"field_names,omitempty"` // 字段列表（必填）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestValuesReq) Reset() {
	*x = GetLatestValuesReq{}
	mi := &file_iotquery_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestValuesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestValuesReq) ProtoMessage() {}

func (x *GetLatestValuesReq) ProtoReflect() protoreflect.Message {
	mi := &file_iotquery_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestValuesReq.ProtoReflect.Descriptor instead.
func (*GetLatestValuesReq) Descriptor() ([]byte, []int) {
	return file_iotquery_proto_rawDescGZIP(), []int{3}
}

func (x *GetLatestValuesReq) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetLatestValuesReq) GetOrgIds() []string {
	if x != nil {
		return x.OrgIds
	}
	return nil
}

func (x *GetLatestValuesReq) GetDeviceIds() []string {
	if x != nil {
		return x.DeviceIds
	}
	return nil
}

func (x *GetLatestValuesReq) GetFieldNames() []string {
	if x != nil {
		return x.FieldNames
	}
	return nil
}

// GetLatestValuesResp 最新值查询响应
type GetLatestValuesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Devices       []*DeviceLatestValues  `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestValuesResp) Reset() {
	*x = GetLatestValuesResp{}
	mi := &file_iotquery_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestValuesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestValuesResp) ProtoMessage() {}

func (x *GetLatestValuesResp) ProtoReflect() protoreflect.Message {
	mi := &file_iotquery_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestValuesResp.ProtoReflect.Descriptor instead.
func (*GetLatestValuesResp) Descriptor() ([]byte, []int) {
	return file_iotquery_proto_rawDescGZIP(), []int{4}
}

func (x *GetLatestValuesResp) GetDevices() []*DeviceLatestValues {
	if x != nil {
		return x.Devices
	}
	return nil
}

// DeviceLatestValues 设备最新值
type DeviceLatestValues struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`                                                       // 设备ID
	Fields        map[string]*FieldValue `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 字段名 -> 字段值映射
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceLatestValues) Reset() {
	*x = DeviceLatestValues{}
	mi := &file_iotquery_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceLatestValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceLatestValues) ProtoMessage() {}

func (x *DeviceLatestValues) ProtoReflect() protoreflect.Message {
	mi := &file_iotquery_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceLatestValues.ProtoReflect.Descriptor instead.
func (*DeviceLatestValues) Descriptor() ([]byte, []int) {
	return file_iotquery_proto_rawDescGZIP(), []int{5}
}

func (x *DeviceLatestValues) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DeviceLatestValues) GetFields() map[string]*FieldValue {
	if x != nil {
		return x.Fields
	}
	return nil
}

// FieldValue 字段值（包含值和时间戳）
type FieldValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ValueJson     string                 `protobuf:"bytes,1,opt,name=value_json,json=valueJson,proto3" json:"value_json,omitempty"` // 字段值（JSON格式）
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                 // 时间戳（Unix时间戳，秒）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldValue) Reset() {
	*x = FieldValue{}
	mi := &file_iotquery_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldValue) ProtoMessage() {}

func (x *FieldValue) ProtoReflect() protoreflect.Message {
	mi := &file_iotquery_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldValue.ProtoReflect.Descriptor instead.
func (*FieldValue) Descriptor() ([]byte, []int) {
	return file_iotquery_proto_rawDescGZIP(), []int{6}
}

func (x *FieldValue) GetValueJson() string {
	if x != nil {
		return x.ValueJson
	}
	return ""
}

func (x *FieldValue) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// GetDeviceStatisticsReq 设备统计查询请求
type GetDeviceStatisticsReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 权限信息
	TenantId string   `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	OrgIds   []string `protobuf:"bytes,2,rep,name=org_ids,json=orgIds,proto3" json:"org_ids,omitempty"`
	// 查询条件
	DeviceIds     []string `protobuf:"bytes,3,rep,name=device_ids,json=deviceIds,proto3" json:"device_ids,omitempty"`    // 设备ID列表（可选）
	FieldNames    []string `protobuf:"bytes,4,rep,name=field_names,json=fieldNames,proto3" json:"field_names,omitempty"` // 字段列表（必填）
	StartTime     int64    `protobuf:"varint,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`   // 开始时间（Unix时间戳，秒）
	EndTime       int64    `protobuf:"varint,6,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`         // 结束时间（Unix时间戳，秒）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceStatisticsReq) Reset() {
	*x = GetDeviceStatisticsReq{}
	mi := &file_iotquery_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceStatisticsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceStatisticsReq) ProtoMessage() {}

func (x *GetDeviceStatisticsReq) ProtoReflect() protoreflect.Message {
	mi := &file_iotquery_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceStatisticsReq.ProtoReflect.Descriptor instead.
func (*GetDeviceStatisticsReq) Descriptor() ([]byte, []int) {
	return file_iotquery_proto_rawDescGZIP(), []int{7}
}

func (x *GetDeviceStatisticsReq) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetDeviceStatisticsReq) GetOrgIds() []string {
	if x != nil {
		return x.OrgIds
	}
	return nil
}

func (x *GetDeviceStatisticsReq) GetDeviceIds() []string {
	if x != nil {
		return x.DeviceIds
	}
	return nil
}

func (x *GetDeviceStatisticsReq) GetFieldNames() []string {
	if x != nil {
		return x.FieldNames
	}
	return nil
}

func (x *GetDeviceStatisticsReq) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *GetDeviceStatisticsReq) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

// GetDeviceStatisticsResp 设备统计查询响应
type GetDeviceStatisticsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Devices       []*DeviceStatistics    `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceStatisticsResp) Reset() {
	*x = GetDeviceStatisticsResp{}
	mi := &file_iotquery_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceStatisticsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceStatisticsResp) ProtoMessage() {}

func (x *GetDeviceStatisticsResp) ProtoReflect() protoreflect.Message {
	mi := &file_iotquery_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceStatisticsResp.ProtoReflect.Descriptor instead.
func (*GetDeviceStatisticsResp) Descriptor() ([]byte, []int) {
	return file_iotquery_proto_rawDescGZIP(), []int{8}
}

func (x *GetDeviceStatisticsResp) GetDevices() []*DeviceStatistics {
	if x != nil {
		return x.Devices
	}
	return nil
}

// DeviceStatistics 设备统计信息
type DeviceStatistics struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	DeviceId      string                      `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`                                                       // 设备ID
	DeviceModel   string                      `protobuf:"bytes,2,opt,name=device_model,json=deviceModel,proto3" json:"device_model,omitempty"`                                              // 设备型号
	Fields        map[string]*FieldStatistics `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 字段名 -> 统计信息映射
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceStatistics) Reset() {
	*x = DeviceStatistics{}
	mi := &file_iotquery_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceStatistics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceStatistics) ProtoMessage() {}

func (x *DeviceStatistics) ProtoReflect() protoreflect.Message {
	mi := &file_iotquery_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceStatistics.ProtoReflect.Descriptor instead.
func (*DeviceStatistics) Descriptor() ([]byte, []int) {
	return file_iotquery_proto_rawDescGZIP(), []int{9}
}

func (x *DeviceStatistics) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DeviceStatistics) GetDeviceModel() string {
	if x != nil {
		return x.DeviceModel
	}
	return ""
}

func (x *DeviceStatistics) GetFields() map[string]*FieldStatistics {
	if x != nil {
		return x.Fields
	}
	return nil
}

// FieldStatistics 字段统计信息
type FieldStatistics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Min           float64                `protobuf:"fixed64,1,opt,name=min,proto3" json:"min,omitempty"`                            // 最小值
	Max           float64                `protobuf:"fixed64,2,opt,name=max,proto3" json:"max,omitempty"`                            // 最大值
	Avg           float64                `protobuf:"fixed64,3,opt,name=avg,proto3" json:"avg,omitempty"`                            // 平均值
	Sum           float64                `protobuf:"fixed64,4,opt,name=sum,proto3" json:"sum,omitempty"`                            // 总和
	Count         int64                  `protobuf:"varint,5,opt,name=count,proto3" json:"count,omitempty"`                         // 数据点数量
	LastValue     string                 `protobuf:"bytes,6,opt,name=last_value,json=lastValue,proto3" json:"last_value,omitempty"` // 最新值（JSON格式）
	LastTime      int64                  `protobuf:"varint,7,opt,name=last_time,json=lastTime,proto3" json:"last_time,omitempty"`   // 最新值时间戳（Unix时间戳，秒）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldStatistics) Reset() {
	*x = FieldStatistics{}
	mi := &file_iotquery_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldStatistics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldStatistics) ProtoMessage() {}

func (x *FieldStatistics) ProtoReflect() protoreflect.Message {
	mi := &file_iotquery_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldStatistics.ProtoReflect.Descriptor instead.
func (*FieldStatistics) Descriptor() ([]byte, []int) {
	return file_iotquery_proto_rawDescGZIP(), []int{10}
}

func (x *FieldStatistics) GetMin() float64 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *FieldStatistics) GetMax() float64 {
	if x != nil {
		return x.Max
	}
	return 0
}

func (x *FieldStatistics) GetAvg() float64 {
	if x != nil {
		return x.Avg
	}
	return 0
}

func (x *FieldStatistics) GetSum() float64 {
	if x != nil {
		return x.Sum
	}
	return 0
}

func (x *FieldStatistics) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *FieldStatistics) GetLastValue() string {
	if x != nil {
		return x.LastValue
	}
	return ""
}

func (x *FieldStatistics) GetLastTime() int64 {
	if x != nil {
		return x.LastTime
	}
	return 0
}

var File_iotquery_proto protoreflect.FileDescriptor

const file_iotquery_proto_rawDesc = "" +
	"\n" +
	"\x0eiotquery.proto\x12\biotquery\"\xf7\x02\n" +
	"\x12QueryTimeSeriesReq\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x17\n" +
	"\aorg_ids\x18\x02 \x03(\tR\x06orgIds\x12\x1d\n" +
	"\n" +
	"device_ids\x18\x03 \x03(\tR\tdeviceIds\x12\x1f\n" +
	"\vfield_names\x18\x04 \x03(\tR\n" +
	"fieldNames\x12\x1d\n" +
	"\n" +
	"start_time\x18\x05 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x06 \x01(\x03R\aendTime\x12 \n" +
	"\vaggregation\x18\a \x01(\tR\vaggregation\x12)\n" +
	"\x10interval_seconds\x18\b \x01(\x03R\x0fintervalSeconds\x12\x14\n" +
	"\x05limit\x18\t \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\n" +
	" \x01(\x05R\x06offset\x12\x19\n" +
	"\border_by\x18\v \x01(\tR\aorderBy\x12\x1b\n" +
	"\torder_dir\x18\f \x01(\tR\borderDir\"\x92\x01\n" +
	"\x13QueryTimeSeriesResp\x124\n" +
	"\arecords\x18\x01 \x03(\v2\x1a.iotquery.TimeSeriesRecordR\arecords\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\xd7\x01\n" +
	"\x10TimeSeriesRecord\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12!\n" +
	"\fdevice_model\x18\x03 \x01(\tR\vdeviceModel\x12'\n" +
	"\x0fdevice_category\x18\x04 \x01(\tR\x0edeviceCategory\x12\x1d\n" +
	"\n" +
	"field_name\x18\x05 \x01(\tR\tfieldName\x12\x1d\n" +
	"\n" +
	"value_json\x18\x06 \x01(\tR\tvalueJson\"\x8a\x01\n" +
	"\x12GetLatestValuesReq\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x17\n" +
	"\aorg_ids\x18\x02 \x03(\tR\x06orgIds\x12\x1d\n" +
	"\n" +
	"device_ids\x18\x03 \x03(\tR\tdeviceIds\x12\x1f\n" +
	"\vfield_names\x18\x04 \x03(\tR\n" +
	"fieldNames\"M\n" +
	"\x13GetLatestValuesResp\x126\n" +
	"\adevices\x18\x01 \x03(\v2\x1c.iotquery.DeviceLatestValuesR\adevices\"\xc4\x01\n" +
	"\x12DeviceLatestValues\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12@\n" +
	"\x06fields\x18\x02 \x03(\v2(.iotquery.DeviceLatestValues.FieldsEntryR\x06fields\x1aO\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.iotquery.FieldValueR\x05value:\x028\x01\"I\n" +
	"\n" +
	"FieldValue\x12\x1d\n" +
	"\n" +
	"value_json\x18\x01 \x01(\tR\tvalueJson\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"\xc8\x01\n" +
	"\x16GetDeviceStatisticsReq\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x17\n" +
	"\aorg_ids\x18\x02 \x03(\tR\x06orgIds\x12\x1d\n" +
	"\n" +
	"device_ids\x18\x03 \x03(\tR\tdeviceIds\x12\x1f\n" +
	"\vfield_names\x18\x04 \x03(\tR\n" +
	"fieldNames\x12\x1d\n" +
	"\n" +
	"start_time\x18\x05 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x06 \x01(\x03R\aendTime\"O\n" +
	"\x17GetDeviceStatisticsResp\x124\n" +
	"\adevices\x18\x01 \x03(\v2\x1a.iotquery.DeviceStatisticsR\adevices\"\xe8\x01\n" +
	"\x10DeviceStatistics\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12!\n" +
	"\fdevice_model\x18\x02 \x01(\tR\vdeviceModel\x12>\n" +
	"\x06fields\x18\x03 \x03(\v2&.iotquery.DeviceStatistics.FieldsEntryR\x06fields\x1aT\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12/\n" +
	"\x05value\x18\x02 \x01(\v2\x19.iotquery.FieldStatisticsR\x05value:\x028\x01\"\xab\x01\n" +
	"\x0fFieldStatistics\x12\x10\n" +
	"\x03min\x18\x01 \x01(\x01R\x03min\x12\x10\n" +
	"\x03max\x18\x02 \x01(\x01R\x03max\x12\x10\n" +
	"\x03avg\x18\x03 \x01(\x01R\x03avg\x12\x10\n" +
	"\x03sum\x18\x04 \x01(\x01R\x03sum\x12\x14\n" +
	"\x05count\x18\x05 \x01(\x03R\x05count\x12\x1d\n" +
	"\n" +
	"last_value\x18\x06 \x01(\tR\tlastValue\x12\x1b\n" +
	"\tlast_time\x18\a \x01(\x03R\blastTime2\x86\x02\n" +
	"\bIoTQuery\x12N\n" +
	"\x0fQueryTimeSeries\x12\x1c.iotquery.QueryTimeSeriesReq\x1a\x1d.iotquery.QueryTimeSeriesResp\x12N\n" +
	"\x0fGetLatestValues\x12\x1c.iotquery.GetLatestValuesReq\x1a\x1d.iotquery.GetLatestValuesResp\x12Z\n" +
	"\x13GetDeviceStatistics\x12 .iotquery.GetDeviceStatisticsReq\x1a!.iotquery.GetDeviceStatisticsRespB\x1cZ\x1anexlyn/service/iotquery/pbb\x06proto3"

var (
	file_iotquery_proto_rawDescOnce sync.Once
	file_iotquery_proto_rawDescData []byte
)

func file_iotquery_proto_rawDescGZIP() []byte {
	file_iotquery_proto_rawDescOnce.Do(func() {
		file_iotquery_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_iotquery_proto_rawDesc), len(file_iotquery_proto_rawDesc)))
	})
	return file_iotquery_proto_rawDescData
}

var file_iotquery_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_iotquery_proto_goTypes = []any{
	(*QueryTimeSeriesReq)(nil),      // 0: iotquery.QueryTimeSeriesReq
	(*QueryTimeSeriesResp)(nil),     // 1: iotquery.QueryTimeSeriesResp
	(*TimeSeriesRecord)(nil),        // 2: iotquery.TimeSeriesRecord
	(*GetLatestValuesReq)(nil),      // 3: iotquery.GetLatestValuesReq
	(*GetLatestValuesResp)(nil),     // 4: iotquery.GetLatestValuesResp
	(*DeviceLatestValues)(nil),      // 5: iotquery.DeviceLatestValues
	(*FieldValue)(nil),              // 6: iotquery.FieldValue
	(*GetDeviceStatisticsReq)(nil),  // 7: iotquery.GetDeviceStatisticsReq
	(*GetDeviceStatisticsResp)(nil), // 8: iotquery.GetDeviceStatisticsResp
	(*DeviceStatistics)(nil),        // 9: iotquery.DeviceStatistics
	(*FieldStatistics)(nil),         // 10: iotquery.FieldStatistics
	nil,                             // 11: iotquery.DeviceLatestValues.FieldsEntry
	nil,                             // 12: iotquery.DeviceStatistics.FieldsEntry
}
var file_iotquery_proto_depIdxs = []int32{
	2,  // 0: iotquery.QueryTimeSeriesResp.records:type_name -> iotquery.TimeSeriesRecord
	5,  // 1: iotquery.GetLatestValuesResp.devices:type_name -> iotquery.DeviceLatestValues
	11, // 2: iotquery.DeviceLatestValues.fields:type_name -> iotquery.DeviceLatestValues.FieldsEntry
	9,  // 3: iotquery.GetDeviceStatisticsResp.devices:type_name -> iotquery.DeviceStatistics
	12, // 4: iotquery.DeviceStatistics.fields:type_name -> iotquery.DeviceStatistics.FieldsEntry
	6,  // 5: iotquery.DeviceLatestValues.FieldsEntry.value:type_name -> iotquery.FieldValue
	10, // 6: iotquery.DeviceStatistics.FieldsEntry.value:type_name -> iotquery.FieldStatistics
	0,  // 7: iotquery.IoTQuery.QueryTimeSeries:input_type -> iotquery.QueryTimeSeriesReq
	3,  // 8: iotquery.IoTQuery.GetLatestValues:input_type -> iotquery.GetLatestValuesReq
	7,  // 9: iotquery.IoTQuery.GetDeviceStatistics:input_type -> iotquery.GetDeviceStatisticsReq
	1,  // 10: iotquery.IoTQuery.QueryTimeSeries:output_type -> iotquery.QueryTimeSeriesResp
	4,  // 11: iotquery.IoTQuery.GetLatestValues:output_type -> iotquery.GetLatestValuesResp
	8,  // 12: iotquery.IoTQuery.GetDeviceStatistics:output_type -> iotquery.GetDeviceStatisticsResp
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_iotquery_proto_init() }
func file_iotquery_proto_init() {
	if File_iotquery_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_iotquery_proto_rawDesc), len(file_iotquery_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_iotquery_proto_goTypes,
		DependencyIndexes: file_iotquery_proto_depIdxs,
		MessageInfos:      file_iotquery_proto_msgTypes,
	}.Build()
	File_iotquery_proto = out.File
	file_iotquery_proto_goTypes = nil
	file_iotquery_proto_depIdxs = nil
}
