// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.4
// source: iotquery.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IoTQuery_QueryTimeSeries_FullMethodName     = "/iotquery.IoTQuery/QueryTimeSeries"
	IoTQuery_GetLatestValues_FullMethodName     = "/iotquery.IoTQuery/GetLatestValues"
	IoTQuery_GetDeviceStatistics_FullMethodName = "/iotquery.IoTQuery/GetDeviceStatistics"
)

// IoTQueryClient is the client API for IoTQuery service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// IoTQuery gRPC服务
// 提供传感器历史数据查询能力（轻量级，只依赖PostgreSQL和ClickHouse）
type IoTQueryClient interface {
	// QueryTimeSeries 查询时序数据
	// 支持原始数据查询和6种聚合类型（avg/max/min/sum/count/last）
	QueryTimeSeries(ctx context.Context, in *QueryTimeSeriesReq, opts ...grpc.CallOption) (*QueryTimeSeriesResp, error)
	// GetLatestValues 获取设备字段最新值
	// 用于实时监控和可视化大屏展示
	GetLatestValues(ctx context.Context, in *GetLatestValuesReq, opts ...grpc.CallOption) (*GetLatestValuesResp, error)
	// GetDeviceStatistics 获取设备统计信息
	// 计算指定时间范围内的min/max/avg/sum/count等统计指标
	GetDeviceStatistics(ctx context.Context, in *GetDeviceStatisticsReq, opts ...grpc.CallOption) (*GetDeviceStatisticsResp, error)
}

type ioTQueryClient struct {
	cc grpc.ClientConnInterface
}

func NewIoTQueryClient(cc grpc.ClientConnInterface) IoTQueryClient {
	return &ioTQueryClient{cc}
}

func (c *ioTQueryClient) QueryTimeSeries(ctx context.Context, in *QueryTimeSeriesReq, opts ...grpc.CallOption) (*QueryTimeSeriesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryTimeSeriesResp)
	err := c.cc.Invoke(ctx, IoTQuery_QueryTimeSeries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ioTQueryClient) GetLatestValues(ctx context.Context, in *GetLatestValuesReq, opts ...grpc.CallOption) (*GetLatestValuesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLatestValuesResp)
	err := c.cc.Invoke(ctx, IoTQuery_GetLatestValues_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ioTQueryClient) GetDeviceStatistics(ctx context.Context, in *GetDeviceStatisticsReq, opts ...grpc.CallOption) (*GetDeviceStatisticsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDeviceStatisticsResp)
	err := c.cc.Invoke(ctx, IoTQuery_GetDeviceStatistics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IoTQueryServer is the server API for IoTQuery service.
// All implementations must embed UnimplementedIoTQueryServer
// for forward compatibility.
//
// IoTQuery gRPC服务
// 提供传感器历史数据查询能力（轻量级，只依赖PostgreSQL和ClickHouse）
type IoTQueryServer interface {
	// QueryTimeSeries 查询时序数据
	// 支持原始数据查询和6种聚合类型（avg/max/min/sum/count/last）
	QueryTimeSeries(context.Context, *QueryTimeSeriesReq) (*QueryTimeSeriesResp, error)
	// GetLatestValues 获取设备字段最新值
	// 用于实时监控和可视化大屏展示
	GetLatestValues(context.Context, *GetLatestValuesReq) (*GetLatestValuesResp, error)
	// GetDeviceStatistics 获取设备统计信息
	// 计算指定时间范围内的min/max/avg/sum/count等统计指标
	GetDeviceStatistics(context.Context, *GetDeviceStatisticsReq) (*GetDeviceStatisticsResp, error)
	mustEmbedUnimplementedIoTQueryServer()
}

// UnimplementedIoTQueryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIoTQueryServer struct{}

func (UnimplementedIoTQueryServer) QueryTimeSeries(context.Context, *QueryTimeSeriesReq) (*QueryTimeSeriesResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryTimeSeries not implemented")
}
func (UnimplementedIoTQueryServer) GetLatestValues(context.Context, *GetLatestValuesReq) (*GetLatestValuesResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLatestValues not implemented")
}
func (UnimplementedIoTQueryServer) GetDeviceStatistics(context.Context, *GetDeviceStatisticsReq) (*GetDeviceStatisticsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeviceStatistics not implemented")
}
func (UnimplementedIoTQueryServer) mustEmbedUnimplementedIoTQueryServer() {}
func (UnimplementedIoTQueryServer) testEmbeddedByValue()                  {}

// UnsafeIoTQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IoTQueryServer will
// result in compilation errors.
type UnsafeIoTQueryServer interface {
	mustEmbedUnimplementedIoTQueryServer()
}

func RegisterIoTQueryServer(s grpc.ServiceRegistrar, srv IoTQueryServer) {
	// If the following call pancis, it indicates UnimplementedIoTQueryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IoTQuery_ServiceDesc, srv)
}

func _IoTQuery_QueryTimeSeries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryTimeSeriesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IoTQueryServer).QueryTimeSeries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IoTQuery_QueryTimeSeries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IoTQueryServer).QueryTimeSeries(ctx, req.(*QueryTimeSeriesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IoTQuery_GetLatestValues_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLatestValuesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IoTQueryServer).GetLatestValues(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IoTQuery_GetLatestValues_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IoTQueryServer).GetLatestValues(ctx, req.(*GetLatestValuesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IoTQuery_GetDeviceStatistics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeviceStatisticsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IoTQueryServer).GetDeviceStatistics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IoTQuery_GetDeviceStatistics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IoTQueryServer).GetDeviceStatistics(ctx, req.(*GetDeviceStatisticsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// IoTQuery_ServiceDesc is the grpc.ServiceDesc for IoTQuery service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IoTQuery_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "iotquery.IoTQuery",
	HandlerType: (*IoTQueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryTimeSeries",
			Handler:    _IoTQuery_QueryTimeSeries_Handler,
		},
		{
			MethodName: "GetLatestValues",
			Handler:    _IoTQuery_GetLatestValues_Handler,
		},
		{
			MethodName: "GetDeviceStatistics",
			Handler:    _IoTQuery_GetDeviceStatistics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "iotquery.proto",
}
