// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AddOrganizationMemberRequest struct {
	OrganizationMemberPathRequest
	UserId        string `json:"userId"`                 // 用户ID（必填）
	RelationType  string `json:"relationType,optional"`  // 关系类型（默认member）
	PositionTitle string `json:"positionTitle,optional"` // 职位标题
	IsPrimary     bool   `json:"isPrimary,optional"`     // 是否主要关系（默认false）
}

type AddOrganizationMemberResponse struct {
	BaseResponse
}

type AddPermissionRequest struct {
	UserKey   string `json:"userKey"`   // 用户Key
	TenantKey string `json:"tenantKey"` // 租户ID
	Resource  string `json:"resource"`  // 资源 (如: user:read, graph:write)
	Action    string `json:"action"`    // 操作 (read, write, delete, admin)
}

type AddPermissionResponse struct {
	BaseResponse
}

type AddRoleForUserResponse struct {
	BaseResponse
}

type AddRolePermissionRequest struct {
	RoleKey   string `json:"roleKey"`   // 角色键
	Resource  string `json:"resource"`  // 资源
	Action    string `json:"action"`    // 操作
	TenantKey string `json:"tenantKey"` // 租户ID（*表示所有租户）
}

type AddRolePermissionResponse struct {
	BaseResponse
}

type AddRoleRequest struct {
	UserKey   string `json:"userKey"`   // 用户Key
	RoleKey   string `json:"roleKey"`   // 角色键 (super_admin, admin, user)
	TenantKey string `json:"tenantKey"` // 租户ID
}

type BaseResponse struct {
	Code int64  `json:"code"`          // 响应码
	Msg  string `json:"msg,omitempty"` // 响应消息
}

type BindOrganizationRequest struct {
	Id          string `path:"id"`          // 组织ID（路径参数）
	RemoteOrgId int32  `json:"remoteOrgId"` // 远程组织ID
}

type BindOrganizationResponse struct {
	BaseResponse
}

type BindUserRequest struct {
	Id           string `path:"id"`           // 用户ID（路径参数）
	RemoteUserId int32  `json:"remoteUserId"` // 远程用户ID
}

type BindUserResponse struct {
	BaseResponse
}

type BlockKey struct {
	BlockType LogicBlockType `json:"blockType"` // 逻辑块类型
	Version   string         `json:"version"`   // 版本，允许为空表示默认版本
}

type BlockKeyListData struct {
	List []BlockKey `json:"list"` // 逻辑块键列表
}

type ChangePasswordRequest struct {
	OldPassword string `json:"oldPassword"` // 旧密码
	NewPassword string `json:"newPassword"` // 新密码
}

type ChangePasswordResponse struct {
	BaseResponse
}

type CheckInfoAtomTypeRequest struct {
	InfoAtomTypeIdPathRequest
}

type CheckInfoAtomTypeResponse struct {
	BaseResponse
	Data struct {
		Exists bool `json:"exists"` // 是否存在
	} `json:"data,omitempty"`
}

type CheckPermissionRequest struct {
	UserKey   string `json:"userKey"`   // 用户Key
	TenantKey string `json:"tenantKey"` // 租户Key
	Resource  string `json:"resource"`  // 资源
	Action    string `json:"action"`    // 操作
}

type CheckPermissionResponse struct {
	BaseResponse
	HasPermission bool `json:"hasPermission"` // 是否有权限
}

type CreateGraphConfigRequest struct {
	TenantId    string       `json:"tenantId"`    // 租户ID
	Name        string       `json:"name"`        // 图的名称
	Version     string       `json:"version"`     // 图的版本
	Description string       `json:"description"` // 图的描述
	Tags        []string     `json:"tags"`        // 标签，用于分类
	Enable      bool         `json:"enable"`      // 图是否启用
	Nodes       []NodeConfig `json:"nodes"`       // 图中的节点
	Edges       []EdgeConfig `json:"edges"`       // 图中的边
}

type CreateGraphConfigResponse struct {
	BaseResponse
	Data struct {
		ID string `json:"id"` // 新创建的图配置ID
	} `json:"data,omitempty"`
}

type CreateInfoAtomTypeRequest struct {
	TenantId   string     `json:"tenantId"`   // 租户ID
	Name       string     `json:"name"`       // Type 名称，如 "face.detected"
	Version    string     `json:"version"`    // 版本，便于灰度/演进
	Tags       []string   `json:"tags"`       // 标签，用于分类
	DataFormat DataFormat `json:"dataFormat"` // 数据格式
}

type CreateInfoAtomTypeResponse struct {
	BaseResponse
	Data struct {
		ID string `json:"id"` // 新创建的信息原子类型ID
	} `json:"data,omitempty"`
}

type CreateOrganizationRequest struct {
	Code        string `json:"code"`                 // 组织代码（必填）
	Name        string `json:"name"`                 // 组织名称（必填）
	Type        string `json:"type,optional"`        // 组织类型（默认department）
	Description string `json:"description,optional"` // 描述
	ParentId    string `json:"parentId,optional"`    // 父组织ID（为空则创建为根组织）
	SortOrder   int    `json:"sortOrder,optional"`   // 排序（默认0）
	ManagerId   string `json:"managerId,optional"`   // 负责人ID
	Status      string `json:"status,optional"`      // 状态（默认active）
}

type CreateOrganizationResponse struct {
	BaseResponse
	Data struct {
		Id   string `json:"id"`   // 新创建的组织ID
		Code string `json:"code"` // 组织代码
		Path string `json:"path"` // 路径编码
	} `json:"data,omitempty"`
}

type CreateRoleRequest struct {
	RoleKey     string   `json:"roleKey"`              // 角色键
	RoleName    string   `json:"roleName"`             // 角色显示名称
	Description string   `json:"description,optional"` // 角色描述
	Permissions []string `json:"permissions"`          // 角色权限列表
}

type CreateRoleResponse struct {
	BaseResponse
}

type CreateTagRequest struct {
	Scope       string `json:"scope"`                // tenant | user（必填）
	Label       string `json:"label"`                // 必填
	Description string `json:"description,optional"` // 可选
}

type CreateTagResponse struct {
	BaseResponse
	Data struct {
		Id string `json:"id"`
	} `json:"data,omitempty"`
}

type CreateTenantRequest struct {
	TenantKey     string   `json:"tenantKey"`              // 租户唯一标识符
	TenantName    string   `json:"tenantName"`             // 租户名称（必填）
	Description   string   `json:"description,optional"`   // 描述
	Tags          []string `json:"tags,optional"`          // 标签
	ContactEmail  string   `json:"contactEmail,optional"`  // 联系邮箱
	Status        string   `json:"status,optional"`        // 初始状态（默认active）
	MaxUsers      int      `json:"maxUsers,optional"`      // 用户数量限制（默认100）
	ExpiresAt     string   `json:"expiresAt,optional"`     // 过期时间（ISO 8601）
	AdminUserName string   `json:"adminUserName,optional"` // 管理员用户名（默认admin）
	AdminName     string   `json:"adminName,optional"`     // 管理员显示名称
	AdminEmail    string   `json:"adminEmail,optional"`    // 管理员邮箱
	AdminPassword string   `json:"adminPassword,optional"` // 管理员密码（可选，不提供则生成随机密码）
	AdminRoleKey  string   `json:"adminRoleKey"`           // 管理员角色（必填，必须是不包含租户管理权限的角色）
}

type CreateTenantResponse struct {
	BaseResponse
	Data struct {
		TenantKey     string `json:"tenantKey"`               // 租户业务标识符
		TenantId      string `json:"tenantId"`                // 租户UUID
		TenantName    string `json:"tenantName"`              // 租户名称
		AdminUserKey  string `json:"adminUserKey,omitempty"`  // 管理员用户Key
		AdminUserName string `json:"adminUserName,omitempty"` // 管理员用户名
		AdminPassword string `json:"adminPassword,omitempty"` // 管理员初始密码（如果是生成的）
	} `json:"data,omitempty"`
}

type CreateUserData struct {
	UserKey  string `json:"userKey"`  // 新创建的用户Key
	UserName string `json:"userName"` // 用户名
	Password string `json:"password"` // 临时密码
}

type CreateUserRequest struct {
	UserName   string         `json:"userName"`            // 用户名
	Email      string         `json:"email"`               // 电子邮件
	Name       string         `json:"name"`                // 用户姓名
	TenantId   string         `json:"tenantId"`            // 租户ID
	Phone      string         `json:"phone,optional"`      // 电话号码
	Title      string         `json:"title,optional"`      // 职位
	Avatar     string         `json:"avatar,optional"`     // 用户头像 URL
	Signature  string         `json:"signature,optional"`  // 签名
	Country    string         `json:"country,optional"`    // 国家
	Address    string         `json:"address,optional"`    // 地址
	TagIds     []string       `json:"tagIds,optional"`     // 标签ID列表
	Geographic UserGeographic `json:"geographic,optional"` // 地理信息
}

type CreateUserResponse struct {
	BaseResponse
	Data CreateUserData `json:"data,omitempty"` // 创建结果数据
}

type DataFormat struct {
	DataPlural bool          `json:"dataPlural"` // 数据是否为复数
	FieldStart string        `json:"fieldStart"` // 数据是复数时，数组的字段
	Fields     []FieldConfig `json:"fields"`     // 字段配置列表
}

type DeleteGraphConfigRequest struct {
	GraphConfigIdPathRequest
}

type DeleteGraphConfigResponse struct {
	BaseResponse
}

type DeleteInfoAtomTypeRequest struct {
	InfoAtomTypeIdPathRequest
}

type DeleteInfoAtomTypeResponse struct {
	BaseResponse
}

type DeleteOrganizationRequest struct {
	OrganizationIdPathRequest
	ForceDelete bool `json:"forceDelete,optional"` // 强制删除（级联删除子组织，默认false）
}

type DeleteOrganizationResponse struct {
	BaseResponse
	Data struct {
		DeletedCount int `json:"deletedCount"` // 删除的组织数量（包含子组织）
	} `json:"data,omitempty"`
}

type DeleteRoleRequest struct {
	RoleKey string `path:"roleKey"` // 角色键
}

type DeleteRoleResponse struct {
	BaseResponse
}

type DeleteTagRequest struct {
	TagIdPathRequest
}

type DeleteTagResponse struct {
	BaseResponse
}

type DeleteTenantRequest struct {
	TenantIdPathRequest
}

type DeleteTenantResponse struct {
	BaseResponse
}

type DeleteUserRequest struct {
	UserIdPathRequest
}

type DeleteUserResponse struct {
	BaseResponse
}

type EdgeConfig struct {
	ID        string `json:"id"`        // 边的唯一标识符
	SourceID  string `json:"sourceId"`  // 边的源节点ID
	TargetID  string `json:"targetId"`  // 边的目标节点ID
	Condition string `json:"condition"` // 边的条件表达式
}

type FieldConfig struct {
	FieldKey  string    `json:"fieldKey"`  // 字段键
	FieldPath string    `json:"fieldPath"` // 字段路径
	FieldType FieldType `json:"fieldType"` // 字段类型
}

type FieldType struct {
	Value string `json:"value"` // string, int, float, bool
}

type GetAvailablePermissionsResponse struct {
	BaseResponse
	Data []PermissionItem `json:"data"` // 权限项列表
}

type GetBlockKeyAllRequest struct {
}

type GetBlockKeyAllResponse struct {
	BaseResponse
	Data BlockKeyListData `json:"data,omitempty"` // 逻辑块键列表数据
}

type GetCurrentUserResponse struct {
	BaseResponse
	Data User `json:"data,omitempty"` // 完整用户数据
}

type GetGraphConfigListRequest struct {
	PageParamsRequest
	TenantId string   `form:"tenantId,optional"` // 租户ID筛选
	Name     string   `form:"name,optional"`     // 名称模糊查询
	Tags     []string `form:"tags,optional"`     // 标签筛选
	Enable   *bool    `form:"enable,optional"`   // 启用状态筛选
}

type GetGraphConfigListResponse struct {
	BaseResponse
	PageParams
	Data GraphConfigListData `json:"data,omitempty"` // 图配置列表数据
}

type GetGraphConfigRequest struct {
	GraphConfigIdPathRequest
}

type GetGraphConfigResponse struct {
	BaseResponse
	Data GraphConfig `json:"data,omitempty"` // 图配置数据
}

type GetInfoAtomTypeListRequest struct {
	PageParamsRequest
	TenantId string   `form:"tenantId,optional"` // 租户ID过滤
	Name     string   `form:"name,optional"`     // 名称过滤
	Tags     []string `form:"tags,optional"`     // 标签过滤，包含任一标签的记录
}

type GetInfoAtomTypeListResponse struct {
	BaseResponse
	PageParams
	Data InfoAtomTypeListData `json:"data,omitempty"` // 信息原子类型列表数据
}

type GetInfoAtomTypeRequest struct {
	InfoAtomTypeIdPathRequest
}

type GetInfoAtomTypeResponse struct {
	BaseResponse
	Data InfoAtomType `json:"data,omitempty"` // 信息原子类型数据
}

type GetOrgSyncStatusRequest struct {
	OrgIds []string `form:"orgIds"` // 组织ID列表
}

type GetOrgSyncStatusResponse struct {
	BaseResponse
	Data struct {
		SyncStatus map[string]bool `json:"syncStatus"` // key: 组织ID, value: 是否已同步
	} `json:"data,omitempty"`
}

type GetOrganizationListRequest struct {
	PageParamsRequest
	Code     string `form:"code,optional" db:"code"`          // 组织代码
	Name     string `form:"name,optional" db:"name"`          // 组织名称模糊查询
	Type     string `form:"type,optional" db:"type"`          // 组织类型
	Status   string `form:"status,optional" db:"status"`      // 状态过滤
	ParentId string `form:"parentId,optional" db:"parent_id"` // 父组织ID
	Level    int    `form:"level,optional" db:"level"`        // 层级过滤
	TenantId string `form:"tenantId,optional" db:"tenant_id"` // 租户ID
}

type GetOrganizationListResponse struct {
	BaseResponse
	PageParams
	Data OrganizationListData `json:"data,omitempty"` // 组织列表数据
}

type GetOrganizationMembersRequest struct {
	OrganizationMemberPathRequest
	PageParamsRequest
	Keyword      string `form:"keyword,optional"`      // 关键字搜索（用户名、姓名、邮箱）
	RelationType string `form:"relationType,optional"` // 关系类型过滤（manager/member）
	IsPrimary    bool   `form:"isPrimary,optional"`    // 是否主要关系过滤
}

type GetOrganizationMembersResponse struct {
	BaseResponse
	PageParams
	Data OrganizationMembersData `json:"data,omitempty"` // 成员列表数据
}

type GetOrganizationOptionsRequest struct {
	TenantId string `form:"tenantId,optional"` // 租户ID过滤（超级管理员可指定）
	Keyword  string `form:"keyword,optional"`  // 关键字搜索（组织名称、代码）
	ParentId string `form:"parentId,optional"` // 父组织ID过滤
	Type     string `form:"type,optional"`     // 组织类型过滤
	Limit    int64  `form:"limit,optional"`    // 限制数量（默认50）
}

type GetOrganizationOptionsResponse struct {
	BaseResponse
	Data struct {
		List []OrganizationOption `json:"list"` // 组织选项列表
	} `json:"data,omitempty"`
}

type GetOrganizationRequest struct {
	OrganizationIdPathRequest
}

type GetOrganizationResponse struct {
	BaseResponse
	Data Organization `json:"data,omitempty"` // 组织详情数据
}

type GetOrganizationTreeRequest struct {
	TenantId string `form:"tenantId,optional"` // 租户ID过滤（超级管理员可指定）
	RootId   string `form:"rootId,optional"`   // 根节点ID（默认为租户根组织）
}

type GetOrganizationTreeResponse struct {
	BaseResponse
	Data []OrganizationTree `json:"data,omitempty"` // 组织树数据
}

type GetPermissionRulesRequest struct {
	UserKey   string `form:"userKey,optional"`  // 用户Key筛选
	TenantKey string `form:"tenantId,optional"` // 租户ID筛选
	Resource  string `form:"resource,optional"` // 资源筛选
	Action    string `form:"action,optional"`   // 操作筛选
	Ptype     string `form:"ptype,optional"`    // 规则类型筛选
	PageParamsRequest
}

type GetPermissionRulesResponse struct {
	BaseResponse
	Data []PermissionRule `json:"data"` // 权限规则列表
	PageParams
}

type GetRoleListRequest struct {
	RoleKey  string `form:"roleKey,optional"`  // 角色键筛选
	RoleName string `form:"roleName,optional"` // 角色名称筛选
	PageParamsRequest
}

type GetRoleListResponse struct {
	BaseResponse
	Data []RoleInfo `json:"data"` // 角色列表
	PageParams
}

type GetRoleRequest struct {
	RoleKey string `path:"roleKey"` // 角色键
}

type GetRoleResponse struct {
	BaseResponse
	Data RoleInfo `json:"data"` // 角色信息
}

type GetTagListRequest struct {
	PageParamsRequest
	Scope   string `form:"scope" db:"scope"` // 必填：tenant | user
	Keyword string `form:"keyword,optional"` // 模糊搜索
}

type GetTagListResponse struct {
	BaseResponse
	PageParams
	Data TagListData `json:"data,omitempty"`
}

type GetTagOptionsRequest struct {
	Scope   string `form:"scope"`
	Keyword string `form:"keyword,optional"`
	Limit   int64  `form:"limit,optional"`
}

type GetTagOptionsResponse struct {
	BaseResponse
	Data struct {
		List []TagOption `json:"list"`
	} `json:"data,omitempty"`
}

type GetTagRequest struct {
	TagIdPathRequest
}

type GetTagResponse struct {
	BaseResponse
	Data TagDefinition `json:"data,omitempty"`
}

type GetTenantListRequest struct {
	PageParamsRequest
	Id         string   `form:"id,optional" db:"id"`                  // 租户UUID
	TenantKey  string   `form:"tenantKey,optional" db:"tenant_key"`   // 租户唯一标识符
	TenantName string   `form:"tenantName,optional" db:"tenant_name"` // 名称模糊查询
	Status     string   `form:"status,optional" db:"status"`          // 状态过滤（字符串类型）
	Tags       []string `form:"tags,optional" "`                      // 多标签过滤（包含任一）
}

type GetTenantListResponse struct {
	BaseResponse
	PageParams
	Data TenantListData `json:"data,omitempty"` // 列表数据
}

type GetTenantOptionsRequest struct {
	Keyword string `form:"keyword,optional"` // 关键字搜索（租户名称）
	Limit   int64  `form:"limit,optional"`   // 限制数量（默认20）
	Status  string `form:"status,optional"`  // 状态过滤
}

type GetTenantOptionsResponse struct {
	BaseResponse
	Data struct {
		List []TenantOption `json:"list"` // 租户选项列表
	} `json:"data,omitempty"`
}

type GetTenantRequest struct {
	TenantIdPathRequest
}

type GetTenantResponse struct {
	BaseResponse
	Data Tenant `json:"data,omitempty"` // 租户数据
}

type GetUserByIdRequest struct {
	UserIdPathRequest
}

type GetUserByIdResponse struct {
	BaseResponse
	Data User `json:"data,omitempty"` // 完整用户数据
}

type GetUserListRequest struct {
	PageParamsRequest
	Ids      []string `form:"ids,optional"`                     // 用户ID列表
	Name     string   `form:"name,optional" db:"name"`          // 用户姓名
	Email    string   `form:"email,optional" db:"email"`        // 电子邮件
	UserName string   `form:"userName,optional" db:"user_name"` // 用户名
	Status   string   `form:"status,optional" db:"status"`      // 用户状态
	TenantId string   `form:"tenantId,optional" db:"tenant_id"` // 租户ID
	TagIds   []string `form:"tagIds,optional"`
}

type GetUserListResponse struct {
	BaseResponse
	PageParams
	Data UserListData `json:"data,omitempty"` // 用户列表数据
}

type GetUserOptionsRequest struct {
	TenantId string `form:"tenantId,optional"` // 租户ID过滤
	Keyword  string `form:"keyword,optional"`  // 关键字搜索（用户名、姓名、邮箱）
	Limit    int64  `form:"limit,optional"`    // 限制数量（默认20）
}

type GetUserOptionsResponse struct {
	BaseResponse
	Data struct {
		List []UserOption `json:"list"` // 用户选项列表
	} `json:"data,omitempty"`
}

type GetUserOrganizationsRequest struct {
	Id        string `path:"id"`                 // 用户ID（路径参数）
	IsPrimary bool   `form:"isPrimary,optional"` // 是否只返回主要关系
}

type GetUserOrganizationsResponse struct {
	BaseResponse
	Data struct {
		List []UserOrgRelation `json:"list"` // 用户组织关系列表
	} `json:"data,omitempty"`
}

type GetUserPermissionsResponse struct {
	BaseResponse
	Permissions []string `json:"permissions"` // 权限列表
	Roles       []string `json:"roles"`       // 角色列表
}

type GetUserSyncStatusRequest struct {
	UserIds []string `form:"userIds"` // 用户ID列表
}

type GetUserSyncStatusResponse struct {
	BaseResponse
	Data struct {
		SyncStatus map[string]bool `json:"syncStatus"` // key: 用户ID, value: 是否已同步
	} `json:"data,omitempty"`
}

type GraphConfig struct {
	ID          string       `json:"id"`          // 图的唯一标识符
	TenantId    string       `json:"tenantId"`    // 租户ID
	Name        string       `json:"name"`        // 图的名称
	Version     string       `json:"version"`     // 图的版本
	Description string       `json:"description"` // 图的描述
	Tags        []string     `json:"tags"`        // 标签，用于分类
	Enable      bool         `json:"enable"`      // 图是否启用
	Nodes       []NodeConfig `json:"nodes"`       // 图中的节点
	Edges       []EdgeConfig `json:"edges"`       // 图中的边
	CreatedAt   int64        `json:"createdAt"`   // 创建时间（Unix时间戳）
	UpdatedAt   int64        `json:"updatedAt"`   // 更新时间（Unix时间戳）
}

type GraphConfigIdPathRequest struct {
	Id string `path:"id"` // 图配置ID
}

type GraphConfigListData struct {
	List []GraphConfig `json:"list"` // 图配置列表
}

type InfoAtomType struct {
	ID         string     `json:"id"`         // 信息原子类型ID
	TenantId   string     `json:"tenantId"`   // 租户ID
	Name       string     `json:"name"`       // Type 名称，如 "face.detected"
	Version    string     `json:"version"`    // 版本，便于灰度/演进
	Tags       []string   `json:"tags"`       // 标签，用于分类
	DataFormat DataFormat `json:"dataFormat"` // 数据格式
	CreatedAt  int64      `json:"createdAt"`  // 创建时间（Unix时间戳）
	UpdatedAt  int64      `json:"updatedAt"`  // 更新时间（Unix时间戳）
}

type InfoAtomTypeIdPathRequest struct {
	Id string `path:"id"` // 信息原子类型ID
}

type InfoAtomTypeListData struct {
	List []InfoAtomType `json:"list"` // 信息原子类型列表
}

type LogicBlockType struct {
	Value string `json:"value"` // 逻辑块类型值，如 filter, state_machine, action 等
}

type LoginRequest struct {
	UserName  string `json:"userName,optional"`  // 用户名
	Password  string `json:"password,optional"`  // 密码
	AutoLogin bool   `json:"autoLogin,optional"` // 是否自动登录
	Type      string `json:"type,optional"`      // 登录类型
}

type LoginResponse struct {
	BaseResponse
	Status string `json:"status,omitempty"` // 登录状态
	Type   string `json:"type,omitempty"`   // 登录类型
	Token  string `json:"token,omitempty"`  // 认证令牌
}

type MoveOrganizationRequest struct {
	OrganizationIdPathRequest
	NewParentId  string `json:"newParentId"`           // 新父组织ID（null表示移动到根级）
	NewSortOrder int    `json:"newSortOrder,optional"` // 新排序（可选）
}

type MoveOrganizationResponse struct {
	BaseResponse
	Data struct {
		NewPath string `json:"newPath"` // 新路径编码
	} `json:"data,omitempty"`
}

type NodeConfig struct {
	ID                        string                 `json:"id"`                        // 节点的唯一标识符
	Type                      NodeType               `json:"type"`                      // 节点类型
	BlockType                 LogicBlockType         `json:"blockType"`                 // 节点关联的逻辑块类型
	BlockVersion              string                 `json:"blockVersion"`              // 节点关联的逻辑块版本
	BlockConfig               map[string]interface{} `json:"blockConfig"`               // 节点关联的逻辑块配置
	IsEntryPoint              bool                   `json:"isEntryPoint"`              // 是否为入口节点
	SubscribedInfoAtomTypeIDs []string               `json:"subscribedInfoAtomTypeIds"` // 订阅的信息原子类型ID列表
	SubscribedSource          string                 `json:"subscribedSource"`          // 节点订阅的信息原子来源
	SubscribedLabels          map[string]string      `json:"subscribedLabels"`          // 节点的标签
}

type NodeType struct {
	Value string `json:"value"` // 节点类型值
}

type Organization struct {
	Id          string  `json:"id"`                    // 组织UUID（内部标识）
	Code        string  `json:"code"`                  // 组织代码（业务标识）
	Name        string  `json:"name"`                  // 组织名称
	Type        string  `json:"type"`                  // 组织类型（company/department/team等）
	Description *string `json:"description,omitempty"` // 描述（可为空）
	Path        string  `json:"path"`                  // 路径编码（/root/parent_id/current_id/）
	ParentId    *string `json:"parentId,omitempty"`    // 父组织ID（可为空）
	Level       int     `json:"level"`                 // 层级（1-10）
	SortOrder   int     `json:"sortOrder"`             // 排序
	ManagerId   *string `json:"managerId,omitempty"`   // 负责人ID（可为空）
	ManagerName *string `json:"managerName,omitempty"` // 负责人姓名（可为空）
	MemberCount int     `json:"memberCount"`           // 成员数量
	Status      string  `json:"status"`                // 状态（active/inactive/deleted）
	TenantId    string  `json:"tenantId"`              // 租户ID
	CreatedBy   *string `json:"createdBy,omitempty"`   // 创建者（可为空）
	UpdatedBy   *string `json:"updatedBy,omitempty"`   // 更新者（可为空）
	CreatedAt   string  `json:"createdAt"`             // 创建时间
	UpdatedAt   string  `json:"updatedAt"`             // 更新时间
}

type OrganizationBrief struct {
	Id          string  `json:"id"`                    // 组织UUID
	Code        string  `json:"code"`                  // 组织代码
	Name        string  `json:"name"`                  // 组织名称
	Type        string  `json:"type"`                  // 组织类型
	Path        string  `json:"path"`                  // 路径编码
	ParentId    *string `json:"parentId,omitempty"`    // 父组织ID（可为空）
	Level       int     `json:"level"`                 // 层级
	ManagerName *string `json:"managerName,omitempty"` // 负责人姓名（可为空）
	MemberCount int     `json:"memberCount"`           // 成员数量
	Status      string  `json:"status"`                // 状态
}

type OrganizationIdPathRequest struct {
	Id string `path:"id"` // 组织ID
}

type OrganizationListData struct {
	List []OrganizationBrief `json:"list"` // 组织简要信息列表
}

type OrganizationMemberPathRequest struct {
	Id string `path:"id"` // 组织ID
}

type OrganizationMembersData struct {
	List []UserOrgRelation `json:"list"` // 成员关系列表
}

type OrganizationOption struct {
	Id     string `json:"id"`     // 组织UUID
	Code   string `json:"code"`   // 组织代码
	Name   string `json:"name"`   // 组织名称
	Path   string `json:"path"`   // 路径编码
	Level  int    `json:"level"`  // 层级
	Status string `json:"status"` // 状态
}

type OrganizationTree struct {
	Organization
	Children []OrganizationTree `json:"children"` // 子组织
}

type PageParams struct {
	Current  int64 `json:"current,omitempty"`  // 当前页码
	PageSize int64 `json:"pageSize,omitempty"` // 每页大小
	Total    int64 `json:"total,omitempty"`    // 总记录数
}

type PageParamsRequest struct {
	Current  int64 `form:"current,optional"`  // 当前页码
	PageSize int64 `form:"pageSize,optional"` // 每页大小
}

type PermissionItem struct {
	Resource    string `json:"resource"`    // 资源
	Action      string `json:"action"`      // 操作
	Description string `json:"description"` // 权限描述
	Category    string `json:"category"`    // 权限分类
}

type PermissionRule struct {
	Ptype     string `json:"ptype"`             // 规则类型 (p, g)
	UserKey   string `json:"userKey"`           // 用户Key
	TenantKey string `json:"tenantKey"`         // 租户ID
	Resource  string `json:"resource"`          // 资源
	Action    string `json:"action"`            // 操作
	RoleKey   string `json:"roleKey,omitempty"` // 角色键 (用于角色关联规则)
}

type RemoveOrganizationMemberRequest struct {
	UserOrgPathRequest
}

type RemoveOrganizationMemberResponse struct {
	BaseResponse
}

type RemovePermissionRequest struct {
	UserKey   string `json:"userKey"`   // 用户Key
	TenantKey string `json:"tenantKey"` // 租户ID
	Resource  string `json:"resource"`  // 资源
	Action    string `json:"action"`    // 操作
}

type RemovePermissionResponse struct {
	BaseResponse
}

type RemoveRoleForUserResponse struct {
	BaseResponse
}

type RemoveRolePermissionRequest struct {
	RoleKey   string `json:"roleKey"`   // 角色键
	Resource  string `json:"resource"`  // 资源
	Action    string `json:"action"`    // 操作
	TenantKey string `json:"tenantKey"` // 租户ID
}

type RemoveRolePermissionResponse struct {
	BaseResponse
}

type RemoveRoleRequest struct {
	UserKey   string `json:"userKey"`   // 用户Key
	RoleKey   string `json:"roleKey"`   // 角色键
	TenantKey string `json:"tenantKey"` // 租户ID
}

type ResetPasswordRequest struct {
	UserIdPathRequest
	Password string `json:"password"` // 新密码
}

type ResetPasswordResponse struct {
	BaseResponse
}

type RoleInfo struct {
	RoleKey     string   `json:"roleKey"`     // 角色键
	RoleName    string   `json:"roleName"`    // 角色显示名称
	Description string   `json:"description"` // 角色描述
	Permissions []string `json:"permissions"` // 角色拥有的权限列表
}

type SyncHealthCheckResponse struct {
	BaseResponse
	Data struct {
		Healthy bool `json:"healthy"` // 服务是否健康
	} `json:"data,omitempty"`
}

type SyncOrganizationRequest struct {
	Id string `path:"id"` // 组织ID（路径参数）
}

type SyncOrganizationResponse struct {
	BaseResponse
	Data struct {
		RemoteOrgId string `json:"remoteOrgId"` // Skylark组织ID
	} `json:"data,omitempty"`
}

type SyncUserRequest struct {
	Id string `path:"id"` // 用户ID（路径参数）
}

type SyncUserResponse struct {
	BaseResponse
	Data struct {
		RemoteUserId string `json:"remoteUserId"` // Skylark用户ID
	} `json:"data,omitempty"`
}

type TagDefinition struct {
	Id          string `json:"id"`
	Scope       string `json:"scope"`       // tenant | user
	Label       string `json:"label"`       // 标签名称
	Description string `json:"description"` // 描述
	CreatedAt   int64  `json:"createdAt"`
	UpdatedAt   int64  `json:"updatedAt"`
}

type TagIdPathRequest struct {
	Id string `path:"id"`
}

type TagListData struct {
	List []TagDefinition `json:"list"`
}

type TagOption struct {
	Id    string `json:"id"`
	Label string `json:"label"`
	Count int64  `json:"count"`
}

type Tenant struct {
	Id           string   `json:"id"`           // 租户UUID（内部标识）
	TenantKey    string   `json:"tenantKey"`    // 租户唯一标识符（业务标识）
	TenantName   string   `json:"tenantName"`   // 租户名称
	Description  string   `json:"description"`  // 描述
	Tags         []string `json:"tags"`         // 标签（通过关联查询）
	ContactEmail string   `json:"contactEmail"` // 联系邮箱
	Status       string   `json:"status"`       // 状态：active/inactive/deleted
	CreatedAt    string   `json:"createdAt"`    // 创建时间（ISO 8601）
	UpdatedAt    string   `json:"updatedAt"`    // 更新时间（ISO 8601）
	ExpiresAt    string   `json:"expiresAt"`    // 过期时间（ISO 8601）
	CreatedBy    string   `json:"createdBy"`    // 创建者用户ID
	UpdatedBy    string   `json:"updatedBy"`    // 最后修改者用户ID
	MaxUsers     int      `json:"maxUsers"`     // 用户数量限制
}

type TenantIdPathRequest struct {
	Id string `path:"id"` // 租户唯一标识符
}

type TenantInfo struct {
	TenantKey  string `json:"tenantKey"`  // 租户业务标识符
	TenantId   string `json:"tenantId"`   // 租户ID
	TenantName string `json:"tenantName"` // 租户名称
}

type TenantListData struct {
	List []Tenant `json:"list"` // 租户列表
}

type TenantOption struct {
	TenantKey  string `json:"tenantKey"`  // 租户业务标识符
	TenantId   string `json:"tenantId"`   // 租户UUID
	TenantName string `json:"tenantName"` // 租户名称
	Status     string `json:"status"`     // 状态
}

type UnbindOrganizationRequest struct {
	Id string `path:"id"` // 组织ID（路径参数）
}

type UnbindOrganizationResponse struct {
	BaseResponse
}

type UnbindUserRequest struct {
	Id string `path:"id"` // 用户ID（路径参数）
}

type UnbindUserResponse struct {
	BaseResponse
}

type UpdateCurrentUserRequest struct {
	Name      string `json:"name,optional"`      // 用户姓名
	Email     string `json:"email,optional"`     // 电子邮件
	Phone     string `json:"phone,optional"`     // 电话号码
	Title     string `json:"title,optional"`     // 职位
	Avatar    string `json:"avatar,optional"`    // 用户头像 URL
	Signature string `json:"signature,optional"` // 签名
}

type UpdateCurrentUserResponse struct {
	BaseResponse
}

type UpdateGraphConfigRequest struct {
	GraphConfigIdPathRequest
	TenantId    string       `json:"tenantId,optional"`    // 租户ID
	Name        string       `json:"name,optional"`        // 图的名称
	Version     string       `json:"version,optional"`     // 图的版本
	Description string       `json:"description,optional"` // 图的描述
	Tags        []string     `json:"tags,optional"`        // 标签，用于分类
	Enable      *bool        `json:"enable,optional"`      // 图是否启用
	Nodes       []NodeConfig `json:"nodes,optional"`       // 图中的节点
	Edges       []EdgeConfig `json:"edges,optional"`       // 图中的边
}

type UpdateGraphConfigResponse struct {
	BaseResponse
}

type UpdateInfoAtomTypeRequest struct {
	InfoAtomTypeIdPathRequest
	TenantId   string     `json:"tenantId,optional"`   // 租户ID
	Name       string     `json:"name,optional"`       // Type 名称，如 "face.detected"
	Version    string     `json:"version,optional"`    // 版本，便于灰度/演进
	Tags       []string   `json:"tags,optional"`       // 标签，用于分类
	DataFormat DataFormat `json:"dataFormat,optional"` // 数据格式
}

type UpdateInfoAtomTypeResponse struct {
	BaseResponse
}

type UpdateOrganizationMemberRequest struct {
	UserOrgPathRequest
	RelationType  string `json:"relationType,optional"`  // 关系类型
	PositionTitle string `json:"positionTitle,optional"` // 职位标题
	IsPrimary     bool   `json:"isPrimary,optional"`     // 是否主要关系
	Status        string `json:"status,optional"`        // 关系状态
}

type UpdateOrganizationMemberResponse struct {
	BaseResponse
}

type UpdateOrganizationRequest struct {
	OrganizationIdPathRequest
	Name        string `json:"name,optional"`        // 组织名称
	Type        string `json:"type,optional"`        // 组织类型
	Description string `json:"description,optional"` // 描述
	SortOrder   int    `json:"sortOrder,optional"`   // 排序
	ManagerId   string `json:"managerId,optional"`   // 负责人ID
	Status      string `json:"status,optional"`      // 状态
}

type UpdateOrganizationResponse struct {
	BaseResponse
}

type UpdateRoleRequest struct {
	RoleKey     string   `path:"roleKey"`              // 角色键
	RoleName    string   `json:"roleName,optional"`    // 角色显示名称
	Description string   `json:"description,optional"` // 角色描述
	Permissions []string `json:"permissions,optional"` // 角色权限列表
}

type UpdateRoleResponse struct {
	BaseResponse
}

type UpdateTagRequest struct {
	TagIdPathRequest
	Scope       string `json:"scope,optional"`
	Label       string `json:"label,optional"`
	Description string `json:"description,optional"`
}

type UpdateTagResponse struct {
	BaseResponse
}

type UpdateTenantRequest struct {
	TenantIdPathRequest
	TenantName   string   `json:"tenantName,optional"`   // 租户名称
	Description  string   `json:"description,optional"`  // 描述
	Tags         []string `json:"tags,optional"`         // 标签
	ContactEmail string   `json:"contactEmail,optional"` // 联系邮箱
	MaxUsers     int      `json:"maxUsers,optional"`     // 用户数量限制
	ExpiresAt    string   `json:"expiresAt,optional"`    // 过期时间（ISO 8601）
}

type UpdateTenantResponse struct {
	BaseResponse
}

type UpdateTenantStatusRequest struct {
	TenantIdPathRequest
	Status string `json:"status"` // 状态：active/inactive/deleted
}

type UpdateTenantStatusResponse struct {
	BaseResponse
}

type UpdateUserRequest struct {
	UserIdPathRequest
	Name       string         `json:"name,optional"`       // 用户姓名
	Email      string         `json:"email,optional"`      // 电子邮件
	UserName   string         `json:"userName,optional"`   // 用户名
	Phone      string         `json:"phone,optional"`      // 电话号码
	Title      string         `json:"title,optional"`      // 职位
	Avatar     string         `json:"avatar,optional"`     // 用户头像 URL
	Signature  string         `json:"signature,optional"`  // 签名
	Country    string         `json:"country,optional"`    // 国家
	Address    string         `json:"address,optional"`    // 地址
	TagIds     []string       `json:"tagIds,optional"`     // 标签ID列表
	Geographic UserGeographic `json:"geographic,optional"` // 地理信息
}

type UpdateUserResponse struct {
	BaseResponse
}

type UpdateUserStatusRequest struct {
	UserIdPathRequest
	Status string `json:"status,optional"` // 用户状态：'active'-活跃，'inactive'-禁用，'deleted'-删除
}

type UpdateUserStatusResponse struct {
	BaseResponse
}

type UploadAvatarData struct {
	AvatarUrl string `json:"avatarUrl"` // 头像URL
}

type UploadAvatarResponse struct {
	BaseResponse
	Data UploadAvatarData `json:"data,omitempty"` // 上传结果数据
}

type User struct {
	Id              string         `json:"id"`              // 用户ID
	UserKey         string         `json:"userKey"`         // 用户Key
	UserName        string         `json:"userName"`        // 用户名
	Email           string         `json:"email"`           // 电子邮件
	Phone           string         `json:"phone"`           // 电话号码
	Name            string         `json:"name"`            // 用户姓名
	Avatar          string         `json:"avatar"`          // 用户头像 URL
	Signature       string         `json:"signature"`       // 个人签名
	Title           string         `json:"title"`           // 职位
	TenantInfo      TenantInfo     `json:"tenantInfo"`      // 租户信息
	OrganizationIds []string       `json:"organizationIds"` // 用户关联的组织ID列表
	Tags            []UserTag      `json:"tags"`            // 标签列表
	Geographic      UserGeographic `json:"geographic"`      // 地理信息
	Country         string         `json:"country"`         // 国家
	Address         string         `json:"address"`         // 地址
	Status          string         `json:"status"`          // 用户状态：'active'-活跃，'inactive'-禁用，'deleted'-删除
	CreatedAt       string         `json:"createdAt"`       // 创建时间
	UpdatedAt       string         `json:"updatedAt"`       // 更新时间
	LastLoginAt     string         `json:"lastLoginAt"`     // 最后登录时间
}

type UserBrief struct {
	Id          string     `json:"id"`          // 用户ID
	UserKey     string     `json:"userKey"`     // 用户Key
	UserName    string     `json:"userName"`    // 用户名
	Name        string     `json:"name"`        // 用户姓名
	Email       string     `json:"email"`       // 电子邮件
	Avatar      string     `json:"avatar"`      // 用户头像 URL
	Status      string     `json:"status"`      // 用户状态
	TenantInfo  TenantInfo `json:"tenantInfo"`  // 租户信息
	IsActive    bool       `json:"isActive"`    // 用户是否活跃
	Tags        []UserTag  `json:"tags"`        // 用户标签
	CreatedAt   int64      `json:"createdAt"`   // 创建时间（Unix时间戳）
	UpdatedAt   int64      `json:"updatedAt"`   // 更新时间（Unix时间戳）
	LastLoginAt int64      `json:"lastLoginAt"` // 最后登录时间（Unix时间戳）
}

type UserGeographic struct {
	Province UserLocation `json:"province,omitempty"` // 省份
	City     UserLocation `json:"city,omitempty"`     // 城市
}

type UserIdPathRequest struct {
	Id string `path:"id"` // 用户ID
}

type UserListData struct {
	List []UserBrief `json:"list"` // 用户简要信息列表
}

type UserLocation struct {
	Label string `json:"label,omitempty"` // 地理位置显示名称
	Key   string `json:"key,omitempty"`   // 地理位置键
}

type UserOption struct {
	Id        string `json:"id"`        // 用户UUID
	UserKey   string `json:"userKey"`   // 用户Key
	UserName  string `json:"userName"`  // 用户名
	Name      string `json:"name"`      // 用户姓名
	Email     string `json:"email"`     // 邮箱
	TenantId  string `json:"tenantId"`  // 所属租户ID
	TenantKey string `json:"tenantKey"` // 所属租户Key
}

type UserOrgBrief struct {
	OrgId         string `json:"orgId"`         // 组织ID
	OrgCode       string `json:"orgCode"`       // 组织代码
	OrgName       string `json:"orgName"`       // 组织名称
	OrgType       string `json:"orgType"`       // 组织类型
	RelationType  string `json:"relationType"`  // 关系类型：manager, member, deputy, consultant
	PositionTitle string `json:"positionTitle"` // 职位名称
	IsPrimary     bool   `json:"isPrimary"`     // 是否为主属组织
}

type UserOrgPathRequest struct {
	OrgId  string `path:"orgId"`  // 组织ID
	UserId string `path:"userId"` // 用户ID
}

type UserOrgRelation struct {
	Id            string `json:"id"`            // 关系ID
	UserId        string `json:"userId"`        // 用户ID
	UserKey       string `json:"userKey"`       // 用户Key
	UserName      string `json:"userName"`      // 用户名
	Name          string `json:"name"`          // 用户姓名
	Email         string `json:"email"`         // 用户邮箱
	OrgId         string `json:"orgId"`         // 组织ID
	OrgCode       string `json:"orgCode"`       // 组织代码
	OrgName       string `json:"orgName"`       // 组织名称
	RelationType  string `json:"relationType"`  // 关系类型（manager/member）
	PositionTitle string `json:"positionTitle"` // 职位标题
	IsPrimary     bool   `json:"isPrimary"`     // 是否主要关系
	Status        string `json:"status"`        // 关系状态
	JoinedAt      string `json:"joinedAt"`      // 加入时间
}

type UserTag struct {
	Id    string `json:"id,omitempty"`    // 标签ID
	Label string `json:"label,omitempty"` // 标签显示名称
}
