// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	auth "github.com/rezeropoint/nexlyn/restful/backend/internal/handler/auth"
	organization "github.com/rezeropoint/nexlyn/restful/backend/internal/handler/organization"
	permission "github.com/rezeropoint/nexlyn/restful/backend/internal/handler/permission"
	sync "github.com/rezeropoint/nexlyn/restful/backend/internal/handler/sync"
	tags "github.com/rezeropoint/nexlyn/restful/backend/internal/handler/tags"
	tenant "github.com/rezeropoint/nexlyn/restful/backend/internal/handler/tenant"
	user "github.com/rezeropoint/nexlyn/restful/backend/internal/handler/user"
	"github.com/rezeropoint/nexlyn/restful/backend/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 用户登录
				Method:  http.MethodPost,
				Path:    "/auth/login",
				Handler: auth.LoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 创建组织
				Method:  http.MethodPost,
				Path:    "/organization",
				Handler: organization.CreateOrganizationHandler(serverCtx),
			},
			{
				// 获取组织详情
				Method:  http.MethodGet,
				Path:    "/organization/:id",
				Handler: organization.GetOrganizationHandler(serverCtx),
			},
			{
				// 更新组织
				Method:  http.MethodPut,
				Path:    "/organization/:id",
				Handler: organization.UpdateOrganizationHandler(serverCtx),
			},
			{
				// 删除组织
				Method:  http.MethodDelete,
				Path:    "/organization/:id",
				Handler: organization.DeleteOrganizationHandler(serverCtx),
			},
			{
				// 获取组织成员
				Method:  http.MethodGet,
				Path:    "/organization/:id/members",
				Handler: organization.GetOrganizationMembersHandler(serverCtx),
			},
			{
				// 添加组织成员
				Method:  http.MethodPost,
				Path:    "/organization/:id/members",
				Handler: organization.AddOrganizationMemberHandler(serverCtx),
			},
			{
				// 移动组织
				Method:  http.MethodPost,
				Path:    "/organization/:id/move",
				Handler: organization.MoveOrganizationHandler(serverCtx),
			},
			{
				// 移除组织成员
				Method:  http.MethodDelete,
				Path:    "/organization/:orgId/members/:userId",
				Handler: organization.RemoveOrganizationMemberHandler(serverCtx),
			},
			{
				// 更新成员关系
				Method:  http.MethodPut,
				Path:    "/organization/:orgId/members/:userId",
				Handler: organization.UpdateOrganizationMemberHandler(serverCtx),
			},
			{
				// 获取组织列表
				Method:  http.MethodGet,
				Path:    "/organization/list",
				Handler: organization.GetOrganizationListHandler(serverCtx),
			},
			{
				// 获取组织下拉选项
				Method:  http.MethodGet,
				Path:    "/organization/options",
				Handler: organization.GetOrganizationOptionsHandler(serverCtx),
			},
			{
				// 获取组织树
				Method:  http.MethodGet,
				Path:    "/organization/tree",
				Handler: organization.GetOrganizationTreeHandler(serverCtx),
			},
			{
				// 获取用户所属组织
				Method:  http.MethodGet,
				Path:    "/user/:id/organizations",
				Handler: organization.GetUserOrganizationsHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 添加权限规则
				Method:  http.MethodPost,
				Path:    "/permission/add",
				Handler: permission.AddPermissionHandler(serverCtx),
			},
			{
				// 获取可用权限列表
				Method:  http.MethodGet,
				Path:    "/permission/available",
				Handler: permission.GetAvailablePermissionsHandler(serverCtx),
			},
			{
				// 检查用户权限
				Method:  http.MethodPost,
				Path:    "/permission/check",
				Handler: permission.CheckPermissionHandler(serverCtx),
			},
			{
				// 获取当前用户权限
				Method:  http.MethodGet,
				Path:    "/permission/current",
				Handler: permission.GetCurrentUserPermissionsHandler(serverCtx),
			},
			{
				// 移除权限规则
				Method:  http.MethodDelete,
				Path:    "/permission/remove",
				Handler: permission.RemovePermissionHandler(serverCtx),
			},
			{
				// 创建角色
				Method:  http.MethodPost,
				Path:    "/permission/role",
				Handler: permission.CreateRoleHandler(serverCtx),
			},
			{
				// 更新角色
				Method:  http.MethodPut,
				Path:    "/permission/role/:roleKey",
				Handler: permission.UpdateRoleHandler(serverCtx),
			},
			{
				// 删除角色
				Method:  http.MethodDelete,
				Path:    "/permission/role/:roleKey",
				Handler: permission.DeleteRoleHandler(serverCtx),
			},
			{
				// 获取角色详情
				Method:  http.MethodGet,
				Path:    "/permission/role/:roleKey",
				Handler: permission.GetRoleHandler(serverCtx),
			},
			{
				// 为用户添加角色
				Method:  http.MethodPost,
				Path:    "/permission/role/add",
				Handler: permission.AddRoleForUserHandler(serverCtx),
			},
			{
				// 获取角色列表
				Method:  http.MethodGet,
				Path:    "/permission/role/list",
				Handler: permission.GetRoleListHandler(serverCtx),
			},
			{
				// 为角色添加权限
				Method:  http.MethodPost,
				Path:    "/permission/role/permission/add",
				Handler: permission.AddRolePermissionHandler(serverCtx),
			},
			{
				// 为角色移除权限
				Method:  http.MethodDelete,
				Path:    "/permission/role/permission/remove",
				Handler: permission.RemoveRolePermissionHandler(serverCtx),
			},
			{
				// 为用户移除角色
				Method:  http.MethodDelete,
				Path:    "/permission/role/remove",
				Handler: permission.RemoveRoleForUserHandler(serverCtx),
			},
			{
				// 获取权限规则列表
				Method:  http.MethodGet,
				Path:    "/permission/rules",
				Handler: permission.GetPermissionRulesHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// eventsync服务健康检查
				Method:  http.MethodGet,
				Path:    "/sync/health",
				Handler: sync.SyncHealthCheckHandler(serverCtx),
			},
			{
				// 同步单个组织到Skylark
				Method:  http.MethodPost,
				Path:    "/sync/organization/:id",
				Handler: sync.SyncOrganizationHandler(serverCtx),
			},
			{
				// 绑定组织到已存在的Skylark组织
				Method:  http.MethodPost,
				Path:    "/sync/organization/:id/bind",
				Handler: sync.BindOrganizationHandler(serverCtx),
			},
			{
				// 解绑组织的Skylark映射
				Method:  http.MethodDelete,
				Path:    "/sync/organization/:id/bind",
				Handler: sync.UnbindOrganizationHandler(serverCtx),
			},
			{
				// 查询组织同步状态
				Method:  http.MethodGet,
				Path:    "/sync/organizations/status",
				Handler: sync.GetOrgSyncStatusHandler(serverCtx),
			},
			{
				// 同步单个用户到Skylark
				Method:  http.MethodPost,
				Path:    "/sync/user/:id",
				Handler: sync.SyncUserHandler(serverCtx),
			},
			{
				// 绑定用户到已存在的Skylark用户
				Method:  http.MethodPost,
				Path:    "/sync/user/:id/bind",
				Handler: sync.BindUserHandler(serverCtx),
			},
			{
				// 解绑用户的Skylark映射
				Method:  http.MethodDelete,
				Path:    "/sync/user/:id/bind",
				Handler: sync.UnbindUserHandler(serverCtx),
			},
			{
				// 查询用户同步状态
				Method:  http.MethodGet,
				Path:    "/sync/users/status",
				Handler: sync.GetUserSyncStatusHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 创建标签
				Method:  http.MethodPost,
				Path:    "/tags",
				Handler: tags.CreateTagHandler(serverCtx),
			},
			{
				// 更新标签
				Method:  http.MethodPut,
				Path:    "/tags/:id",
				Handler: tags.UpdateTagHandler(serverCtx),
			},
			{
				// 删除标签
				Method:  http.MethodDelete,
				Path:    "/tags/:id",
				Handler: tags.DeleteTagHandler(serverCtx),
			},
			{
				// 获取标签详情
				Method:  http.MethodGet,
				Path:    "/tags/:id",
				Handler: tags.GetTagHandler(serverCtx),
			},
			{
				// 获取标签列表
				Method:  http.MethodGet,
				Path:    "/tags/list",
				Handler: tags.GetTagListHandler(serverCtx),
			},
			{
				// 获取标签下拉选项
				Method:  http.MethodGet,
				Path:    "/tags/options",
				Handler: tags.GetTagOptionsHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 创建租户
				Method:  http.MethodPost,
				Path:    "/tenant",
				Handler: tenant.CreateTenantHandler(serverCtx),
			},
			{
				// 获取租户详情
				Method:  http.MethodGet,
				Path:    "/tenant/:id",
				Handler: tenant.GetTenantHandler(serverCtx),
			},
			{
				// 更新租户信息
				Method:  http.MethodPut,
				Path:    "/tenant/:id",
				Handler: tenant.UpdateTenantHandler(serverCtx),
			},
			{
				// 删除租户
				Method:  http.MethodDelete,
				Path:    "/tenant/:id",
				Handler: tenant.DeleteTenantHandler(serverCtx),
			},
			{
				// 更新租户状态
				Method:  http.MethodPost,
				Path:    "/tenant/:id/status",
				Handler: tenant.UpdateTenantStatusHandler(serverCtx),
			},
			{
				// 获取租户列表
				Method:  http.MethodGet,
				Path:    "/tenant/list",
				Handler: tenant.GetTenantListHandler(serverCtx),
			},
			{
				// 获取租户选项列表（下拉框用）
				Method:  http.MethodGet,
				Path:    "/tenant/options",
				Handler: tenant.GetTenantOptionsHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 创建新用户
				Method:  http.MethodPost,
				Path:    "/user",
				Handler: user.CreateUserHandler(serverCtx),
			},
			{
				// 根据ID获取用户详情
				Method:  http.MethodGet,
				Path:    "/user/:id",
				Handler: user.GetUserByIdHandler(serverCtx),
			},
			{
				// 更新用户信息
				Method:  http.MethodPut,
				Path:    "/user/:id",
				Handler: user.UpdateUserHandler(serverCtx),
			},
			{
				// 删除用户
				Method:  http.MethodDelete,
				Path:    "/user/:id",
				Handler: user.DeleteUserHandler(serverCtx),
			},
			{
				// 重置用户密码(仅限管理员,需要user:write权限;用户修改自己密码请使用changePassword接口)
				Method:  http.MethodPost,
				Path:    "/user/:id/reset-password",
				Handler: user.ResetUserPasswordHandler(serverCtx),
			},
			{
				// 更新用户状态
				Method:  http.MethodPost,
				Path:    "/user/:id/status",
				Handler: user.UpdateUserStatusHandler(serverCtx),
			},
			{
				// 上传用户头像
				Method:  http.MethodPost,
				Path:    "/user/avatar/upload",
				Handler: user.UploadAvatarHandler(serverCtx),
			},
			{
				// 获取当前用户信息
				Method:  http.MethodGet,
				Path:    "/user/current",
				Handler: user.GetCurrentUserHandler(serverCtx),
			},
			{
				// 更新当前用户信息(用户修改自己的资料,无需user:write权限)
				Method:  http.MethodPost,
				Path:    "/user/current/profile",
				Handler: user.UpdateCurrentUserHandler(serverCtx),
			},
			{
				// 获取用户列表
				Method:  http.MethodGet,
				Path:    "/user/list",
				Handler: user.GetUserListHandler(serverCtx),
			},
			{
				// 获取用户选项列表（下拉框用）
				Method:  http.MethodGet,
				Path:    "/user/options",
				Handler: user.GetUserOptionsHandler(serverCtx),
			},
			{
				// 修改当前用户密码
				Method:  http.MethodPost,
				Path:    "/user/password/change",
				Handler: user.ChangePasswordHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)
}
