// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.4
// source: lynxengine.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 信息原子请求
type InfoAtomRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TenantId       string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`                       // 租户ID
	InfoAtomTypeId string                 `protobuf:"bytes,2,opt,name=info_atom_type_id,json=infoAtomTypeId,proto3" json:"info_atom_type_id,omitempty"` // 信息原子类型ID
	Source         string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`                                           // 数据来源（如设备ID）
	RawData        []byte                 `protobuf:"bytes,4,opt,name=raw_data,json=rawData,proto3" json:"raw_data,omitempty"`                          // 原始JSON数据
	Tags           []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`                                               // 标签列表
	Timestamp      int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                    // 时间戳（Unix毫秒）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InfoAtomRequest) Reset() {
	*x = InfoAtomRequest{}
	mi := &file_lynxengine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoAtomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoAtomRequest) ProtoMessage() {}

func (x *InfoAtomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lynxengine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoAtomRequest.ProtoReflect.Descriptor instead.
func (*InfoAtomRequest) Descriptor() ([]byte, []int) {
	return file_lynxengine_proto_rawDescGZIP(), []int{0}
}

func (x *InfoAtomRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *InfoAtomRequest) GetInfoAtomTypeId() string {
	if x != nil {
		return x.InfoAtomTypeId
	}
	return ""
}

func (x *InfoAtomRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *InfoAtomRequest) GetRawData() []byte {
	if x != nil {
		return x.RawData
	}
	return nil
}

func (x *InfoAtomRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *InfoAtomRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// 信息原子响应
type InfoAtomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                          // 是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                           // 响应消息
	InfoAtomId    string                 `protobuf:"bytes,3,opt,name=info_atom_id,json=infoAtomId,proto3" json:"info_atom_id,omitempty"` // 生成的信息原子ID
	ErrorCode     string                 `protobuf:"bytes,4,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`      // 错误码（可选）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoAtomResponse) Reset() {
	*x = InfoAtomResponse{}
	mi := &file_lynxengine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoAtomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoAtomResponse) ProtoMessage() {}

func (x *InfoAtomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lynxengine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoAtomResponse.ProtoReflect.Descriptor instead.
func (*InfoAtomResponse) Descriptor() ([]byte, []int) {
	return file_lynxengine_proto_rawDescGZIP(), []int{1}
}

func (x *InfoAtomResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *InfoAtomResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *InfoAtomResponse) GetInfoAtomId() string {
	if x != nil {
		return x.InfoAtomId
	}
	return ""
}

func (x *InfoAtomResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

// 健康检查请求
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_lynxengine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lynxengine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_lynxengine_proto_rawDescGZIP(), []int{2}
}

// 健康检查响应
type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"` // 是否健康
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_lynxengine_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lynxengine_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_lynxengine_proto_rawDescGZIP(), []int{3}
}

func (x *HealthCheckResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

var File_lynxengine_proto protoreflect.FileDescriptor

const file_lynxengine_proto_rawDesc = "" +
	"\n" +
	"\x10lynxengine.proto\x12\n" +
	"lynxengine\"\xbe\x01\n" +
	"\x0fInfoAtomRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12)\n" +
	"\x11info_atom_type_id\x18\x02 \x01(\tR\x0einfoAtomTypeId\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x19\n" +
	"\braw_data\x18\x04 \x01(\fR\arawData\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\"\x87\x01\n" +
	"\x10InfoAtomResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12 \n" +
	"\finfo_atom_id\x18\x03 \x01(\tR\n" +
	"infoAtomId\x12\x1d\n" +
	"\n" +
	"error_code\x18\x04 \x01(\tR\terrorCode\"\x14\n" +
	"\x12HealthCheckRequest\"/\n" +
	"\x13HealthCheckResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy2\xaa\x01\n" +
	"\n" +
	"LynxEngine\x12L\n" +
	"\x0fReceiveInfoAtom\x12\x1b.lynxengine.InfoAtomRequest\x1a\x1c.lynxengine.InfoAtomResponse\x12N\n" +
	"\vHealthCheck\x12\x1e.lynxengine.HealthCheckRequest\x1a\x1f.lynxengine.HealthCheckResponseB\x1eZ\x1cnexlyn/service/lynxengine/pbb\x06proto3"

var (
	file_lynxengine_proto_rawDescOnce sync.Once
	file_lynxengine_proto_rawDescData []byte
)

func file_lynxengine_proto_rawDescGZIP() []byte {
	file_lynxengine_proto_rawDescOnce.Do(func() {
		file_lynxengine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lynxengine_proto_rawDesc), len(file_lynxengine_proto_rawDesc)))
	})
	return file_lynxengine_proto_rawDescData
}

var file_lynxengine_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_lynxengine_proto_goTypes = []any{
	(*InfoAtomRequest)(nil),     // 0: lynxengine.InfoAtomRequest
	(*InfoAtomResponse)(nil),    // 1: lynxengine.InfoAtomResponse
	(*HealthCheckRequest)(nil),  // 2: lynxengine.HealthCheckRequest
	(*HealthCheckResponse)(nil), // 3: lynxengine.HealthCheckResponse
}
var file_lynxengine_proto_depIdxs = []int32{
	0, // 0: lynxengine.LynxEngine.ReceiveInfoAtom:input_type -> lynxengine.InfoAtomRequest
	2, // 1: lynxengine.LynxEngine.HealthCheck:input_type -> lynxengine.HealthCheckRequest
	1, // 2: lynxengine.LynxEngine.ReceiveInfoAtom:output_type -> lynxengine.InfoAtomResponse
	3, // 3: lynxengine.LynxEngine.HealthCheck:output_type -> lynxengine.HealthCheckResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_lynxengine_proto_init() }
func file_lynxengine_proto_init() {
	if File_lynxengine_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lynxengine_proto_rawDesc), len(file_lynxengine_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lynxengine_proto_goTypes,
		DependencyIndexes: file_lynxengine_proto_depIdxs,
		MessageInfos:      file_lynxengine_proto_msgTypes,
	}.Build()
	File_lynxengine_proto = out.File
	file_lynxengine_proto_goTypes = nil
	file_lynxengine_proto_depIdxs = nil
}
