// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.4
// source: lynxengine.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LynxEngine_ReceiveInfoAtom_FullMethodName = "/lynxengine.LynxEngine/ReceiveInfoAtom"
	LynxEngine_HealthCheck_FullMethodName     = "/lynxengine.LynxEngine/HealthCheck"
)

// LynxEngineClient is the client API for LynxEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// LynxEngine gRPC服务
type LynxEngineClient interface {
	// 接收信息原子
	ReceiveInfoAtom(ctx context.Context, in *InfoAtomRequest, opts ...grpc.CallOption) (*InfoAtomResponse, error)
	// 健康检查
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type lynxEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewLynxEngineClient(cc grpc.ClientConnInterface) LynxEngineClient {
	return &lynxEngineClient{cc}
}

func (c *lynxEngineClient) ReceiveInfoAtom(ctx context.Context, in *InfoAtomRequest, opts ...grpc.CallOption) (*InfoAtomResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InfoAtomResponse)
	err := c.cc.Invoke(ctx, LynxEngine_ReceiveInfoAtom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lynxEngineClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, LynxEngine_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LynxEngineServer is the server API for LynxEngine service.
// All implementations must embed UnimplementedLynxEngineServer
// for forward compatibility.
//
// LynxEngine gRPC服务
type LynxEngineServer interface {
	// 接收信息原子
	ReceiveInfoAtom(context.Context, *InfoAtomRequest) (*InfoAtomResponse, error)
	// 健康检查
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedLynxEngineServer()
}

// UnimplementedLynxEngineServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLynxEngineServer struct{}

func (UnimplementedLynxEngineServer) ReceiveInfoAtom(context.Context, *InfoAtomRequest) (*InfoAtomResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReceiveInfoAtom not implemented")
}
func (UnimplementedLynxEngineServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedLynxEngineServer) mustEmbedUnimplementedLynxEngineServer() {}
func (UnimplementedLynxEngineServer) testEmbeddedByValue()                    {}

// UnsafeLynxEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LynxEngineServer will
// result in compilation errors.
type UnsafeLynxEngineServer interface {
	mustEmbedUnimplementedLynxEngineServer()
}

func RegisterLynxEngineServer(s grpc.ServiceRegistrar, srv LynxEngineServer) {
	// If the following call pancis, it indicates UnimplementedLynxEngineServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LynxEngine_ServiceDesc, srv)
}

func _LynxEngine_ReceiveInfoAtom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoAtomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LynxEngineServer).ReceiveInfoAtom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LynxEngine_ReceiveInfoAtom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LynxEngineServer).ReceiveInfoAtom(ctx, req.(*InfoAtomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LynxEngine_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LynxEngineServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LynxEngine_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LynxEngineServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LynxEngine_ServiceDesc is the grpc.ServiceDesc for LynxEngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LynxEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lynxengine.LynxEngine",
	HandlerType: (*LynxEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReceiveInfoAtom",
			Handler:    _LynxEngine_ReceiveInfoAtom_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _LynxEngine_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lynxengine.proto",
}
