// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: iotquery.proto

package server

import (
	"context"

	"github.com/rezeropoint/nexlyn/service/iotquery/internal/logic"
	"github.com/rezeropoint/nexlyn/service/iotquery/internal/svc"
	"github.com/rezeropoint/nexlyn/service/iotquery/pb"
)

type IoTQueryServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedIoTQueryServer
}

func NewIoTQueryServer(svcCtx *svc.ServiceContext) *IoTQueryServer {
	return &IoTQueryServer{
		svcCtx: svcCtx,
	}
}

// QueryTimeSeries 查询时序数据
func (s *IoTQueryServer) QueryTimeSeries(ctx context.Context, in *pb.QueryTimeSeriesReq) (*pb.QueryTimeSeriesResp, error) {
	l := logic.NewQueryTimeSeriesLogic(ctx, s.svcCtx)
	return l.QueryTimeSeries(in)
}

// GetLatestValues 获取设备字段最新值
func (s *IoTQueryServer) GetLatestValues(ctx context.Context, in *pb.GetLatestValuesReq) (*pb.GetLatestValuesResp, error) {
	l := logic.NewGetLatestValuesLogic(ctx, s.svcCtx)
	return l.GetLatestValues(in)
}

// GetDeviceStatistics 获取设备统计信息
func (s *IoTQueryServer) GetDeviceStatistics(ctx context.Context, in *pb.GetDeviceStatisticsReq) (*pb.GetDeviceStatisticsResp, error) {
	l := logic.NewGetDeviceStatisticsLogic(ctx, s.svcCtx)
	return l.GetDeviceStatistics(in)
}
