// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: lynxengine.proto

package server

import (
	"context"

	"github.com/rezeropoint/nexlyn/service/lynxengine/internal/logic"
	"github.com/rezeropoint/nexlyn/service/lynxengine/internal/svc"
	"github.com/rezeropoint/nexlyn/service/lynxengine/pb"
)

type LynxEngineServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedLynxEngineServer
}

func NewLynxEngineServer(svcCtx *svc.ServiceContext) *LynxEngineServer {
	return &LynxEngineServer{
		svcCtx: svcCtx,
	}
}

// 接收信息原子
func (s *LynxEngineServer) ReceiveInfoAtom(ctx context.Context, in *pb.InfoAtomRequest) (*pb.InfoAtomResponse, error) {
	l := logic.NewReceiveInfoAtomLogic(ctx, s.svcCtx)
	return l.ReceiveInfoAtom(in)
}

// 健康检查
func (s *LynxEngineServer) HealthCheck(ctx context.Context, in *pb.HealthCheckRequest) (*pb.HealthCheckResponse, error) {
	l := logic.NewHealthCheckLogic(ctx, s.svcCtx)
	return l.HealthCheck(in)
}
