// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AbortJourneyRequest struct {
	FlowId    int64 `path:"flowId"`    // 流程ID
	JourneyId int64 `path:"journeyId"` // Journey ID
}

type AbortJourneyResponse struct {
	BaseResponse
}

type Assignment struct {
	Id         int64  `json:"id"`                 // Assignment ID
	AssigneeId string `json:"assigneeId"`         // 处理人UUID（SDK中的远程用户ID）
	Status     string `json:"status"`             // 状态：processing/completed
	Category   string `json:"category"`           // 类别：processed（待我处理）/proposed（我发起的）/cc（抄送我的）
	VertexId   int64  `json:"vertexId"`           // 节点ID
	JourneyId  int64  `json:"journeyId"`          // Journey ID
	CreatedAt  string `json:"createdAt"`          // 创建时间
	UpdatedAt  string `json:"updatedAt"`          // 更新时间
	FlowId     int64  `json:"flowId,optional"`    // 流程ID（SDK自动补充）
	FlowTitle  string `json:"flowTitle,optional"` // 流程标题（SDK自动补充）
}

type AssignmentListData struct {
	List  []Assignment `json:"list"`  // 任务列表
	Total int          `json:"total"` // 总数
}

type Attachment struct {
	Id         int64  `json:"id"`         // 附件ID
	Name       string `json:"name"`       // 文件名
	Url        string `json:"url"`        // 下载URL
	Size       int64  `json:"size"`       // 文件大小（字节）
	MimeType   string `json:"mimeType"`   // MIME类型
	UploadedBy int64  `json:"uploadedBy"` // 上传者用户ID
	CreatedAt  string `json:"createdAt"`  // 上传时间
}

type BaseResponse struct {
	Code int64  `json:"code"`          // 响应码
	Msg  string `json:"msg,omitempty"` // 响应消息
}

type ColumnInfo struct {
	Field       string `json:"field"`       // 字段名
	DisplayName string `json:"displayName"` // 展示名称
	Type        string `json:"type"`        // 字段类型
}

type CreateEventConfigWithFieldsRequest struct {
	Name         string             `json:"name"`                  // 事件名称（必填）
	FlowId       int                `json:"flowId"`                // 远程流程ID（必填）
	OrgFieldName string             `json:"orgFieldName,optional"` // 组织字段名（可选）
	Description  string             `json:"description,optional"`  // 描述
	Enabled      bool               `json:"enabled,optional"`      // 是否启用（默认true）
	Fields       []FieldConfigInput `json:"fields"`                // 字段配置列表（必填）
}

type CreateEventConfigWithFieldsResponse struct {
	BaseResponse
	Data struct {
		Id   string `json:"id"`   // 事件配置UUID
		Name string `json:"name"` // 事件名称
	} `json:"data,omitempty"`
}

type CreateOrgMappingRequest struct {
	RemoteOrgValue string `json:"remoteOrgValue"` // 远程组织值（必填）
	LocalOrgId     string `json:"localOrgId"`     // 本地组织ID（必填）
}

type CreateOrgMappingResponse struct {
	BaseResponse
	Data struct {
		Id string `json:"id"` // 组织映射UUID
	} `json:"data,omitempty"`
}

type DeleteEventConfigRequest struct {
	EventIdPathRequest
}

type DeleteEventConfigResponse struct {
	BaseResponse
}

type DeleteOrgMappingRequest struct {
	OrgMappingIdPathRequest
}

type DeleteOrgMappingResponse struct {
	BaseResponse
}

type EventConfig struct {
	Id           string `json:"id"`                    // 配置UUID
	Name         string `json:"name"`                  // 事件显示名称（自定义）
	FlowId       int    `json:"flowId"`                // 远程流程ID
	FlowTitle    string `json:"flowTitle,optional"`    // 远程流程名称（冗余）
	OrgFieldName string `json:"orgFieldName,optional"` // 组织字段名（可选）
	Description  string `json:"description,optional"`  // 描述
	Enabled      bool   `json:"enabled"`               // 是否启用
	TenantId     string `json:"tenantId"`              // 租户ID
	CreatedBy    string `json:"createdBy,optional"`    // 创建者
	UpdatedBy    string `json:"updatedBy,optional"`    // 更新者
	CreatedAt    string `json:"createdAt,optional"`    // 创建时间
	UpdatedAt    string `json:"updatedAt,optional"`    // 更新时间
}

type EventConfigWithFields struct {
	Id           string        `json:"id"`                    // 配置UUID
	Name         string        `json:"name"`                  // 事件显示名称
	FlowId       int           `json:"flowId"`                // 远程流程ID
	FlowTitle    string        `json:"flowTitle,optional"`    // 远程流程名称
	OrgFieldName string        `json:"orgFieldName,optional"` // 组织字段名
	Description  string        `json:"description,optional"`  // 描述
	Enabled      bool          `json:"enabled"`               // 是否启用
	TenantId     string        `json:"tenantId"`              // 租户ID
	CreatedBy    string        `json:"createdBy,optional"`    // 创建者
	UpdatedBy    string        `json:"updatedBy,optional"`    // 更新者
	CreatedAt    string        `json:"createdAt,optional"`    // 创建时间
	UpdatedAt    string        `json:"updatedAt,optional"`    // 更新时间
	Fields       []FieldConfig `json:"fields"`                // 字段配置列表
}

type EventDataPathRequest struct {
	EventId   string `path:"eventId"`   // 事件配置ID
	JourneyId int    `path:"journeyId"` // Journey ID（事件实例ID）
}

type EventIdPathRequest struct {
	Id string `path:"id"` // 事件配置ID
}

type EventPendingStats struct {
	EventConfigID   string `json:"eventConfigId"`   // 事件配置ID
	EventName       string `json:"eventName"`       // 事件名称
	PendingCount    int64  `json:"pendingCount"`    // 未开始事件数（只有发起节点）
	ProcessingCount int64  `json:"processingCount"` // 处理中事件数（有多个节点）
	Total           int64  `json:"total"`           // 该事件的总数（未完成的事件）
}

type FieldConfig struct {
	Id            string `json:"id"`                 // 配置UUID
	EventConfigId string `json:"eventConfigId"`      // 关联事件配置ID
	FieldName     string `json:"fieldName"`          // 远程表字段名
	DisplayName   string `json:"displayName"`        // 展示名称
	FieldType     string `json:"fieldType"`          // 字段类型：string/number/date/datetime/boolean
	IsVisible     bool   `json:"isVisible"`          // 是否在列表页展示
	DisplayOrder  int    `json:"displayOrder"`       // 展示顺序
	IsSearchable  bool   `json:"isSearchable"`       // 是否可搜索
	CreatedAt     string `json:"createdAt,optional"` // 创建时间
	UpdatedAt     string `json:"updatedAt,optional"` // 更新时间
}

type FieldConfigInput struct {
	FieldName    string `json:"fieldName"`    // 字段名（必填）
	DisplayName  string `json:"displayName"`  // 展示名称（必填）
	FieldType    string `json:"fieldType"`    // 字段类型（必填）
	IsVisible    bool   `json:"isVisible"`    // 是否可见
	DisplayOrder int    `json:"displayOrder"` // 展示顺序
	IsSearchable bool   `json:"isSearchable"` // 是否可搜索
}

type FieldMetadata struct {
	FieldName string `json:"fieldName"` // 字段名
	DataType  string `json:"dataType"`  // 数据类型
	IsSystem  bool   `json:"isSystem"`  // 是否为系统字段（slp_前缀）
}

type FieldOption struct {
	Id       int                    `json:"id"`                // 选项ID
	Value    string                 `json:"value"`             // 选项值
	Settings map[string]interface{} `json:"settings,optional"` // 选项设置
	Position int                    `json:"position"`          // 选项位置
}

type FlowDetailData struct {
	Id       int64        `json:"id"`       // 流程ID
	Title    string       `json:"title"`    // 流程标题
	Fields   []FlowField  `json:"fields"`   // 字段列表
	Vertices []FlowVertex `json:"vertices"` // 节点列表
	Edges    []FlowEdge   `json:"edges"`    // 边列表
}

type FlowEdge struct {
	Id           int64  `json:"id"`                 // 边ID
	SourceVertex int64  `json:"sourceVertex"`       // 源节点ID
	TargetVertex int64  `json:"targetVertex"`       // 目标节点ID
	Condition    string `json:"condition,optional"` // 条件表达式
}

type FlowField struct {
	Name        string `json:"name"`                 // 字段名
	Title       string `json:"title"`                // 字段标题
	Type        string `json:"type"`                 // 字段类型：TextField/NumberField/DateField等
	Required    bool   `json:"required"`             // 是否必填
	Description string `json:"description,optional"` // 字段描述
}

type FlowInfo struct {
	Id          int    `json:"id"`          // 流程ID
	Title       string `json:"title"`       // 流程名称
	NamespaceId int    `json:"namespaceId"` // 命名空间ID
}

type FlowNode struct {
	VertexId    int      `json:"vertexId"`    // 节点ID
	VertexName  string   `json:"vertexName"`  // 节点名称
	VertexAlias string   `json:"vertexAlias"` // 节点别名
	UserIds     []string `json:"userIds"`     // 处理人ID列表（支持同一节点多人处理）
	UserNames   []string `json:"userNames"`   // 处理人姓名列表（引擎已转换，与UserIds一一对应）
	CreatedAt   string   `json:"createdAt"`   // 节点第一次创建时间
	UpdatedAt   string   `json:"updatedAt"`   // 节点最后更新时间
}

type FlowUser struct {
	Id         string `json:"id"`                  // 用户UUID
	Name       string `json:"name"`                // 用户姓名
	Nickname   string `json:"nickname,optional"`   // 用户昵称
	Identifier string `json:"identifier,optional"` // 工号/身份证号
}

type FlowVertex struct {
	Id          int64  `json:"id"`                   // 节点ID
	Title       string `json:"title"`                // 节点标题
	Type        string `json:"type"`                 // 节点类型：start/end/approve/cc等
	Description string `json:"description,optional"` // 节点描述
}

type GetDurationStatsRequest struct {
	StatsQueryParams
}

type GetDurationStatsResponse struct {
	BaseResponse
	Data struct {
		AvgDuration    float64 `json:"avgDuration"`    // 平均处理时长（秒）
		MinDuration    float64 `json:"minDuration"`    // 最短处理时长（秒）
		MaxDuration    float64 `json:"maxDuration"`    // 最长处理时长（秒）
		TotalCount     int64   `json:"totalCount"`     // 统计范围内的总事件数
		CompletedCount int64   `json:"completedCount"` // 已完成事件数
	} `json:"data,omitempty"`
}

type GetEventConfigListWithFieldsRequest struct {
	PageParamsRequest
	Keyword string `form:"keyword,optional"` // 关键词搜索（名称）
	Enabled *bool  `form:"enabled,optional"` // 启用状态筛选（nil=全部, true=已启用, false=未启用）
}

type GetEventConfigListWithFieldsResponse struct {
	BaseResponse
	PageParams
	Data struct {
		List []EventConfigWithFields `json:"list"` // 事件配置列表（包含字段）
	} `json:"data,omitempty"`
}

type GetEventConfigWithFieldsRequest struct {
	EventIdPathRequest
}

type GetEventConfigWithFieldsResponse struct {
	BaseResponse
	Data EventConfigWithFields `json:"data,omitempty"` // 事件配置+字段
}

type GetEventDetailRequest struct {
	EventDataPathRequest
}

type GetEventDetailResponse struct {
	BaseResponse
	Data struct {
		JourneyId          int                    `json:"journeyId"`          // Journey ID
		CurrentStatus      string                 `json:"currentStatus"`      // 当前流程状态
		InitiatorUserId    string                 `json:"initiatorUserId"`    // 发起人ID
		InitiatorUserName  string                 `json:"initiatorUserName"`  // 发起人姓名（引擎已转换）
		InitiatedAt        string                 `json:"initiatedAt"`        // 发起时间
		LatestBusinessData map[string]interface{} `json:"latestBusinessData"` // 最新业务数据（当前快照）
		FlowHistory        []FlowNode             `json:"flowHistory"`        // 流转历史（所有Assignment的节点信息）
	} `json:"data,omitempty"`
}

type GetFlowDetailRequest struct {
	FlowId int64 `path:"flowId"` // 流程ID
}

type GetFlowDetailResponse struct {
	BaseResponse
	Data FlowDetailData `json:"data"`
}

type GetFlowFieldsRequest struct {
	FlowId int `path:"flowId"` // 流程ID（路径参数）
}

type GetFlowFieldsResponse struct {
	BaseResponse
	Data struct {
		SystemFields   []FieldMetadata `json:"systemFields"`   // 系统字段列表（slp_前缀）
		BusinessFields []FieldMetadata `json:"businessFields"` // 业务字段列表
	} `json:"data,omitempty"`
}

type GetFlowListRequest struct {
	ConfiguredOnly bool `form:"configuredOnly,optional"` // 是否只返回已配置事件的流程
}

type GetFlowListResponse struct {
	BaseResponse
	Data struct {
		List []FlowInfo `json:"list"` // 流程列表
	} `json:"data,omitempty"`
}

type GetJourneyFullDetailRequest struct {
	FlowId    int64 `path:"flowId"`    // 流程ID
	JourneyId int64 `path:"journeyId"` // Journey ID
}

type GetJourneyFullDetailResponse struct {
	BaseResponse
	Data JourneyFullDetail `json:"data"`
}

type GetNodeStatsRequest struct {
	StatsQueryParams
}

type GetNodeStatsResponse struct {
	BaseResponse
	Data struct {
		NodeMetrics []NodeMetric `json:"nodeMetrics"` // 节点指标列表（按事件数量降序）
	} `json:"data,omitempty"`
}

type GetOrgMappingListRequest struct {
	PageParamsRequest
	Keyword string `form:"keyword,optional"` // 关键词搜索（远程组织值或本地组织名称）
}

type GetOrgMappingListResponse struct {
	BaseResponse
	PageParams
	Data struct {
		List []OrgMapping `json:"list"` // 组织映射列表
	} `json:"data,omitempty"`
}

type GetOrgMappingRequest struct {
	OrgMappingIdPathRequest
}

type GetOrgMappingResponse struct {
	BaseResponse
	Data OrgMapping `json:"data,omitempty"` // 组织映射详情
}

type GetOrgStatsRequest struct {
	StatsQueryParams
}

type GetOrgStatsResponse struct {
	BaseResponse
	Data struct {
		OrgMetrics []OrgMetric `json:"orgMetrics"` // 组织指标列表（按事件数量降序）
	} `json:"data,omitempty"`
}

type GetPendingStatsRequest struct {
	StatsQueryParams
}

type GetPendingStatsResponse struct {
	BaseResponse
	Data struct {
		EventStats      []EventPendingStats `json:"eventStats"`      // 按事件配置分组的统计（按事件名称排序）
		TotalPending    int64               `json:"totalPending"`    // 所有事件的未开始总数
		TotalProcessing int64               `json:"totalProcessing"` // 所有事件的处理中总数
		Total           int64               `json:"total"`           // 总事件数（未完成的事件）
	} `json:"data,omitempty"`
}

type GetPlatformConfigRequest struct {
}

type GetPlatformConfigResponse struct {
	BaseResponse
	Data PlatformConfig `json:"data,omitempty"` // 平台配置（密码不返回）
}

type GetProposedJourneysRequest struct {
	FlowId   int64 `form:"flowId"`   // 流程ID
	Page     int   `form:"page"`     // 页码
	PageSize int   `form:"pageSize"` // 每页数量
}

type GetProposedJourneysResponse struct {
	BaseResponse
	Data JourneyListData `json:"data"`
}

type GetStatusStatsRequest struct {
	StatsQueryParams
}

type GetStatusStatsResponse struct {
	BaseResponse
	Data struct {
		StatusCounts []StatusCount `json:"statusCounts"` // 各状态数量（按数量降序）
		Total        int64         `json:"total"`        // 总事件数量
	} `json:"data,omitempty"`
}

type GetTrendStatsRequest struct {
	StatsQueryParams
	GroupBy string `form:"groupBy,optional,options=day|week|month"` // 聚合维度（day/week/month，默认day）
}

type GetTrendStatsResponse struct {
	BaseResponse
	Data struct {
		TimePoints []TrendPoint `json:"timePoints"` // 时间点数据（按时间正序）
	} `json:"data,omitempty"`
}

type GetUserAssignmentsRequest struct {
	Category string `form:"category"` // 类别：processed（待我处理）/proposed（我发起的）/cc（抄送我的）
	Page     int    `form:"page"`     // 页码
	PageSize int    `form:"pageSize"` // 每页数量
}

type GetUserAssignmentsResponse struct {
	BaseResponse
	Data AssignmentListData `json:"data"`
}

type GetUserStatsRequest struct {
	StatsQueryParams
	TopN int `form:"topN,optional"` // Top N数量（默认10）
}

type GetUserStatsResponse struct {
	BaseResponse
	Data struct {
		UserMetrics []UserMetric `json:"userMetrics"` // 用户指标列表（按处理数量降序）
		Total       int64        `json:"total"`       // 统计范围内的总处理人数
	} `json:"data,omitempty"`
}

type Journey struct {
	Id              int64    `json:"id"`              // Journey ID
	Sn              string   `json:"sn"`              // 流程编号
	Status          string   `json:"status"`          // 流程状态：processing/completed/aborted/stashed
	CurrentVertexId int64    `json:"currentVertexId"` // 当前节点ID
	FlowId          int64    `json:"flowId"`          // 流程ID
	CreatedAt       string   `json:"createdAt"`       // 创建时间
	UpdatedAt       string   `json:"updatedAt"`       // 更新时间
	User            FlowUser `json:"user,optional"`   // 发起人信息
}

type JourneyDetail struct {
	Id                       int64                  `json:"id"`                                // Journey ID
	Sn                       string                 `json:"sn"`                                // 流程编号
	Status                   string                 `json:"status"`                            // 流程状态
	CurrentVertexId          int64                  `json:"currentVertexId"`                   // 当前节点ID
	FlowId                   int64                  `json:"flowId"`                            // 流程ID
	CreatedAt                string                 `json:"createdAt"`                         // 创建时间
	UpdatedAt                string                 `json:"updatedAt"`                         // 更新时间
	JourneyUrl               string                 `json:"journeyUrl,optional"`               // Skylark流程详情页URL
	ReviewerVertexIds        []int64                `json:"reviewerVertexIds,optional"`        // 审批节点ID列表
	CurrentDurationThreshold string                 `json:"currentDurationThreshold,optional"` // 当前节点超时阈值
	Initiator                FlowUser               `json:"initiator,optional"`                // 发起人信息
	BusinessData             map[string]interface{} `json:"businessData,optional"`             // 字段值
	Attachments              []Attachment           `json:"attachments,optional"`              // 附件列表
}

type JourneyFullDetail struct {
	BasicInfo    JourneyDetail         `json:"basicInfo"`    // 基础信息
	History      []Moment              `json:"history"`      // 审批历史
	PendingNodes []PendingNode         `json:"pendingNodes"` // 待处理节点
	Vertices     map[string]FlowVertex `json:"vertices"`     // 节点映射（key为节点ID字符串）
}

type JourneyListData struct {
	List  []Journey `json:"list"`  // 流程列表
	Total int       `json:"total"` // 总数
}

type JourneySearchRequest struct {
	Status      string `json:"status,optional"`      // 流程状态
	Keyword     string `json:"keyword,optional"`     // 关键词
	InitiatorId string `json:"initiatorId,optional"` // 发起人ID（本地用户UUID，SDK会转换为远程ID）
	CreatedFrom string `json:"createdFrom,optional"` // 创建时间起始
	CreatedTo   string `json:"createdTo,optional"`   // 创建时间结束
	Page        int    `json:"page"`                 // 页码
	PageSize    int    `json:"pageSize"`             // 每页数量
}

type Moment struct {
	Id           int64  `json:"id"`                    // Moment ID
	AssignmentId int64  `json:"assignmentId"`          // Assignment ID
	JourneyId    int64  `json:"journeyId"`             // Journey ID
	VertexId     int64  `json:"vertexId"`              // 节点ID
	VertexName   string `json:"vertexName,optional"`   // 节点名称
	Status       string `json:"status"`                // 状态：approved/refused/transferred/cancelled
	OperatorId   string `json:"operatorId"`            // 操作人UUID（远程用户ID）
	OperatorName string `json:"operatorName,optional"` // 操作人姓名
	Comment      string `json:"comment,optional"`      // 处理意见
	CreatedAt    string `json:"createdAt"`             // 操作时间
	UpdatedAt    string `json:"updatedAt"`             // 更新时间
	Duration     int    `json:"duration,optional"`     // 处理时长（秒）
}

type NodeMetric struct {
	VertexId    int     `json:"vertexId"`    // 节点ID
	VertexName  string  `json:"vertexName"`  // 节点名称
	Count       int64   `json:"count"`       // 该节点的事件数量
	AvgDuration float64 `json:"avgDuration"` // 该节点平均停留时长（秒）
}

type OrgMapping struct {
	Id             string `json:"id"`                    // 映射UUID
	TenantId       string `json:"tenantId"`              // 租户ID
	RemoteOrgValue string `json:"remoteOrgValue"`        // 远程组织字段值
	LocalOrgId     string `json:"localOrgId"`            // 本地组织ID
	LocalOrgName   string `json:"localOrgName,optional"` // 本地组织名称（通过LEFT JOIN查询）
	CreatedAt      string `json:"createdAt,optional"`    // 创建时间
	UpdatedAt      string `json:"updatedAt,optional"`    // 更新时间
}

type OrgMappingIdPathRequest struct {
	Id string `path:"id"` // 组织映射ID
}

type OrgMetric struct {
	OrgValue    string  `json:"orgValue"`    // 组织字段值
	Count       int64   `json:"count"`       // 该组织的事件数量
	AvgDuration float64 `json:"avgDuration"` // 该组织的平均处理时长（秒）
}

type PageParams struct {
	Current  int64 `json:"current,omitempty"`  // 当前页码
	PageSize int64 `json:"pageSize,omitempty"` // 每页大小
	Total    int64 `json:"total,omitempty"`    // 总记录数
}

type PageParamsRequest struct {
	Current  int64 `form:"current,optional"`  // 当前页码
	PageSize int64 `form:"pageSize,optional"` // 每页大小
}

type PendingNode struct {
	VertexId    int64         `json:"vertexId"`    // 节点ID
	VertexName  string        `json:"vertexName"`  // 节点名称
	AssigneeIds []string      `json:"assigneeIds"` // 待处理人ID列表（调用方可根据ID自行查询用户信息）
	CreatedAt   string        `json:"createdAt"`   // 任务创建时间
	Fields      []VertexField `json:"fields"`      // 节点字段列表
}

type PlatformConfig struct {
	Id          string `json:"id"`                 // 配置UUID
	TenantId    string `json:"tenantId"`           // 租户ID
	Host        string `json:"host"`               // 数据库地址
	Port        int    `json:"port"`               // 端口
	Database    string `json:"database"`           // 数据库名
	Username    string `json:"username"`           // 用户名
	Password    string `json:"password,omitempty"` // 密码（敏感，查询时不返回）
	NamespaceId int    `json:"namespaceId"`        // 命名空间ID
	ApiBaseUrl  string `json:"apiBaseUrl"`         // Skylark API基础地址（纯域名，如：skylark.example.com）
	ApiToken    string `json:"apiToken,omitempty"` // API认证Token（敏感，查询时不返回）
	CreatedBy   string `json:"createdBy,optional"` // 创建者
	UpdatedBy   string `json:"updatedBy,optional"` // 更新者
	CreatedAt   string `json:"createdAt,optional"` // 创建时间
	UpdatedAt   string `json:"updatedAt,optional"` // 更新时间
}

type ProcessingUser struct {
	Id         string   `json:"id"`                  // 用户UUID
	Name       string   `json:"name"`                // 用户姓名
	Nickname   string   `json:"nickname,optional"`   // 用户昵称
	Phone      string   `json:"phone,optional"`      // 手机号
	Identifier string   `json:"identifier,optional"` // 工号/身份证号
	Headimgurl string   `json:"headimgurl,optional"` // 头像URL
	Tags       []string `json:"tags,optional"`       // 用户标签
}

type QueryEventDataRequest struct {
	EventId   string   `path:"eventId"`            // 事件配置ID（路径参数）
	OrgId     string   `json:"orgId"`              // 组织ID（必填，前端指定，后端验证权限）
	Page      int      `json:"page,optional"`      // 页码（从1开始）
	PageSize  int      `json:"pageSize,optional"`  // 每页数量
	Keyword   string   `json:"keyword,optional"`   // 关键词搜索
	SortField string   `json:"sortField,optional"` // 排序字段
	SortOrder string   `json:"sortOrder,optional"` // 排序方向：asc/desc
	Status    []string `json:"status,optional"`    // 状态筛选（可选，支持多个状态：processing/finished/cancelled等）
}

type QueryEventDataResponse struct {
	BaseResponse
	Data struct {
		Columns []ColumnInfo             `json:"columns"` // 列定义
		Records []map[string]interface{} `json:"records"` // 数据记录（动态字段）
		Total   int64                    `json:"total"`   // 总记录数
	} `json:"data,omitempty"`
}

type SavePlatformConfigRequest struct {
	Host        string `json:"host"`        // 数据库地址（必填）
	Port        int    `json:"port"`        // 端口（必填）
	Database    string `json:"database"`    // 数据库名（必填）
	Username    string `json:"username"`    // 用户名（必填）
	Password    string `json:"password"`    // 密码（必填）
	NamespaceId int    `json:"namespaceId"` // 命名空间ID（必填）
	ApiBaseUrl  string `json:"apiBaseUrl"`  // Skylark API基础地址（纯域名，必填）
	ApiToken    string `json:"apiToken"`    // API认证Token（必填）
}

type SavePlatformConfigResponse struct {
	BaseResponse
	Data struct {
		Id string `json:"id"` // 平台配置UUID
	} `json:"data,omitempty"`
}

type SearchJourneysData struct {
	List  []Journey `json:"list"`  // 流程列表
	Total int       `json:"total"` // 总数
}

type SearchJourneysRequest struct {
	FlowId int64 `path:"flowId"` // 流程ID（路径参数）
	JourneySearchRequest
}

type SearchJourneysResponse struct {
	BaseResponse
	Data SearchJourneysData `json:"data"`
}

type StatsQueryParams struct {
	EventIds []string `form:"eventIds,optional"` // 事件配置ID列表（必填，支持单个或多个ID）
	OrgId    string   `form:"orgId"`             // 组织ID（必填，前端指定，后端验证权限）
	DateFrom string   `form:"dateFrom,optional"` // 开始日期（ISO格式，可选）
	DateTo   string   `form:"dateTo,optional"`   // 结束日期（ISO格式，可选）
	Status   string   `form:"status,optional"`   // 按状态筛选（可选，如"completed"）
}

type StatusCount struct {
	Status     string  `json:"status"`     // 状态显示名称（中文）
	StatusKey  string  `json:"statusKey"`  // 状态原始值（英文）
	Count      int64   `json:"count"`      // 该状态的事件数量
	Percentage float64 `json:"percentage"` // 占比（0-100）
}

type TestPlatformConnectionRequest struct {
	Host        string `json:"host"`        // 数据库地址
	Port        int    `json:"port"`        // 端口
	Database    string `json:"database"`    // 数据库名
	Username    string `json:"username"`    // 用户名
	Password    string `json:"password"`    // 密码
	NamespaceId int    `json:"namespaceId"` // 命名空间ID
	ApiBaseUrl  string `json:"apiBaseUrl"`  // Skylark API基础地址（纯域名）
	ApiToken    string `json:"apiToken"`    // API认证Token
}

type TestPlatformConnectionResponse struct {
	BaseResponse
	Data struct {
		Success    bool   `json:"success"`             // 连接是否成功
		FlowsCount int    `json:"flowsCount,optional"` // flows数量
		Message    string `json:"message,optional"`    // 消息
	} `json:"data,omitempty"`
}

type TrendPoint struct {
	Date           string  `json:"date"`           // 日期（YYYY-MM-DD 或 YYYY-WW 或 YYYY-MM）
	TotalCount     int64   `json:"totalCount"`     // 该时间段新增的总事件数
	CompletedCount int64   `json:"completedCount"` // 该时间段完成的事件数
	CompletionRate float64 `json:"completionRate"` // 完成率（0-100）
}

type TypedValue struct {
	Type  string      `json:"type"`  // string/number/boolean/date/array/object/file
	Value interface{} `json:"value"` // 字段值
}

type UpdateEventConfigWithFieldsRequest struct {
	EventIdPathRequest
	Name         string             `json:"name,optional"`         // 事件名称
	OrgFieldName string             `json:"orgFieldName,optional"` // 组织字段名
	Description  string             `json:"description,optional"`  // 描述
	Enabled      bool               `json:"enabled,optional"`      // 是否启用
	Fields       []FieldConfigInput `json:"fields"`                // 字段配置列表（完整替换）
}

type UpdateEventConfigWithFieldsResponse struct {
	BaseResponse
}

type UpdateFlowJourneyStatusRequest struct {
	FlowId            int64                 `path:"flowId"`                     // 流程ID（路径参数）
	JourneyId         int64                 `path:"journeyId"`                  // Journey ID（路径参数）
	AssignmentId      int64                 `json:"assignmentId"`               // Assignment ID（必填）
	Operation         string                `json:"operation"`                  // 操作类型：approve/refuse/transfer/cancel
	Comment           string                `json:"comment,optional"`           // 处理意见（可选）
	CarbonCopyUserIds []string              `json:"carbonCopyUserIds,optional"` // 抄送用户UUID列表（可选）
	Data              map[string]TypedValue `json:"data,optional"`              // 字段数据更新（可选）
}

type UpdateFlowJourneyStatusResponse struct {
	BaseResponse
}

type UpdateOrgMappingRequest struct {
	OrgMappingIdPathRequest
	RemoteOrgValue string `json:"remoteOrgValue,optional"` // 远程组织值
	LocalOrgId     string `json:"localOrgId,optional"`     // 本地组织ID
}

type UpdateOrgMappingResponse struct {
	BaseResponse
}

type UserMetric struct {
	UserId   string `json:"userId"`   // 用户ID
	UserName string `json:"userName"` // 用户姓名
	Count    int64  `json:"count"`    // 处理的事件数量
	Rank     int    `json:"rank"`     // 排名（1开始）
}

type VertexField struct {
	Id          int64         `json:"id"`          // 字段ID
	IdentityKey string        `json:"identityKey"` // 字段唯一标识键（用于Data参数）
	Title       string        `json:"title"`       // 字段标题
	Type        string        `json:"type"`        // 字段类型（如 Field::RadioButton）
	Required    bool          `json:"required"`    // 是否必填
	Editable    bool          `json:"editable"`    // 是否可编辑
	MaxLength   int           `json:"maxLength"`   // 字数限制（0表示无限制）
	Options     []FieldOption `json:"options"`     // 字段可选项
}
