// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	block "github.com/rezeropoint/nexlyn/restful/lynxmanager/internal/handler/block"
	graphconfig "github.com/rezeropoint/nexlyn/restful/lynxmanager/internal/handler/graphconfig"
	infoatomtype "github.com/rezeropoint/nexlyn/restful/lynxmanager/internal/handler/infoatomtype"
	tag "github.com/rezeropoint/nexlyn/restful/lynxmanager/internal/handler/tag"
	"github.com/rezeropoint/nexlyn/restful/lynxmanager/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 查询逻辑块规格列表
				Method:  http.MethodGet,
				Path:    "/block/specs",
				Handler: block.GetBlockSpecsHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/lynxmanager"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 创建逻辑图配置
				Method:  http.MethodPost,
				Path:    "/graph/create",
				Handler: graphconfig.CreateGraphConfigHandler(serverCtx),
			},
			{
				// 删除逻辑图配置
				Method:  http.MethodDelete,
				Path:    "/graph/delete/:id",
				Handler: graphconfig.DeleteGraphConfigHandler(serverCtx),
			},
			{
				// 获取逻辑图配置详情
				Method:  http.MethodGet,
				Path:    "/graph/get/:id",
				Handler: graphconfig.GetGraphConfigHandler(serverCtx),
			},
			{
				// 查询逻辑图配置列表
				Method:  http.MethodGet,
				Path:    "/graph/list",
				Handler: graphconfig.GetGraphConfigListHandler(serverCtx),
			},
			{
				// 更新逻辑图配置
				Method:  http.MethodPut,
				Path:    "/graph/update/:id",
				Handler: graphconfig.UpdateGraphConfigHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/lynxmanager"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 创建信息原子类型
				Method:  http.MethodPost,
				Path:    "/infoatom-type/create",
				Handler: infoatomtype.CreateInfoAtomTypeHandler(serverCtx),
			},
			{
				// 删除信息原子类型
				Method:  http.MethodDelete,
				Path:    "/infoatom-type/delete/:id",
				Handler: infoatomtype.DeleteInfoAtomTypeHandler(serverCtx),
			},
			{
				// 获取信息原子类型详情
				Method:  http.MethodGet,
				Path:    "/infoatom-type/get/:id",
				Handler: infoatomtype.GetInfoAtomTypeHandler(serverCtx),
			},
			{
				// 查询信息原子类型列表
				Method:  http.MethodGet,
				Path:    "/infoatom-type/list",
				Handler: infoatomtype.GetInfoAtomTypeListHandler(serverCtx),
			},
			{
				// 更新信息原子类型
				Method:  http.MethodPut,
				Path:    "/infoatom-type/update/:id",
				Handler: infoatomtype.UpdateInfoAtomTypeHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/lynxmanager"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 创建标签
				Method:  http.MethodPost,
				Path:    "/tags",
				Handler: tag.CreateTagHandler(serverCtx),
			},
			{
				// 查询标签列表
				Method:  http.MethodGet,
				Path:    "/tags",
				Handler: tag.ListTagsHandler(serverCtx),
			},
			{
				// 获取标签详情
				Method:  http.MethodGet,
				Path:    "/tags/:id",
				Handler: tag.GetTagHandler(serverCtx),
			},
			{
				// 更新标签
				Method:  http.MethodPut,
				Path:    "/tags/:id",
				Handler: tag.UpdateTagHandler(serverCtx),
			},
			{
				// 删除标签
				Method:  http.MethodDelete,
				Path:    "/tags/:id",
				Handler: tag.DeleteTagHandler(serverCtx),
			},
			{
				// 批量查询标签（用于自动补全）
				Method:  http.MethodPost,
				Path:    "/tags/batch-query",
				Handler: tag.BatchQueryTagsHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/lynxmanager"),
	)
}
