// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AIBoxAbility struct {
	Attribute  AIBoxAttribute   `json:"attribute"`  // 算法属性
	Parameters []AIBoxParameter `json:"parameters"` // 算法可设置的配置项
	Permitted  bool             `json:"permitted"`  // 算法是否已授权
	Code       int              `json:"code"`       // 主算法编号
	Sub        bool             `json:"sub"`        // 是否是子算法
	Name       string           `json:"name"`       // 算法名称
	Desc       string           `json:"desc"`       // 算法描述
	Item       int              `json:"item"`       // 子算法编号
	Policy     []AIBoxPolicy    `json:"policy"`     // 报警规则
}

type AIBoxAlgorithmTask struct {
	AlgTaskSession string                 `json:"alg_task_session"`    // 任务会话ID
	TaskDesc       string                 `json:"task_desc"`           // 任务描述
	MediaName      string                 `json:"media_name"`          // 媒体名称
	AlgInfo        []int                  `json:"alg_info"`            // 算法信息列表
	AlgTaskStatus  AIBoxTaskStatus        `json:"alg_task_status"`     // 任务运行状态
	AlarmBody      int                    `json:"alarm_body"`          // 告警主体
	AlarmProtocol  int                    `json:"alarm_protocol"`      // 告警协议
	MetadataUrl    interface{}            `json:"metadata_url"`        // 元数据URL（可能是string或[]string）
	UserData       map[string]interface{} `json:"user_data,omitempty"` // 用户自定义数据
}

type AIBoxAttribute struct {
	LineRequired bool   `json:"lineRequired"` // 是否必须配置辅助线
	LineDesc     string `json:"lineDesc"`     // 配置辅助线的描述文字
	ZoneRequired bool   `json:"zoneRequired"` // 是否必须配置算法专用区域
	ZoneDesc     string `json:"zoneDesc"`     // 配置算法专用区域的描述文字
}

type AIBoxCapabilities struct {
	BoardId   string         `json:"board_id"`  // 盒子ID
	Abilities []AIBoxAbility `json:"abilities"` // 完整算法能力列表
}

type AIBoxParameter struct {
	Class    string                 `json:"class"`             // 设置项数据类型描述（FLOAT/BOOLEAN/SELECTOR/INTEGER）
	Type     int                    `json:"type"`              // 设置项数据类型编号（FLOAT=>2, BOOLEAN=>4, SELECTOR=>5, INTEGER=>0）
	Max      interface{}            `json:"max,omitempty"`     // 可设置最大值（FLOAT/INTEGER时存在）
	Min      interface{}            `json:"min,omitempty"`     // 可设置最小值（FLOAT/INTEGER时存在）
	Default  interface{}            `json:"default"`           // 设置项默认值
	Key      string                 `json:"key"`               // 设置项标识
	Name     string                 `json:"name"`              // 设置项名称
	Required bool                   `json:"required"`          // 是否必填
	Value    interface{}            `json:"value"`             // 设置值
	Options  []AIBoxParameterOption `json:"options,omitempty"` // SELECTOR待选列表
}

type AIBoxParameterOption struct {
	Enable bool        `json:"enable"` // 当前选项是否可选
	Key    string      `json:"key"`    // 选项标识
	Value  interface{} `json:"value"`  // 选项序号（可能是int或空字符串""）
	Name   string      `json:"name"`   // 选项名称
}

type AIBoxPolicy struct {
	Property string `json:"property"` // 违规的属性名（告警类型）
	Name     string `json:"name"`     // 属性名描述（告警类型的中文描述）
}

type AIBoxTaskStatus struct {
	Type  int    `json:"type"`  // 状态级别标识（1/2/3/4）
	Style string `json:"style"` // 状态级别（normal/warning/danger/success）
	Label string `json:"label"` // 状态描述
}

type BaseResponse struct {
	Code int64  `json:"code"`          // 响应码
	Msg  string `json:"msg,omitempty"` // 响应消息
}

type BindDeviceRequest struct {
	DeviceId         string   `json:"deviceId"`                  // 设备唯一标识符(必填)
	DeviceName       string   `json:"deviceName"`                // 设备名称(必填)
	DeviceAlias      string   `json:"deviceAlias,optional"`      // 设备别名
	DeviceModel      string   `json:"deviceModel"`               // 设备型号(必填,关联模板)
	Description      string   `json:"description,optional"`      // 设备描述
	Location         string   `json:"location,optional"`         // 安装位置
	InstallationDate string   `json:"installationDate,optional"` // 安装日期
	Status           string   `json:"status,optional"`           // 设备状态(默认active)
	TagIds           []string `json:"tagIds,optional"`           // 标签ID列表(绑定时)
}

type BindDeviceResponse struct {
	BaseResponse
	Data struct {
		Id       string `json:"id"`       // 设备绑定记录ID
		DeviceId string `json:"deviceId"` // 设备ID
	} `json:"data,omitempty"`
}

type Condition struct {
	Field    string      `json:"field"`    // 字段名（对应StandardField）
	Operator string      `json:"operator"` // 操作符：eq/ne/gt/lt/gte/lte/contains/in/not_in
	Value    interface{} `json:"value"`    // 比较值
}

type ControlAIBoxTaskRequest struct {
	DeviceIdControlPathRequest
	TaskIdPathRequest
	OrgId          string `form:"orgId"`          // 组织ID（必填）
	ControlCommand int    `json:"controlCommand"` // 启停标识（0停止, 1启动）
}

type ControlAIBoxTaskResponse struct {
	BaseResponse
	Data struct {
		Message string `json:"message"` // 执行结果描述
	} `json:"data,omitempty"`
}

type CreatePlatformRequest struct {
	Type              string            `json:"type"`                       // 平台类型：skylark/webhook/kafka（必填）
	Name              string            `json:"name"`                       // 配置名称（必填）
	Description       string            `json:"description,optional"`       // 配置描述
	Enabled           bool              `json:"enabled,optional"`           // 是否启用（默认true）
	SkylarkDomain     string            `json:"skylarkDomain,optional"`     // Skylark域名
	SkylarkAuthHeader string            `json:"skylarkAuthHeader,optional"` // Skylark认证头
	SkylarkUserID     int64             `json:"skylarkUserID,optional"`     // Skylark用户ID
	WebhookURL        string            `json:"webhookUrl,optional"`        // Webhook URL
	WebhookHeaders    map[string]string `json:"webhookHeaders,optional"`    // 自定义请求头
	WebhookMethod     string            `json:"webhookMethod,optional"`     // HTTP方法
	KafkaBrokers      []string          `json:"kafkaBrokers,optional"`      // Kafka Brokers
	KafkaTopic        string            `json:"kafkaTopic,optional"`        // Kafka Topic
}

type CreatePlatformResponse struct {
	BaseResponse
	Data struct {
		Type string `json:"type"` // 平台类型
		Id   string `json:"id"`   // 平台配置UUID（系统自动生成）
		Name string `json:"name"` // 配置名称
	} `json:"data,omitempty"`
}

type CreateSensorTemplateRequest struct {
	Model          string                `json:"model"`                   // 设备型号标识（必填，唯一）
	Name           string                `json:"name"`                    // 模板显示名称（必填）
	Category       string                `json:"category"`                // 设备类别（必填）
	Manufacturer   string                `json:"manufacturer,optional"`   // 设备厂商
	Description    string                `json:"description,optional"`    // 模板描述
	Version        string                `json:"version,optional"`        // 模板版本号
	Enabled        bool                  `json:"enabled,optional"`        // 是否启用（默认true）
	OnlineConfig   OnlineDetectionConfig `json:"onlineConfig,optional"`   // 在线检测配置（可选，创建时可不配置）
	BusinessConfig DataProcessingConfig  `json:"businessConfig,optional"` // 业务数据处理配置（可选，创建时可不配置）
	ControlConfig  DeviceControlConfig   `json:"controlConfig,optional"`  // 设备控制配置（可选，创建时可不配置）
}

type CreateSensorTemplateResponse struct {
	BaseResponse
	Data struct {
		Id    string `json:"id"`    // 模板ID
		Model string `json:"model"` // 设备型号
		Name  string `json:"name"`  // 模板名称
	} `json:"data,omitempty"`
}

type CreateTagRequest struct {
	Name        string `json:"name"`                 // 标签名称(必填)
	Color       string `json:"color,optional"`       // 标签颜色
	Icon        string `json:"icon,optional"`        // 标签图标
	Description string `json:"description,optional"` // 标签描述
}

type CreateTagResponse struct {
	BaseResponse
	Data struct {
		Id   string `json:"id"`   // 标签ID
		Name string `json:"name"` // 标签名称
	} `json:"data,omitempty"`
}

type DataProcessingConfig struct {
	Category        string           `json:"category"`                 // 设备类别
	Model           string           `json:"model"`                    // 设备型号
	TopicSuffix     string           `json:"topicSuffix"`              // 主题后缀
	TimestampPath   string           `json:"timestampPath,optional"`   // 时间戳路径
	TimestampFormat string           `json:"timestampFormat,optional"` // 时间戳格式
	FieldMappings   []FieldMapping   `json:"fieldMappings"`            // 字段映射规则
	FilterRules     *FilterRule      `json:"filterRules,optional"`     // 数据过滤规则（用于分发前筛选）
	DispatchConfigs []DispatchConfig `json:"dispatchConfigs,optional"` // 分发配置
}

type DeletePlatformRequest struct {
	PlatformIdPathRequest
}

type DeletePlatformResponse struct {
	BaseResponse
}

type DeleteSensorTemplateRequest struct {
	SensorTemplateIdPathRequest
}

type DeleteSensorTemplateResponse struct {
	BaseResponse
}

type DeleteTagRequest struct {
	TagIdPathRequest
}

type DeleteTagResponse struct {
	BaseResponse
}

type DeviceBinding struct {
	Id                    string             `json:"id"`                    // 设备绑定记录ID(UUID)
	DeviceId              string             `json:"deviceId"`              // 设备唯一标识符
	DeviceName            string             `json:"deviceName"`            // 设备名称
	DeviceAlias           string             `json:"deviceAlias"`           // 设备别名
	DeviceModel           string             `json:"deviceModel"`           // 设备型号(关联iot_sensor_templates.model)
	DeviceCategory        string             `json:"deviceCategory"`        // 设备类别(冗余字段)
	Description           string             `json:"description"`           // 设备描述
	Location              string             `json:"location"`              // 安装位置
	InstallationDate      string             `json:"installationDate"`      // 安装日期(YYYY-MM-DD)
	Status                string             `json:"status"`                // 设备状态(active/inactive/maintenance/error/decommissioned)
	IsOnline              bool               `json:"isOnline"`              // 当前在线状态(从Redis实时查询)
	OnlineStatusUpdatedAt string             `json:"onlineStatusUpdatedAt"` // 在线状态最后更新时间
	LastOnlineAt          string             `json:"lastOnlineAt"`          // 最后在线时间
	LastOfflineAt         string             `json:"lastOfflineAt"`         // 最后离线时间
	LastDataAt            string             `json:"lastDataAt"`            // 最后接收数据时间
	TenantId              string             `json:"tenantId"`              // 所属租户ID(UUID)
	OrgId                 string             `json:"orgId"`                 // 所属组织ID(UUID)
	OrgName               string             `json:"orgName"`               // 所属组织名称
	Tags                  []DeviceTagSummary `json:"tags"`                  // 关联的标签列表
	CreatedBy             string             `json:"createdBy"`             // 创建者用户ID(UUID)
	UpdatedBy             string             `json:"updatedBy"`             // 最后修改者用户ID(UUID)
	CreatedAt             string             `json:"createdAt"`             // 创建时间
	UpdatedAt             string             `json:"updatedAt"`             // 更新时间
}

type DeviceBindingSummary struct {
	Id             string             `json:"id"`             // 设备绑定记录ID
	DeviceId       string             `json:"deviceId"`       // 设备唯一标识符
	DeviceName     string             `json:"deviceName"`     // 设备名称
	DeviceAlias    string             `json:"deviceAlias"`    // 设备别名
	DeviceModel    string             `json:"deviceModel"`    // 设备型号
	DeviceCategory string             `json:"deviceCategory"` // 设备类别
	Location       string             `json:"location"`       // 安装位置
	Status         string             `json:"status"`         // 设备状态
	IsOnline       bool               `json:"isOnline"`       // 当前在线状态(从Redis实时查询)
	LastDataAt     string             `json:"lastDataAt"`     // 最后接收数据时间
	OrgId          string             `json:"orgId"`          // 所属组织ID
	OrgName        string             `json:"orgName"`        // 所属组织名称
	Tags           []DeviceTagSummary `json:"tags"`           // 关联的标签列表
	CreatedAt      string             `json:"createdAt"`      // 创建时间
}

type DeviceCategoryInfo struct {
	Code        string `json:"code"`        // 类别代码（如：temp_humidity_smoke_sensor, ai_box）
	Name        string `json:"name"`        // 中文名称（如：温湿度烟雾传感器）
	NameEn      string `json:"nameEn"`      // 英文名称（如：Temperature Sensor）
	Description string `json:"description"` // 描述
	Icon        string `json:"icon"`        // 图标名称（用于前端展示）
}

type DeviceControlConfig struct {
	Category       string `json:"category"`       // 设备类别
	Model          string `json:"model"`          // 设备型号
	CommandSuffix  string `json:"commandSuffix"`  // 命令主题后缀
	ResponseSuffix string `json:"responseSuffix"` // 响应主题后缀
}

type DeviceIdControlPathRequest struct {
	DeviceId string `path:"deviceId"` // 设备ID
}

type DeviceIdPathRequest struct {
	DeviceId string `path:"deviceId"` // 设备ID
}

type DeviceLatestValuesItem struct {
	DeviceId string                `json:"deviceId"` // 设备ID
	Fields   map[string]FieldValue `json:"fields"`   // 字段名->字段值映射
}

type DeviceStatisticsItem struct {
	DeviceId    string                   `json:"deviceId"`    // 设备ID
	DeviceModel string                   `json:"deviceModel"` // 设备型号
	Fields      map[string]FieldStatItem `json:"fields"`      // 字段名->统计信息映射
}

type DeviceTag struct {
	Id          string `json:"id"`          // 标签ID(UUID)
	Name        string `json:"name"`        // 标签名称
	Color       string `json:"color"`       // 标签颜色(HEX格式,如:#FF5733)
	Icon        string `json:"icon"`        // 标签图标
	Description string `json:"description"` // 标签描述
	TenantId    string `json:"tenantId"`    // 所属租户ID(UUID)
	DeviceCount int    `json:"deviceCount"` // 使用该标签的设备数量
	CreatedBy   string `json:"createdBy"`   // 创建者用户ID(UUID)
	UpdatedBy   string `json:"updatedBy"`   // 最后修改者用户ID(UUID)
	CreatedAt   string `json:"createdAt"`   // 创建时间
	UpdatedAt   string `json:"updatedAt"`   // 更新时间
}

type DeviceTagMetadata struct {
	Name        string `json:"name"`                 // 标签名称(必填)
	Color       string `json:"color,optional"`       // 标签颜色
	Icon        string `json:"icon,optional"`        // 标签图标
	Description string `json:"description,optional"` // 标签描述
}

type DeviceTagSummary struct {
	Id          string `json:"id"`          // 标签ID
	Name        string `json:"name"`        // 标签名称
	Color       string `json:"color"`       // 标签颜色
	Description string `json:"description"` // 标签描述
}

type DeviceTagUpdate struct {
	Name        string `json:"name,optional"`        // 标签名称
	Color       string `json:"color,optional"`       // 标签颜色
	Icon        string `json:"icon,optional"`        // 标签图标
	Description string `json:"description,optional"` // 标签描述
}

type DispatchConfig struct {
	Type        string                 `json:"type"`                 // 分发类型：skylark_flows/skylark_forms/log/save
	PlatformID  string                 `json:"platformID,optional"`  // 平台配置ID（关联平台配置）
	FlowID      int64                  `json:"flowID,optional"`      // Skylark流程ID（type=skylark_flows时必填）
	FormID      int64                  `json:"formID,optional"`      // Skylark表单ID（type=skylark_forms时必填）
	ExtraParams map[string]interface{} `json:"extraParams,optional"` // 扩展参数（其他平台使用）
}

type FieldCheck struct {
	Field    string   `json:"field"`             // 字段路径（点分隔）
	Operator string   `json:"operator,optional"` // 检查操作：exists/equals/in（默认exists）
	Value    string   `json:"value,optional"`    // 期望值（operator=equals时使用）
	Values   []string `json:"values,optional"`   // 期望值列表（operator=in时使用）
}

type FieldMapping struct {
	StandardField string  `json:"standardField"`         // 平台标准字段名
	SourcePath    string  `json:"sourcePath"`            // 源字段路径（点分隔）
	FieldType     string  `json:"fieldType,optional"`    // 字段类型
	Scale         float64 `json:"scale,optional"`        // 缩放因子
	Offset        float64 `json:"offset,optional"`       // 偏移量
	DefaultValue  string  `json:"defaultValue,optional"` // 默认值
}

type FieldStatItem struct {
	Min       float64     `json:"min"`       // 最小值
	Max       float64     `json:"max"`       // 最大值
	Avg       float64     `json:"avg"`       // 平均值
	Sum       float64     `json:"sum"`       // 总和
	Count     int64       `json:"count"`     // 数据点数量
	LastValue interface{} `json:"lastValue"` // 最新值
	LastTime  string      `json:"lastTime"`  // 最新值时间戳
}

type FieldValue struct {
	Value     interface{} `json:"value"`     // 字段值
	Timestamp string      `json:"timestamp"` // 时间戳
}

type FilterRule struct {
	Conditions []Condition `json:"conditions"`     // 过滤条件列表
	Logic      string      `json:"logic,optional"` // 逻辑关系：AND/OR，默认AND
}

type GetAIBoxCapabilitiesRequest struct {
	DeviceIdControlPathRequest
	OrgId string `form:"orgId"` // 组织ID（必填）
}

type GetAIBoxCapabilitiesResponse struct {
	BaseResponse
	Data AIBoxCapabilities `json:"data,omitempty"` // 算法能力
}

type GetDeviceCategoriesRequest struct {
}

type GetDeviceCategoriesResponse struct {
	BaseResponse
	Data struct {
		Categories []DeviceCategoryInfo `json:"categories"` // 设备类别列表
	} `json:"data,omitempty"`
}

type GetDeviceRequest struct {
	DeviceIdPathRequest
	OrgId string `form:"orgId"` // 组织ID(必填)
}

type GetDeviceResponse struct {
	BaseResponse
	Data DeviceBinding `json:"data,omitempty"` // 设备详情(含实时在线状态)
}

type GetDeviceStatisticsRequest struct {
	OrgId      string   `json:"orgId"`              // 组织ID（必填）
	DeviceIds  []string `json:"deviceIds,optional"` // 设备ID列表（可选）
	FieldNames []string `json:"fieldNames"`         // 字段列表（必填）
	StartTime  string   `json:"startTime"`          // 开始时间（ISO8601格式）
	EndTime    string   `json:"endTime"`            // 结束时间（ISO8601格式）
}

type GetDeviceStatisticsResponse struct {
	BaseResponse
	Data []DeviceStatisticsItem `json:"data"`
}

type GetLatestValuesRequest struct {
	OrgId      string   `json:"orgId"`              // 组织ID（必填）
	DeviceIds  []string `json:"deviceIds,optional"` // 设备ID列表（可选）
	FieldNames []string `json:"fieldNames"`         // 字段列表（必填）
}

type GetLatestValuesResponse struct {
	BaseResponse
	Data []DeviceLatestValuesItem `json:"data"`
}

type GetPlatformListRequest struct {
	PageParamsRequest
	Type    string `form:"type,optional"`    // 平台类型筛选
	Keyword string `form:"keyword,optional"` // 关键词搜索（ID或名称）
}

type GetPlatformListResponse struct {
	BaseResponse
	PageParams
	Data struct {
		List []PlatformMetadata `json:"list"` // 平台配置列表（仅元数据）
	} `json:"data,omitempty"`
}

type GetPlatformRequest struct {
	PlatformIdPathRequest
}

type GetPlatformResponse struct {
	BaseResponse
	Data PlatformDetail `json:"data,omitempty"` // 平台配置详情（含敏感配置）
}

type GetSensorTemplateListRequest struct {
	PageParamsRequest
	Model        string `form:"model,optional"`        // 型号筛选
	Name         string `form:"name,optional"`         // 名称模糊查询
	Category     string `form:"category,optional"`     // 类别筛选
	Manufacturer string `form:"manufacturer,optional"` // 厂商筛选
	Enabled      string `form:"enabled,optional"`      // 启用状态筛选（true/false）
}

type GetSensorTemplateListResponse struct {
	BaseResponse
	PageParams
	Data struct {
		List []SensorTemplate `json:"list"` // 模板列表
	} `json:"data,omitempty"`
}

type GetSensorTemplateRequest struct {
	SensorTemplateIdPathRequest
}

type GetSensorTemplateResponse struct {
	BaseResponse
	Data SensorTemplateDetail `json:"data,omitempty"` // 模板详情（包含Etcd配置）
}

type GetStandardFieldsRequest struct {
	Category string `path:"category"` // 设备类别代码（如：temp_humidity_smoke_sensor, ai_box）
}

type GetStandardFieldsResponse struct {
	BaseResponse
	Data struct {
		Fields []StandardFieldInfo `json:"fields"` // 标准字段列表
	} `json:"data,omitempty"`
}

type GetTagRequest struct {
	TagIdPathRequest
}

type GetTagResponse struct {
	BaseResponse
	Data DeviceTag `json:"data,omitempty"` // 标签详情
}

type KafkaConfig struct {
	KafkaBrokers []string `json:"kafkaBrokers"` // Kafka Brokers
	KafkaTopic   string   `json:"kafkaTopic"`   // Kafka Topic
}

type ListAIBoxTasksRequest struct {
	DeviceIdControlPathRequest
	OrgId string `form:"orgId"` // 组织ID（必填）
}

type ListAIBoxTasksResponse struct {
	BaseResponse
	Data struct {
		List []AIBoxAlgorithmTask `json:"list"` // 任务列表
	} `json:"data,omitempty"`
}

type ListDevicesRequest struct {
	PageParamsRequest
	OrgId          string `form:"orgId"`                   // 组织ID筛选(必填)
	DeviceModel    string `form:"deviceModel,optional"`    // 设备型号筛选
	DeviceCategory string `form:"deviceCategory,optional"` // 设备类别筛选
	Status         string `form:"status,optional"`         // 设备状态筛选
	IsOnline       string `form:"isOnline,optional"`       // 在线状态筛选(true/false)
	Keyword        string `form:"keyword,optional"`        // 关键词搜索(设备ID、名称、别名)
}

type ListDevicesResponse struct {
	BaseResponse
	PageParams
	Data struct {
		List []DeviceBindingSummary `json:"list"` // 设备列表(含实时在线状态)
	} `json:"data,omitempty"`
}

type ListTagsRequest struct {
	PageParamsRequest
	Name    string `form:"name,optional"`    // 名称模糊查询
	Keyword string `form:"keyword,optional"` // 关键词搜索(名称、描述)
}

type ListTagsResponse struct {
	BaseResponse
	PageParams
	Data struct {
		List []DeviceTagSummary `json:"list"` // 标签列表
	} `json:"data,omitempty"`
}

type ListUnboundDevicesRequest struct {
}

type ListUnboundDevicesResponse struct {
	BaseResponse
	Data struct {
		List []UnboundDevice `json:"list"` // 未绑定设备列表
	} `json:"data,omitempty"`
}

type OnlineDetectionConfig struct {
	Category       string       `json:"category"`             // 设备类别
	Model          string       `json:"model"`                // 设备型号
	TopicSuffix    string       `json:"topicSuffix"`          // 主题后缀
	Strategy       string       `json:"strategy"`             // 检测策略：field_check/any_data
	TimeoutSeconds int          `json:"timeoutSeconds"`       // 超时时间（秒）
	FieldChecks    []FieldCheck `json:"fieldChecks,optional"` // 字段检查规则（strategy=field_check时必填）
}

type PageParams struct {
	Current  int64 `json:"current,omitempty"`  // 当前页码
	PageSize int64 `json:"pageSize,omitempty"` // 每页大小
	Total    int64 `json:"total,omitempty"`    // 总记录数
}

type PageParamsRequest struct {
	Current  int64 `form:"current,optional"`  // 当前页码
	PageSize int64 `form:"pageSize,optional"` // 每页大小
}

type PlatformDetail struct {
	PlatformMetadata
	Config interface{} `json:"config,optional"` // 平台特定配置（根据type解析）
}

type PlatformIdPathRequest struct {
	Id string `path:"id"` // 平台配置ID
}

type PlatformMetadata struct {
	Id          string `json:"id"`                   // 配置UUID（系统自动生成）
	Type        string `json:"type"`                 // 平台类型：skylark/webhook/kafka
	Name        string `json:"name"`                 // 配置显示名称
	Description string `json:"description,optional"` // 配置描述
	Enabled     bool   `json:"enabled"`              // 是否启用
	TenantId    string `json:"tenantId"`             // 租户ID
	CreatedBy   string `json:"createdBy,optional"`   // 创建者
	UpdatedBy   string `json:"updatedBy,optional"`   // 更新者
	CreatedAt   string `json:"createdAt,optional"`   // 创建时间
	UpdatedAt   string `json:"updatedAt,optional"`   // 更新时间
}

type QueryTimeSeriesRequest struct {
	OrgId       string   `json:"orgId"`                                                   // 组织ID（必填，REST层将查询其所有子组织）
	DeviceIds   []string `json:"deviceIds,optional"`                                      // 设备ID列表（可选，在组织范围内进一步过滤）
	FieldNames  []string `json:"fieldNames"`                                              // 查询字段列表（必填）
	StartTime   string   `json:"startTime"`                                               // 开始时间（ISO8601格式，如"2024-01-01T00:00:00Z"）
	EndTime     string   `json:"endTime"`                                                 // 结束时间（ISO8601格式）
	Aggregation string   `json:"aggregation,optional,options=avg|max|min|sum|count|last"` // 聚合类型（空表示原始数据）
	Interval    int64    `json:"interval,optional"`                                       // 聚合时间间隔（秒），仅在Aggregation非空时有效
	Limit       int64    `json:"limit,optional,range=[1:10000]"`                          // 限制返回条数（默认1000）
	Offset      int64    `json:"offset,optional,range=[0:]"`                              // 偏移量（默认0）
	OrderBy     string   `json:"orderBy,optional,options=timestamp|device_id"`            // 排序字段（默认timestamp）
	OrderDir    string   `json:"orderDir,optional,options=asc|desc|ASC|DESC,default=asc"` // 排序方向（默认asc）
}

type QueryTimeSeriesResponse struct {
	BaseResponse
	Data struct {
		List     []TimeSeriesDataItem `json:"list"`     // 数据列表
		Total    int64                `json:"total"`    // 总记录数
		Page     int64                `json:"page"`     // 当前页码
		PageSize int64                `json:"pageSize"` // 每页数量
	} `json:"data"`
}

type SensorTemplate struct {
	Id           string `json:"id"`           // 模板UUID
	Model        string `json:"model"`        // 设备型号标识（业务标识）
	Name         string `json:"name"`         // 模板显示名称
	Category     string `json:"category"`     // 设备类别
	Manufacturer string `json:"manufacturer"` // 设备厂商
	Description  string `json:"description"`  // 模板描述
	Version      string `json:"version"`      // 模板版本号
	Enabled      bool   `json:"enabled"`      // 是否启用
	DeviceCount  int    `json:"deviceCount"`  // 使用该模板的设备数量
	TenantId     string `json:"tenantId"`     // 租户ID
	CreatedBy    string `json:"createdBy"`    // 创建者用户ID
	UpdatedBy    string `json:"updatedBy"`    // 最后修改者用户ID
	CreatedAt    string `json:"createdAt"`    // 创建时间（ISO 8601）
	UpdatedAt    string `json:"updatedAt"`    // 更新时间（ISO 8601）
}

type SensorTemplateDetail struct {
	SensorTemplate
	OnlineConfig   OnlineDetectionConfig `json:"onlineConfig,optional"`   // 在线检测配置
	BusinessConfig DataProcessingConfig  `json:"businessConfig,optional"` // 业务数据处理配置
	ControlConfig  DeviceControlConfig   `json:"controlConfig,optional"`  // 设备控制配置
}

type SensorTemplateIdPathRequest struct {
	Id string `path:"id"` // 模板ID
}

type SkylarkConfig struct {
	SkylarkDomain     string `json:"skylarkDomain"`     // Skylark域名
	SkylarkAuthHeader string `json:"skylarkAuthHeader"` // Skylark认证头
	SkylarkUserID     int64  `json:"skylarkUserID"`     // Skylark用户ID
}

type StandardFieldInfo struct {
	Name        string   `json:"name"`                  // 字段名（如：temperature）
	DisplayName string   `json:"displayName"`           // 显示名称（如：温度）
	FieldType   string   `json:"fieldType"`             // 字段类型（string/number/boolean等）
	Unit        string   `json:"unit,omitempty"`        // 单位（如：℃, %, ppm）
	Description string   `json:"description,omitempty"` // 字段描述
	Required    bool     `json:"required"`              // 是否必填
	MinValue    float64  `json:"minValue,omitempty"`    // 最小值（数值类型）
	MaxValue    float64  `json:"maxValue,omitempty"`    // 最大值（数值类型）
	EnumValues  []string `json:"enumValues,omitempty"`  // 枚举值（枚举类型）
}

type TagIdPathRequest struct {
	TagId string `path:"tagId"` // 标签ID
}

type TaskIdPathRequest struct {
	TaskId string `path:"taskId"` // 任务ID
}

type TimeSeriesDataItem struct {
	Timestamp      string      `json:"timestamp"`      // 数据时间戳
	DeviceId       string      `json:"deviceId"`       // 设备唯一标识符
	DeviceModel    string      `json:"deviceModel"`    // 设备型号
	DeviceCategory string      `json:"deviceCategory"` // 设备类别
	FieldName      string      `json:"fieldName"`      // 字段名称
	Value          interface{} `json:"value"`          // 字段值
}

type UnbindDeviceRequest struct {
	DeviceIdPathRequest
	OrgId string `json:"orgId"` // 组织ID(必填)
}

type UnbindDeviceResponse struct {
	BaseResponse
}

type UnboundDevice struct {
	DeviceId string `json:"deviceId"` // 设备ID
	Category string `json:"category"` // 设备类别
	IsOnline bool   `json:"isOnline"` // 在线状态
	LastSeen string `json:"lastSeen"` // 最后上报时间
}

type UpdateDeviceRequest struct {
	DeviceIdPathRequest
	OrgId            string   `json:"orgId"`                     // 组织ID(必填)
	DeviceName       string   `json:"deviceName,optional"`       // 设备名称
	DeviceAlias      string   `json:"deviceAlias,optional"`      // 设备别名
	Description      string   `json:"description,optional"`      // 设备描述
	Location         string   `json:"location,optional"`         // 安装位置
	InstallationDate string   `json:"installationDate,optional"` // 安装日期
	Status           string   `json:"status,optional"`           // 设备状态
	TagIds           []string `json:"tagIds,optional"`           // 更新标签列表(完全替换)
}

type UpdateDeviceResponse struct {
	BaseResponse
}

type UpdatePlatformRequest struct {
	PlatformIdPathRequest
	Type              string            `json:"type"`                       // 平台类型：skylark/webhook/kafka（必填，不可修改）
	Name              string            `json:"name,optional"`              // 配置名称
	Description       string            `json:"description,optional"`       // 配置描述
	Enabled           bool              `json:"enabled,optional"`           // 是否启用
	SkylarkDomain     string            `json:"skylarkDomain,optional"`     // Skylark域名
	SkylarkAuthHeader string            `json:"skylarkAuthHeader,optional"` // Skylark认证头
	SkylarkUserID     int64             `json:"skylarkUserID,optional"`     // Skylark用户ID
	WebhookURL        string            `json:"webhookUrl,optional"`        // Webhook URL
	WebhookHeaders    map[string]string `json:"webhookHeaders,optional"`    // 自定义请求头
	WebhookMethod     string            `json:"webhookMethod,optional"`     // HTTP方法
	KafkaBrokers      []string          `json:"kafkaBrokers,optional"`      // Kafka Brokers
	KafkaTopic        string            `json:"kafkaTopic,optional"`        // Kafka Topic
}

type UpdatePlatformResponse struct {
	BaseResponse
}

type UpdateSensorTemplateRequest struct {
	SensorTemplateIdPathRequest
	Model          string                 `json:"model"`                   // 设备型号（必填，不允许修改）
	Name           string                 `json:"name,optional"`           // 模板显示名称
	Category       string                 `json:"category"`                // 设备类别（必填，不允许修改）
	Manufacturer   string                 `json:"manufacturer,optional"`   // 设备厂商
	Description    string                 `json:"description,optional"`    // 模板描述
	Version        string                 `json:"version,optional"`        // 模板版本号
	Enabled        bool                   `json:"enabled,optional"`        // 是否启用
	OnlineConfig   *OnlineDetectionConfig `json:"onlineConfig,optional"`   // 在线检测配置（nil=删除）
	BusinessConfig *DataProcessingConfig  `json:"businessConfig,optional"` // 业务数据处理配置（nil=删除）
	ControlConfig  *DeviceControlConfig   `json:"controlConfig,optional"`  // 设备控制配置（nil=删除）
}

type UpdateSensorTemplateResponse struct {
	BaseResponse
}

type UpdateTagRequest struct {
	TagIdPathRequest
	Name        string `json:"name,optional"`        // 标签名称
	Color       string `json:"color,optional"`       // 标签颜色
	Icon        string `json:"icon,optional"`        // 标签图标
	Description string `json:"description,optional"` // 标签描述
}

type UpdateTagResponse struct {
	BaseResponse
}

type WebhookConfig struct {
	WebhookURL     string            `json:"webhookUrl"`              // Webhook URL
	WebhookHeaders map[string]string `json:"webhookHeaders,optional"` // 自定义请求头
	WebhookMethod  string            `json:"webhookMethod,optional"`  // HTTP方法
}
