// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.4
// source: eventsync.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SyncUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`            // 租户ID
	LocalUserId   string                 `protobuf:"bytes,2,opt,name=local_user_id,json=localUserId,proto3" json:"local_user_id,omitempty"` // 本地用户ID
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`                                    // 用户姓名
	Identifier    string                 `protobuf:"bytes,4,opt,name=identifier,proto3" json:"identifier,omitempty"`                        // 用户标识符（邮箱等，可选）
	Phone         string                 `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`                                  // 手机号（可选）
	Openid        string                 `protobuf:"bytes,6,opt,name=openid,proto3" json:"openid,omitempty"`                                // OpenID（可选）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncUserReq) Reset() {
	*x = SyncUserReq{}
	mi := &file_eventsync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncUserReq) ProtoMessage() {}

func (x *SyncUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_eventsync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncUserReq.ProtoReflect.Descriptor instead.
func (*SyncUserReq) Descriptor() ([]byte, []int) {
	return file_eventsync_proto_rawDescGZIP(), []int{0}
}

func (x *SyncUserReq) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *SyncUserReq) GetLocalUserId() string {
	if x != nil {
		return x.LocalUserId
	}
	return ""
}

func (x *SyncUserReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SyncUserReq) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *SyncUserReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *SyncUserReq) GetOpenid() string {
	if x != nil {
		return x.Openid
	}
	return ""
}

type SyncUserResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                                // 是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                                 // 响应消息
	RemoteUserId  string                 `protobuf:"bytes,3,opt,name=remote_user_id,json=remoteUserId,proto3" json:"remote_user_id,omitempty"` // Skylark用户ID
	ErrorCode     string                 `protobuf:"bytes,4,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`            // 错误码（可选）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncUserResp) Reset() {
	*x = SyncUserResp{}
	mi := &file_eventsync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncUserResp) ProtoMessage() {}

func (x *SyncUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_eventsync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncUserResp.ProtoReflect.Descriptor instead.
func (*SyncUserResp) Descriptor() ([]byte, []int) {
	return file_eventsync_proto_rawDescGZIP(), []int{1}
}

func (x *SyncUserResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SyncUserResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SyncUserResp) GetRemoteUserId() string {
	if x != nil {
		return x.RemoteUserId
	}
	return ""
}

func (x *SyncUserResp) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

type SyncOrganizationReq struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TenantId         string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`                             // 租户ID
	LocalOrgId       string                 `protobuf:"bytes,2,opt,name=local_org_id,json=localOrgId,proto3" json:"local_org_id,omitempty"`                     // 本地组织ID
	ParentLocalOrgId string                 `protobuf:"bytes,3,opt,name=parent_local_org_id,json=parentLocalOrgId,proto3" json:"parent_local_org_id,omitempty"` // 父组织本地ID（空字符串表示根组织）
	Name             string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`                                                     // 组织名称
	Description      string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`                                       // 组织描述
	FounderId        string                 `protobuf:"bytes,6,opt,name=founder_id,json=founderId,proto3" json:"founder_id,omitempty"`                          // 创建人本地用户ID
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SyncOrganizationReq) Reset() {
	*x = SyncOrganizationReq{}
	mi := &file_eventsync_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncOrganizationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncOrganizationReq) ProtoMessage() {}

func (x *SyncOrganizationReq) ProtoReflect() protoreflect.Message {
	mi := &file_eventsync_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncOrganizationReq.ProtoReflect.Descriptor instead.
func (*SyncOrganizationReq) Descriptor() ([]byte, []int) {
	return file_eventsync_proto_rawDescGZIP(), []int{2}
}

func (x *SyncOrganizationReq) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *SyncOrganizationReq) GetLocalOrgId() string {
	if x != nil {
		return x.LocalOrgId
	}
	return ""
}

func (x *SyncOrganizationReq) GetParentLocalOrgId() string {
	if x != nil {
		return x.ParentLocalOrgId
	}
	return ""
}

func (x *SyncOrganizationReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SyncOrganizationReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SyncOrganizationReq) GetFounderId() string {
	if x != nil {
		return x.FounderId
	}
	return ""
}

type SyncOrganizationResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RemoteOrgId   string                 `protobuf:"bytes,3,opt,name=remote_org_id,json=remoteOrgId,proto3" json:"remote_org_id,omitempty"` // Skylark组织ID
	ErrorCode     string                 `protobuf:"bytes,4,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncOrganizationResp) Reset() {
	*x = SyncOrganizationResp{}
	mi := &file_eventsync_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncOrganizationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncOrganizationResp) ProtoMessage() {}

func (x *SyncOrganizationResp) ProtoReflect() protoreflect.Message {
	mi := &file_eventsync_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncOrganizationResp.ProtoReflect.Descriptor instead.
func (*SyncOrganizationResp) Descriptor() ([]byte, []int) {
	return file_eventsync_proto_rawDescGZIP(), []int{3}
}

func (x *SyncOrganizationResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SyncOrganizationResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SyncOrganizationResp) GetRemoteOrgId() string {
	if x != nil {
		return x.RemoteOrgId
	}
	return ""
}

func (x *SyncOrganizationResp) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

type DeleteOrganizationReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	LocalOrgId    string                 `protobuf:"bytes,2,opt,name=local_org_id,json=localOrgId,proto3" json:"local_org_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOrganizationReq) Reset() {
	*x = DeleteOrganizationReq{}
	mi := &file_eventsync_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOrganizationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOrganizationReq) ProtoMessage() {}

func (x *DeleteOrganizationReq) ProtoReflect() protoreflect.Message {
	mi := &file_eventsync_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOrganizationReq.ProtoReflect.Descriptor instead.
func (*DeleteOrganizationReq) Descriptor() ([]byte, []int) {
	return file_eventsync_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteOrganizationReq) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *DeleteOrganizationReq) GetLocalOrgId() string {
	if x != nil {
		return x.LocalOrgId
	}
	return ""
}

type DeleteOrganizationResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOrganizationResp) Reset() {
	*x = DeleteOrganizationResp{}
	mi := &file_eventsync_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOrganizationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOrganizationResp) ProtoMessage() {}

func (x *DeleteOrganizationResp) ProtoReflect() protoreflect.Message {
	mi := &file_eventsync_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOrganizationResp.ProtoReflect.Descriptor instead.
func (*DeleteOrganizationResp) Descriptor() ([]byte, []int) {
	return file_eventsync_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteOrganizationResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteOrganizationResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DeleteOrganizationResp) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

type HealthCheckReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckReq) Reset() {
	*x = HealthCheckReq{}
	mi := &file_eventsync_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckReq) ProtoMessage() {}

func (x *HealthCheckReq) ProtoReflect() protoreflect.Message {
	mi := &file_eventsync_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckReq.ProtoReflect.Descriptor instead.
func (*HealthCheckReq) Descriptor() ([]byte, []int) {
	return file_eventsync_proto_rawDescGZIP(), []int{6}
}

type HealthCheckResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResp) Reset() {
	*x = HealthCheckResp{}
	mi := &file_eventsync_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResp) ProtoMessage() {}

func (x *HealthCheckResp) ProtoReflect() protoreflect.Message {
	mi := &file_eventsync_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResp.ProtoReflect.Descriptor instead.
func (*HealthCheckResp) Descriptor() ([]byte, []int) {
	return file_eventsync_proto_rawDescGZIP(), []int{7}
}

func (x *HealthCheckResp) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

type GetUserSyncStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"` // 租户ID
	UserIds       []string               `protobuf:"bytes,2,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`    // 用户ID列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserSyncStatusReq) Reset() {
	*x = GetUserSyncStatusReq{}
	mi := &file_eventsync_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserSyncStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserSyncStatusReq) ProtoMessage() {}

func (x *GetUserSyncStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_eventsync_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserSyncStatusReq.ProtoReflect.Descriptor instead.
func (*GetUserSyncStatusReq) Descriptor() ([]byte, []int) {
	return file_eventsync_proto_rawDescGZIP(), []int{8}
}

func (x *GetUserSyncStatusReq) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetUserSyncStatusReq) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type GetUserSyncStatusResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	SyncStatus    map[string]bool        `protobuf:"bytes,3,rep,name=sync_status,json=syncStatus,proto3" json:"sync_status,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // key: 用户ID, value: 是否已同步
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserSyncStatusResp) Reset() {
	*x = GetUserSyncStatusResp{}
	mi := &file_eventsync_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserSyncStatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserSyncStatusResp) ProtoMessage() {}

func (x *GetUserSyncStatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_eventsync_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserSyncStatusResp.ProtoReflect.Descriptor instead.
func (*GetUserSyncStatusResp) Descriptor() ([]byte, []int) {
	return file_eventsync_proto_rawDescGZIP(), []int{9}
}

func (x *GetUserSyncStatusResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetUserSyncStatusResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetUserSyncStatusResp) GetSyncStatus() map[string]bool {
	if x != nil {
		return x.SyncStatus
	}
	return nil
}

type GetOrgSyncStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"` // 租户ID
	OrgIds        []string               `protobuf:"bytes,2,rep,name=org_ids,json=orgIds,proto3" json:"org_ids,omitempty"`       // 组织ID列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrgSyncStatusReq) Reset() {
	*x = GetOrgSyncStatusReq{}
	mi := &file_eventsync_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrgSyncStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrgSyncStatusReq) ProtoMessage() {}

func (x *GetOrgSyncStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_eventsync_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrgSyncStatusReq.ProtoReflect.Descriptor instead.
func (*GetOrgSyncStatusReq) Descriptor() ([]byte, []int) {
	return file_eventsync_proto_rawDescGZIP(), []int{10}
}

func (x *GetOrgSyncStatusReq) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetOrgSyncStatusReq) GetOrgIds() []string {
	if x != nil {
		return x.OrgIds
	}
	return nil
}

type GetOrgSyncStatusResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	SyncStatus    map[string]bool        `protobuf:"bytes,3,rep,name=sync_status,json=syncStatus,proto3" json:"sync_status,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // key: 组织ID, value: 是否已同步
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrgSyncStatusResp) Reset() {
	*x = GetOrgSyncStatusResp{}
	mi := &file_eventsync_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrgSyncStatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrgSyncStatusResp) ProtoMessage() {}

func (x *GetOrgSyncStatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_eventsync_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrgSyncStatusResp.ProtoReflect.Descriptor instead.
func (*GetOrgSyncStatusResp) Descriptor() ([]byte, []int) {
	return file_eventsync_proto_rawDescGZIP(), []int{11}
}

func (x *GetOrgSyncStatusResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetOrgSyncStatusResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetOrgSyncStatusResp) GetSyncStatus() map[string]bool {
	if x != nil {
		return x.SyncStatus
	}
	return nil
}

type BindOrganizationReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`             // 租户ID
	LocalOrgId    string                 `protobuf:"bytes,2,opt,name=local_org_id,json=localOrgId,proto3" json:"local_org_id,omitempty"`     // 本地组织ID
	RemoteOrgId   int32                  `protobuf:"varint,3,opt,name=remote_org_id,json=remoteOrgId,proto3" json:"remote_org_id,omitempty"` // 远程组织ID（Skylark中已存在的组织ID）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindOrganizationReq) Reset() {
	*x = BindOrganizationReq{}
	mi := &file_eventsync_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindOrganizationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindOrganizationReq) ProtoMessage() {}

func (x *BindOrganizationReq) ProtoReflect() protoreflect.Message {
	mi := &file_eventsync_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindOrganizationReq.ProtoReflect.Descriptor instead.
func (*BindOrganizationReq) Descriptor() ([]byte, []int) {
	return file_eventsync_proto_rawDescGZIP(), []int{12}
}

func (x *BindOrganizationReq) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *BindOrganizationReq) GetLocalOrgId() string {
	if x != nil {
		return x.LocalOrgId
	}
	return ""
}

func (x *BindOrganizationReq) GetRemoteOrgId() int32 {
	if x != nil {
		return x.RemoteOrgId
	}
	return 0
}

type BindOrganizationResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindOrganizationResp) Reset() {
	*x = BindOrganizationResp{}
	mi := &file_eventsync_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindOrganizationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindOrganizationResp) ProtoMessage() {}

func (x *BindOrganizationResp) ProtoReflect() protoreflect.Message {
	mi := &file_eventsync_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindOrganizationResp.ProtoReflect.Descriptor instead.
func (*BindOrganizationResp) Descriptor() ([]byte, []int) {
	return file_eventsync_proto_rawDescGZIP(), []int{13}
}

func (x *BindOrganizationResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BindOrganizationResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BindOrganizationResp) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

type UnbindOrganizationReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`         // 租户ID
	LocalOrgId    string                 `protobuf:"bytes,2,opt,name=local_org_id,json=localOrgId,proto3" json:"local_org_id,omitempty"` // 本地组织ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnbindOrganizationReq) Reset() {
	*x = UnbindOrganizationReq{}
	mi := &file_eventsync_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnbindOrganizationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbindOrganizationReq) ProtoMessage() {}

func (x *UnbindOrganizationReq) ProtoReflect() protoreflect.Message {
	mi := &file_eventsync_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbindOrganizationReq.ProtoReflect.Descriptor instead.
func (*UnbindOrganizationReq) Descriptor() ([]byte, []int) {
	return file_eventsync_proto_rawDescGZIP(), []int{14}
}

func (x *UnbindOrganizationReq) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *UnbindOrganizationReq) GetLocalOrgId() string {
	if x != nil {
		return x.LocalOrgId
	}
	return ""
}

type UnbindOrganizationResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnbindOrganizationResp) Reset() {
	*x = UnbindOrganizationResp{}
	mi := &file_eventsync_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnbindOrganizationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbindOrganizationResp) ProtoMessage() {}

func (x *UnbindOrganizationResp) ProtoReflect() protoreflect.Message {
	mi := &file_eventsync_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbindOrganizationResp.ProtoReflect.Descriptor instead.
func (*UnbindOrganizationResp) Descriptor() ([]byte, []int) {
	return file_eventsync_proto_rawDescGZIP(), []int{15}
}

func (x *UnbindOrganizationResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UnbindOrganizationResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UnbindOrganizationResp) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

type BindUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`                // 租户ID
	LocalUserId   string                 `protobuf:"bytes,2,opt,name=local_user_id,json=localUserId,proto3" json:"local_user_id,omitempty"`     // 本地用户ID
	RemoteUserId  int32                  `protobuf:"varint,3,opt,name=remote_user_id,json=remoteUserId,proto3" json:"remote_user_id,omitempty"` // 远程用户ID（Skylark中已存在的用户ID）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindUserReq) Reset() {
	*x = BindUserReq{}
	mi := &file_eventsync_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindUserReq) ProtoMessage() {}

func (x *BindUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_eventsync_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindUserReq.ProtoReflect.Descriptor instead.
func (*BindUserReq) Descriptor() ([]byte, []int) {
	return file_eventsync_proto_rawDescGZIP(), []int{16}
}

func (x *BindUserReq) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *BindUserReq) GetLocalUserId() string {
	if x != nil {
		return x.LocalUserId
	}
	return ""
}

func (x *BindUserReq) GetRemoteUserId() int32 {
	if x != nil {
		return x.RemoteUserId
	}
	return 0
}

type BindUserResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindUserResp) Reset() {
	*x = BindUserResp{}
	mi := &file_eventsync_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindUserResp) ProtoMessage() {}

func (x *BindUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_eventsync_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindUserResp.ProtoReflect.Descriptor instead.
func (*BindUserResp) Descriptor() ([]byte, []int) {
	return file_eventsync_proto_rawDescGZIP(), []int{17}
}

func (x *BindUserResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BindUserResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BindUserResp) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

type UnbindUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`            // 租户ID
	LocalUserId   string                 `protobuf:"bytes,2,opt,name=local_user_id,json=localUserId,proto3" json:"local_user_id,omitempty"` // 本地用户ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnbindUserReq) Reset() {
	*x = UnbindUserReq{}
	mi := &file_eventsync_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnbindUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbindUserReq) ProtoMessage() {}

func (x *UnbindUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_eventsync_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbindUserReq.ProtoReflect.Descriptor instead.
func (*UnbindUserReq) Descriptor() ([]byte, []int) {
	return file_eventsync_proto_rawDescGZIP(), []int{18}
}

func (x *UnbindUserReq) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *UnbindUserReq) GetLocalUserId() string {
	if x != nil {
		return x.LocalUserId
	}
	return ""
}

type UnbindUserResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnbindUserResp) Reset() {
	*x = UnbindUserResp{}
	mi := &file_eventsync_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnbindUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbindUserResp) ProtoMessage() {}

func (x *UnbindUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_eventsync_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbindUserResp.ProtoReflect.Descriptor instead.
func (*UnbindUserResp) Descriptor() ([]byte, []int) {
	return file_eventsync_proto_rawDescGZIP(), []int{19}
}

func (x *UnbindUserResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UnbindUserResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UnbindUserResp) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

type UpdateOrganizationReq struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TenantId          string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`                             // 租户ID
	LocalOrgId        string                 `protobuf:"bytes,2,opt,name=local_org_id,json=localOrgId,proto3" json:"local_org_id,omitempty"`                     // 本地组织ID
	Name              string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`                                                     // 组织名称（可选）
	Description       string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`                                       // 组织描述（可选）
	ManagerId         string                 `protobuf:"bytes,5,opt,name=manager_id,json=managerId,proto3" json:"manager_id,omitempty"`                          // 管理员本地用户ID（可选）
	UpdateName        bool                   `protobuf:"varint,6,opt,name=update_name,json=updateName,proto3" json:"update_name,omitempty"`                      // 是否更新名称
	UpdateDescription bool                   `protobuf:"varint,7,opt,name=update_description,json=updateDescription,proto3" json:"update_description,omitempty"` // 是否更新描述
	UpdateManager     bool                   `protobuf:"varint,8,opt,name=update_manager,json=updateManager,proto3" json:"update_manager,omitempty"`             // 是否更新管理员
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpdateOrganizationReq) Reset() {
	*x = UpdateOrganizationReq{}
	mi := &file_eventsync_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrganizationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrganizationReq) ProtoMessage() {}

func (x *UpdateOrganizationReq) ProtoReflect() protoreflect.Message {
	mi := &file_eventsync_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrganizationReq.ProtoReflect.Descriptor instead.
func (*UpdateOrganizationReq) Descriptor() ([]byte, []int) {
	return file_eventsync_proto_rawDescGZIP(), []int{20}
}

func (x *UpdateOrganizationReq) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *UpdateOrganizationReq) GetLocalOrgId() string {
	if x != nil {
		return x.LocalOrgId
	}
	return ""
}

func (x *UpdateOrganizationReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateOrganizationReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateOrganizationReq) GetManagerId() string {
	if x != nil {
		return x.ManagerId
	}
	return ""
}

func (x *UpdateOrganizationReq) GetUpdateName() bool {
	if x != nil {
		return x.UpdateName
	}
	return false
}

func (x *UpdateOrganizationReq) GetUpdateDescription() bool {
	if x != nil {
		return x.UpdateDescription
	}
	return false
}

func (x *UpdateOrganizationReq) GetUpdateManager() bool {
	if x != nil {
		return x.UpdateManager
	}
	return false
}

type UpdateOrganizationResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrganizationResp) Reset() {
	*x = UpdateOrganizationResp{}
	mi := &file_eventsync_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrganizationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrganizationResp) ProtoMessage() {}

func (x *UpdateOrganizationResp) ProtoReflect() protoreflect.Message {
	mi := &file_eventsync_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrganizationResp.ProtoReflect.Descriptor instead.
func (*UpdateOrganizationResp) Descriptor() ([]byte, []int) {
	return file_eventsync_proto_rawDescGZIP(), []int{21}
}

func (x *UpdateOrganizationResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateOrganizationResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateOrganizationResp) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

type AddMemberReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`                  // 租户ID
	LocalOrgId    string                 `protobuf:"bytes,2,opt,name=local_org_id,json=localOrgId,proto3" json:"local_org_id,omitempty"`          // 本地组织ID
	LocalMemberId string                 `protobuf:"bytes,3,opt,name=local_member_id,json=localMemberId,proto3" json:"local_member_id,omitempty"` // 成员本地用户ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMemberReq) Reset() {
	*x = AddMemberReq{}
	mi := &file_eventsync_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMemberReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMemberReq) ProtoMessage() {}

func (x *AddMemberReq) ProtoReflect() protoreflect.Message {
	mi := &file_eventsync_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMemberReq.ProtoReflect.Descriptor instead.
func (*AddMemberReq) Descriptor() ([]byte, []int) {
	return file_eventsync_proto_rawDescGZIP(), []int{22}
}

func (x *AddMemberReq) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *AddMemberReq) GetLocalOrgId() string {
	if x != nil {
		return x.LocalOrgId
	}
	return ""
}

func (x *AddMemberReq) GetLocalMemberId() string {
	if x != nil {
		return x.LocalMemberId
	}
	return ""
}

type AddMemberResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMemberResp) Reset() {
	*x = AddMemberResp{}
	mi := &file_eventsync_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMemberResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMemberResp) ProtoMessage() {}

func (x *AddMemberResp) ProtoReflect() protoreflect.Message {
	mi := &file_eventsync_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMemberResp.ProtoReflect.Descriptor instead.
func (*AddMemberResp) Descriptor() ([]byte, []int) {
	return file_eventsync_proto_rawDescGZIP(), []int{23}
}

func (x *AddMemberResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddMemberResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AddMemberResp) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

type RemoveMemberReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`                  // 租户ID
	LocalOrgId    string                 `protobuf:"bytes,2,opt,name=local_org_id,json=localOrgId,proto3" json:"local_org_id,omitempty"`          // 本地组织ID
	LocalMemberId string                 `protobuf:"bytes,3,opt,name=local_member_id,json=localMemberId,proto3" json:"local_member_id,omitempty"` // 成员本地用户ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveMemberReq) Reset() {
	*x = RemoveMemberReq{}
	mi := &file_eventsync_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveMemberReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMemberReq) ProtoMessage() {}

func (x *RemoveMemberReq) ProtoReflect() protoreflect.Message {
	mi := &file_eventsync_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMemberReq.ProtoReflect.Descriptor instead.
func (*RemoveMemberReq) Descriptor() ([]byte, []int) {
	return file_eventsync_proto_rawDescGZIP(), []int{24}
}

func (x *RemoveMemberReq) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RemoveMemberReq) GetLocalOrgId() string {
	if x != nil {
		return x.LocalOrgId
	}
	return ""
}

func (x *RemoveMemberReq) GetLocalMemberId() string {
	if x != nil {
		return x.LocalMemberId
	}
	return ""
}

type RemoveMemberResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveMemberResp) Reset() {
	*x = RemoveMemberResp{}
	mi := &file_eventsync_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveMemberResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMemberResp) ProtoMessage() {}

func (x *RemoveMemberResp) ProtoReflect() protoreflect.Message {
	mi := &file_eventsync_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMemberResp.ProtoReflect.Descriptor instead.
func (*RemoveMemberResp) Descriptor() ([]byte, []int) {
	return file_eventsync_proto_rawDescGZIP(), []int{25}
}

func (x *RemoveMemberResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RemoveMemberResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RemoveMemberResp) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

var File_eventsync_proto protoreflect.FileDescriptor

const file_eventsync_proto_rawDesc = "" +
	"\n" +
	"\x0feventsync.proto\x12\teventsync\"\xb0\x01\n" +
	"\vSyncUserReq\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\"\n" +
	"\rlocal_user_id\x18\x02 \x01(\tR\vlocalUserId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"identifier\x18\x04 \x01(\tR\n" +
	"identifier\x12\x14\n" +
	"\x05phone\x18\x05 \x01(\tR\x05phone\x12\x16\n" +
	"\x06openid\x18\x06 \x01(\tR\x06openid\"\x87\x01\n" +
	"\fSyncUserResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12$\n" +
	"\x0eremote_user_id\x18\x03 \x01(\tR\fremoteUserId\x12\x1d\n" +
	"\n" +
	"error_code\x18\x04 \x01(\tR\terrorCode\"\xd8\x01\n" +
	"\x13SyncOrganizationReq\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12 \n" +
	"\flocal_org_id\x18\x02 \x01(\tR\n" +
	"localOrgId\x12-\n" +
	"\x13parent_local_org_id\x18\x03 \x01(\tR\x10parentLocalOrgId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"founder_id\x18\x06 \x01(\tR\tfounderId\"\x8d\x01\n" +
	"\x14SyncOrganizationResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\"\n" +
	"\rremote_org_id\x18\x03 \x01(\tR\vremoteOrgId\x12\x1d\n" +
	"\n" +
	"error_code\x18\x04 \x01(\tR\terrorCode\"V\n" +
	"\x15DeleteOrganizationReq\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12 \n" +
	"\flocal_org_id\x18\x02 \x01(\tR\n" +
	"localOrgId\"k\n" +
	"\x16DeleteOrganizationResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"error_code\x18\x03 \x01(\tR\terrorCode\"\x10\n" +
	"\x0eHealthCheckReq\"+\n" +
	"\x0fHealthCheckResp\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\"N\n" +
	"\x14GetUserSyncStatusReq\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x19\n" +
	"\buser_ids\x18\x02 \x03(\tR\auserIds\"\xdd\x01\n" +
	"\x15GetUserSyncStatusResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12Q\n" +
	"\vsync_status\x18\x03 \x03(\v20.eventsync.GetUserSyncStatusResp.SyncStatusEntryR\n" +
	"syncStatus\x1a=\n" +
	"\x0fSyncStatusEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\"K\n" +
	"\x13GetOrgSyncStatusReq\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x17\n" +
	"\aorg_ids\x18\x02 \x03(\tR\x06orgIds\"\xdb\x01\n" +
	"\x14GetOrgSyncStatusResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12P\n" +
	"\vsync_status\x18\x03 \x03(\v2/.eventsync.GetOrgSyncStatusResp.SyncStatusEntryR\n" +
	"syncStatus\x1a=\n" +
	"\x0fSyncStatusEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\"x\n" +
	"\x13BindOrganizationReq\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12 \n" +
	"\flocal_org_id\x18\x02 \x01(\tR\n" +
	"localOrgId\x12\"\n" +
	"\rremote_org_id\x18\x03 \x01(\x05R\vremoteOrgId\"i\n" +
	"\x14BindOrganizationResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"error_code\x18\x03 \x01(\tR\terrorCode\"V\n" +
	"\x15UnbindOrganizationReq\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12 \n" +
	"\flocal_org_id\x18\x02 \x01(\tR\n" +
	"localOrgId\"k\n" +
	"\x16UnbindOrganizationResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"error_code\x18\x03 \x01(\tR\terrorCode\"t\n" +
	"\vBindUserReq\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\"\n" +
	"\rlocal_user_id\x18\x02 \x01(\tR\vlocalUserId\x12$\n" +
	"\x0eremote_user_id\x18\x03 \x01(\x05R\fremoteUserId\"a\n" +
	"\fBindUserResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"error_code\x18\x03 \x01(\tR\terrorCode\"P\n" +
	"\rUnbindUserReq\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\"\n" +
	"\rlocal_user_id\x18\x02 \x01(\tR\vlocalUserId\"c\n" +
	"\x0eUnbindUserResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"error_code\x18\x03 \x01(\tR\terrorCode\"\xa2\x02\n" +
	"\x15UpdateOrganizationReq\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12 \n" +
	"\flocal_org_id\x18\x02 \x01(\tR\n" +
	"localOrgId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"manager_id\x18\x05 \x01(\tR\tmanagerId\x12\x1f\n" +
	"\vupdate_name\x18\x06 \x01(\bR\n" +
	"updateName\x12-\n" +
	"\x12update_description\x18\a \x01(\bR\x11updateDescription\x12%\n" +
	"\x0eupdate_manager\x18\b \x01(\bR\rupdateManager\"k\n" +
	"\x16UpdateOrganizationResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"error_code\x18\x03 \x01(\tR\terrorCode\"u\n" +
	"\fAddMemberReq\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12 \n" +
	"\flocal_org_id\x18\x02 \x01(\tR\n" +
	"localOrgId\x12&\n" +
	"\x0flocal_member_id\x18\x03 \x01(\tR\rlocalMemberId\"b\n" +
	"\rAddMemberResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"error_code\x18\x03 \x01(\tR\terrorCode\"x\n" +
	"\x0fRemoveMemberReq\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12 \n" +
	"\flocal_org_id\x18\x02 \x01(\tR\n" +
	"localOrgId\x12&\n" +
	"\x0flocal_member_id\x18\x03 \x01(\tR\rlocalMemberId\"e\n" +
	"\x10RemoveMemberResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"error_code\x18\x03 \x01(\tR\terrorCode2\xff\a\n" +
	"\tAdminSync\x12;\n" +
	"\bSyncUser\x12\x16.eventsync.SyncUserReq\x1a\x17.eventsync.SyncUserResp\x12S\n" +
	"\x10SyncOrganization\x12\x1e.eventsync.SyncOrganizationReq\x1a\x1f.eventsync.SyncOrganizationResp\x12Y\n" +
	"\x12DeleteOrganization\x12 .eventsync.DeleteOrganizationReq\x1a!.eventsync.DeleteOrganizationResp\x12D\n" +
	"\vHealthCheck\x12\x19.eventsync.HealthCheckReq\x1a\x1a.eventsync.HealthCheckResp\x12V\n" +
	"\x11GetUserSyncStatus\x12\x1f.eventsync.GetUserSyncStatusReq\x1a .eventsync.GetUserSyncStatusResp\x12S\n" +
	"\x10GetOrgSyncStatus\x12\x1e.eventsync.GetOrgSyncStatusReq\x1a\x1f.eventsync.GetOrgSyncStatusResp\x12S\n" +
	"\x10BindOrganization\x12\x1e.eventsync.BindOrganizationReq\x1a\x1f.eventsync.BindOrganizationResp\x12Y\n" +
	"\x12UnbindOrganization\x12 .eventsync.UnbindOrganizationReq\x1a!.eventsync.UnbindOrganizationResp\x12;\n" +
	"\bBindUser\x12\x16.eventsync.BindUserReq\x1a\x17.eventsync.BindUserResp\x12A\n" +
	"\n" +
	"UnbindUser\x12\x18.eventsync.UnbindUserReq\x1a\x19.eventsync.UnbindUserResp\x12Y\n" +
	"\x12UpdateOrganization\x12 .eventsync.UpdateOrganizationReq\x1a!.eventsync.UpdateOrganizationResp\x12>\n" +
	"\tAddMember\x12\x17.eventsync.AddMemberReq\x1a\x18.eventsync.AddMemberResp\x12G\n" +
	"\fRemoveMember\x12\x1a.eventsync.RemoveMemberReq\x1a\x1b.eventsync.RemoveMemberRespB\x1dZ\x1bnexlyn/service/eventsync/pbb\x06proto3"

var (
	file_eventsync_proto_rawDescOnce sync.Once
	file_eventsync_proto_rawDescData []byte
)

func file_eventsync_proto_rawDescGZIP() []byte {
	file_eventsync_proto_rawDescOnce.Do(func() {
		file_eventsync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_eventsync_proto_rawDesc), len(file_eventsync_proto_rawDesc)))
	})
	return file_eventsync_proto_rawDescData
}

var file_eventsync_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_eventsync_proto_goTypes = []any{
	(*SyncUserReq)(nil),            // 0: eventsync.SyncUserReq
	(*SyncUserResp)(nil),           // 1: eventsync.SyncUserResp
	(*SyncOrganizationReq)(nil),    // 2: eventsync.SyncOrganizationReq
	(*SyncOrganizationResp)(nil),   // 3: eventsync.SyncOrganizationResp
	(*DeleteOrganizationReq)(nil),  // 4: eventsync.DeleteOrganizationReq
	(*DeleteOrganizationResp)(nil), // 5: eventsync.DeleteOrganizationResp
	(*HealthCheckReq)(nil),         // 6: eventsync.HealthCheckReq
	(*HealthCheckResp)(nil),        // 7: eventsync.HealthCheckResp
	(*GetUserSyncStatusReq)(nil),   // 8: eventsync.GetUserSyncStatusReq
	(*GetUserSyncStatusResp)(nil),  // 9: eventsync.GetUserSyncStatusResp
	(*GetOrgSyncStatusReq)(nil),    // 10: eventsync.GetOrgSyncStatusReq
	(*GetOrgSyncStatusResp)(nil),   // 11: eventsync.GetOrgSyncStatusResp
	(*BindOrganizationReq)(nil),    // 12: eventsync.BindOrganizationReq
	(*BindOrganizationResp)(nil),   // 13: eventsync.BindOrganizationResp
	(*UnbindOrganizationReq)(nil),  // 14: eventsync.UnbindOrganizationReq
	(*UnbindOrganizationResp)(nil), // 15: eventsync.UnbindOrganizationResp
	(*BindUserReq)(nil),            // 16: eventsync.BindUserReq
	(*BindUserResp)(nil),           // 17: eventsync.BindUserResp
	(*UnbindUserReq)(nil),          // 18: eventsync.UnbindUserReq
	(*UnbindUserResp)(nil),         // 19: eventsync.UnbindUserResp
	(*UpdateOrganizationReq)(nil),  // 20: eventsync.UpdateOrganizationReq
	(*UpdateOrganizationResp)(nil), // 21: eventsync.UpdateOrganizationResp
	(*AddMemberReq)(nil),           // 22: eventsync.AddMemberReq
	(*AddMemberResp)(nil),          // 23: eventsync.AddMemberResp
	(*RemoveMemberReq)(nil),        // 24: eventsync.RemoveMemberReq
	(*RemoveMemberResp)(nil),       // 25: eventsync.RemoveMemberResp
	nil,                            // 26: eventsync.GetUserSyncStatusResp.SyncStatusEntry
	nil,                            // 27: eventsync.GetOrgSyncStatusResp.SyncStatusEntry
}
var file_eventsync_proto_depIdxs = []int32{
	26, // 0: eventsync.GetUserSyncStatusResp.sync_status:type_name -> eventsync.GetUserSyncStatusResp.SyncStatusEntry
	27, // 1: eventsync.GetOrgSyncStatusResp.sync_status:type_name -> eventsync.GetOrgSyncStatusResp.SyncStatusEntry
	0,  // 2: eventsync.AdminSync.SyncUser:input_type -> eventsync.SyncUserReq
	2,  // 3: eventsync.AdminSync.SyncOrganization:input_type -> eventsync.SyncOrganizationReq
	4,  // 4: eventsync.AdminSync.DeleteOrganization:input_type -> eventsync.DeleteOrganizationReq
	6,  // 5: eventsync.AdminSync.HealthCheck:input_type -> eventsync.HealthCheckReq
	8,  // 6: eventsync.AdminSync.GetUserSyncStatus:input_type -> eventsync.GetUserSyncStatusReq
	10, // 7: eventsync.AdminSync.GetOrgSyncStatus:input_type -> eventsync.GetOrgSyncStatusReq
	12, // 8: eventsync.AdminSync.BindOrganization:input_type -> eventsync.BindOrganizationReq
	14, // 9: eventsync.AdminSync.UnbindOrganization:input_type -> eventsync.UnbindOrganizationReq
	16, // 10: eventsync.AdminSync.BindUser:input_type -> eventsync.BindUserReq
	18, // 11: eventsync.AdminSync.UnbindUser:input_type -> eventsync.UnbindUserReq
	20, // 12: eventsync.AdminSync.UpdateOrganization:input_type -> eventsync.UpdateOrganizationReq
	22, // 13: eventsync.AdminSync.AddMember:input_type -> eventsync.AddMemberReq
	24, // 14: eventsync.AdminSync.RemoveMember:input_type -> eventsync.RemoveMemberReq
	1,  // 15: eventsync.AdminSync.SyncUser:output_type -> eventsync.SyncUserResp
	3,  // 16: eventsync.AdminSync.SyncOrganization:output_type -> eventsync.SyncOrganizationResp
	5,  // 17: eventsync.AdminSync.DeleteOrganization:output_type -> eventsync.DeleteOrganizationResp
	7,  // 18: eventsync.AdminSync.HealthCheck:output_type -> eventsync.HealthCheckResp
	9,  // 19: eventsync.AdminSync.GetUserSyncStatus:output_type -> eventsync.GetUserSyncStatusResp
	11, // 20: eventsync.AdminSync.GetOrgSyncStatus:output_type -> eventsync.GetOrgSyncStatusResp
	13, // 21: eventsync.AdminSync.BindOrganization:output_type -> eventsync.BindOrganizationResp
	15, // 22: eventsync.AdminSync.UnbindOrganization:output_type -> eventsync.UnbindOrganizationResp
	17, // 23: eventsync.AdminSync.BindUser:output_type -> eventsync.BindUserResp
	19, // 24: eventsync.AdminSync.UnbindUser:output_type -> eventsync.UnbindUserResp
	21, // 25: eventsync.AdminSync.UpdateOrganization:output_type -> eventsync.UpdateOrganizationResp
	23, // 26: eventsync.AdminSync.AddMember:output_type -> eventsync.AddMemberResp
	25, // 27: eventsync.AdminSync.RemoveMember:output_type -> eventsync.RemoveMemberResp
	15, // [15:28] is the sub-list for method output_type
	2,  // [2:15] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_eventsync_proto_init() }
func file_eventsync_proto_init() {
	if File_eventsync_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_eventsync_proto_rawDesc), len(file_eventsync_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_eventsync_proto_goTypes,
		DependencyIndexes: file_eventsync_proto_depIdxs,
		MessageInfos:      file_eventsync_proto_msgTypes,
	}.Build()
	File_eventsync_proto = out.File
	file_eventsync_proto_goTypes = nil
	file_eventsync_proto_depIdxs = nil
}
