// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.4
// source: eventsync.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdminSync_SyncUser_FullMethodName           = "/eventsync.AdminSync/SyncUser"
	AdminSync_SyncOrganization_FullMethodName   = "/eventsync.AdminSync/SyncOrganization"
	AdminSync_DeleteOrganization_FullMethodName = "/eventsync.AdminSync/DeleteOrganization"
	AdminSync_HealthCheck_FullMethodName        = "/eventsync.AdminSync/HealthCheck"
	AdminSync_GetUserSyncStatus_FullMethodName  = "/eventsync.AdminSync/GetUserSyncStatus"
	AdminSync_GetOrgSyncStatus_FullMethodName   = "/eventsync.AdminSync/GetOrgSyncStatus"
	AdminSync_BindOrganization_FullMethodName   = "/eventsync.AdminSync/BindOrganization"
	AdminSync_UnbindOrganization_FullMethodName = "/eventsync.AdminSync/UnbindOrganization"
	AdminSync_BindUser_FullMethodName           = "/eventsync.AdminSync/BindUser"
	AdminSync_UnbindUser_FullMethodName         = "/eventsync.AdminSync/UnbindUser"
	AdminSync_UpdateOrganization_FullMethodName = "/eventsync.AdminSync/UpdateOrganization"
	AdminSync_AddMember_FullMethodName          = "/eventsync.AdminSync/AddMember"
	AdminSync_RemoveMember_FullMethodName       = "/eventsync.AdminSync/RemoveMember"
)

// AdminSyncClient is the client API for AdminSync service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AdminSync gRPC服务
// 负责将本地用户和组织同步到Skylark平台
type AdminSyncClient interface {
	// 同步单个用户到Skylark
	SyncUser(ctx context.Context, in *SyncUserReq, opts ...grpc.CallOption) (*SyncUserResp, error)
	// 同步单个组织到Skylark（自动判断根组织或子组织）
	SyncOrganization(ctx context.Context, in *SyncOrganizationReq, opts ...grpc.CallOption) (*SyncOrganizationResp, error)
	// 删除组织同步
	DeleteOrganization(ctx context.Context, in *DeleteOrganizationReq, opts ...grpc.CallOption) (*DeleteOrganizationResp, error)
	// 健康检查
	HealthCheck(ctx context.Context, in *HealthCheckReq, opts ...grpc.CallOption) (*HealthCheckResp, error)
	// 查询用户同步状态
	GetUserSyncStatus(ctx context.Context, in *GetUserSyncStatusReq, opts ...grpc.CallOption) (*GetUserSyncStatusResp, error)
	// 查询组织同步状态
	GetOrgSyncStatus(ctx context.Context, in *GetOrgSyncStatusReq, opts ...grpc.CallOption) (*GetOrgSyncStatusResp, error)
	// 绑定已存在的远程组织
	BindOrganization(ctx context.Context, in *BindOrganizationReq, opts ...grpc.CallOption) (*BindOrganizationResp, error)
	// 解绑组织映射
	UnbindOrganization(ctx context.Context, in *UnbindOrganizationReq, opts ...grpc.CallOption) (*UnbindOrganizationResp, error)
	// 绑定已存在的远程用户
	BindUser(ctx context.Context, in *BindUserReq, opts ...grpc.CallOption) (*BindUserResp, error)
	// 解绑用户映射
	UnbindUser(ctx context.Context, in *UnbindUserReq, opts ...grpc.CallOption) (*UnbindUserResp, error)
	// 更新组织信息（支持设置管理员）
	UpdateOrganization(ctx context.Context, in *UpdateOrganizationReq, opts ...grpc.CallOption) (*UpdateOrganizationResp, error)
	// 添加成员到组织
	AddMember(ctx context.Context, in *AddMemberReq, opts ...grpc.CallOption) (*AddMemberResp, error)
	// 从组织移除成员
	RemoveMember(ctx context.Context, in *RemoveMemberReq, opts ...grpc.CallOption) (*RemoveMemberResp, error)
}

type adminSyncClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminSyncClient(cc grpc.ClientConnInterface) AdminSyncClient {
	return &adminSyncClient{cc}
}

func (c *adminSyncClient) SyncUser(ctx context.Context, in *SyncUserReq, opts ...grpc.CallOption) (*SyncUserResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncUserResp)
	err := c.cc.Invoke(ctx, AdminSync_SyncUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminSyncClient) SyncOrganization(ctx context.Context, in *SyncOrganizationReq, opts ...grpc.CallOption) (*SyncOrganizationResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncOrganizationResp)
	err := c.cc.Invoke(ctx, AdminSync_SyncOrganization_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminSyncClient) DeleteOrganization(ctx context.Context, in *DeleteOrganizationReq, opts ...grpc.CallOption) (*DeleteOrganizationResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteOrganizationResp)
	err := c.cc.Invoke(ctx, AdminSync_DeleteOrganization_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminSyncClient) HealthCheck(ctx context.Context, in *HealthCheckReq, opts ...grpc.CallOption) (*HealthCheckResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResp)
	err := c.cc.Invoke(ctx, AdminSync_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminSyncClient) GetUserSyncStatus(ctx context.Context, in *GetUserSyncStatusReq, opts ...grpc.CallOption) (*GetUserSyncStatusResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserSyncStatusResp)
	err := c.cc.Invoke(ctx, AdminSync_GetUserSyncStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminSyncClient) GetOrgSyncStatus(ctx context.Context, in *GetOrgSyncStatusReq, opts ...grpc.CallOption) (*GetOrgSyncStatusResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOrgSyncStatusResp)
	err := c.cc.Invoke(ctx, AdminSync_GetOrgSyncStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminSyncClient) BindOrganization(ctx context.Context, in *BindOrganizationReq, opts ...grpc.CallOption) (*BindOrganizationResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BindOrganizationResp)
	err := c.cc.Invoke(ctx, AdminSync_BindOrganization_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminSyncClient) UnbindOrganization(ctx context.Context, in *UnbindOrganizationReq, opts ...grpc.CallOption) (*UnbindOrganizationResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnbindOrganizationResp)
	err := c.cc.Invoke(ctx, AdminSync_UnbindOrganization_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminSyncClient) BindUser(ctx context.Context, in *BindUserReq, opts ...grpc.CallOption) (*BindUserResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BindUserResp)
	err := c.cc.Invoke(ctx, AdminSync_BindUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminSyncClient) UnbindUser(ctx context.Context, in *UnbindUserReq, opts ...grpc.CallOption) (*UnbindUserResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnbindUserResp)
	err := c.cc.Invoke(ctx, AdminSync_UnbindUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminSyncClient) UpdateOrganization(ctx context.Context, in *UpdateOrganizationReq, opts ...grpc.CallOption) (*UpdateOrganizationResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateOrganizationResp)
	err := c.cc.Invoke(ctx, AdminSync_UpdateOrganization_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminSyncClient) AddMember(ctx context.Context, in *AddMemberReq, opts ...grpc.CallOption) (*AddMemberResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddMemberResp)
	err := c.cc.Invoke(ctx, AdminSync_AddMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminSyncClient) RemoveMember(ctx context.Context, in *RemoveMemberReq, opts ...grpc.CallOption) (*RemoveMemberResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveMemberResp)
	err := c.cc.Invoke(ctx, AdminSync_RemoveMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminSyncServer is the server API for AdminSync service.
// All implementations must embed UnimplementedAdminSyncServer
// for forward compatibility.
//
// AdminSync gRPC服务
// 负责将本地用户和组织同步到Skylark平台
type AdminSyncServer interface {
	// 同步单个用户到Skylark
	SyncUser(context.Context, *SyncUserReq) (*SyncUserResp, error)
	// 同步单个组织到Skylark（自动判断根组织或子组织）
	SyncOrganization(context.Context, *SyncOrganizationReq) (*SyncOrganizationResp, error)
	// 删除组织同步
	DeleteOrganization(context.Context, *DeleteOrganizationReq) (*DeleteOrganizationResp, error)
	// 健康检查
	HealthCheck(context.Context, *HealthCheckReq) (*HealthCheckResp, error)
	// 查询用户同步状态
	GetUserSyncStatus(context.Context, *GetUserSyncStatusReq) (*GetUserSyncStatusResp, error)
	// 查询组织同步状态
	GetOrgSyncStatus(context.Context, *GetOrgSyncStatusReq) (*GetOrgSyncStatusResp, error)
	// 绑定已存在的远程组织
	BindOrganization(context.Context, *BindOrganizationReq) (*BindOrganizationResp, error)
	// 解绑组织映射
	UnbindOrganization(context.Context, *UnbindOrganizationReq) (*UnbindOrganizationResp, error)
	// 绑定已存在的远程用户
	BindUser(context.Context, *BindUserReq) (*BindUserResp, error)
	// 解绑用户映射
	UnbindUser(context.Context, *UnbindUserReq) (*UnbindUserResp, error)
	// 更新组织信息（支持设置管理员）
	UpdateOrganization(context.Context, *UpdateOrganizationReq) (*UpdateOrganizationResp, error)
	// 添加成员到组织
	AddMember(context.Context, *AddMemberReq) (*AddMemberResp, error)
	// 从组织移除成员
	RemoveMember(context.Context, *RemoveMemberReq) (*RemoveMemberResp, error)
	mustEmbedUnimplementedAdminSyncServer()
}

// UnimplementedAdminSyncServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminSyncServer struct{}

func (UnimplementedAdminSyncServer) SyncUser(context.Context, *SyncUserReq) (*SyncUserResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncUser not implemented")
}
func (UnimplementedAdminSyncServer) SyncOrganization(context.Context, *SyncOrganizationReq) (*SyncOrganizationResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncOrganization not implemented")
}
func (UnimplementedAdminSyncServer) DeleteOrganization(context.Context, *DeleteOrganizationReq) (*DeleteOrganizationResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteOrganization not implemented")
}
func (UnimplementedAdminSyncServer) HealthCheck(context.Context, *HealthCheckReq) (*HealthCheckResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedAdminSyncServer) GetUserSyncStatus(context.Context, *GetUserSyncStatusReq) (*GetUserSyncStatusResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserSyncStatus not implemented")
}
func (UnimplementedAdminSyncServer) GetOrgSyncStatus(context.Context, *GetOrgSyncStatusReq) (*GetOrgSyncStatusResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrgSyncStatus not implemented")
}
func (UnimplementedAdminSyncServer) BindOrganization(context.Context, *BindOrganizationReq) (*BindOrganizationResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BindOrganization not implemented")
}
func (UnimplementedAdminSyncServer) UnbindOrganization(context.Context, *UnbindOrganizationReq) (*UnbindOrganizationResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnbindOrganization not implemented")
}
func (UnimplementedAdminSyncServer) BindUser(context.Context, *BindUserReq) (*BindUserResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BindUser not implemented")
}
func (UnimplementedAdminSyncServer) UnbindUser(context.Context, *UnbindUserReq) (*UnbindUserResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnbindUser not implemented")
}
func (UnimplementedAdminSyncServer) UpdateOrganization(context.Context, *UpdateOrganizationReq) (*UpdateOrganizationResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateOrganization not implemented")
}
func (UnimplementedAdminSyncServer) AddMember(context.Context, *AddMemberReq) (*AddMemberResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddMember not implemented")
}
func (UnimplementedAdminSyncServer) RemoveMember(context.Context, *RemoveMemberReq) (*RemoveMemberResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveMember not implemented")
}
func (UnimplementedAdminSyncServer) mustEmbedUnimplementedAdminSyncServer() {}
func (UnimplementedAdminSyncServer) testEmbeddedByValue()                   {}

// UnsafeAdminSyncServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminSyncServer will
// result in compilation errors.
type UnsafeAdminSyncServer interface {
	mustEmbedUnimplementedAdminSyncServer()
}

func RegisterAdminSyncServer(s grpc.ServiceRegistrar, srv AdminSyncServer) {
	// If the following call pancis, it indicates UnimplementedAdminSyncServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminSync_ServiceDesc, srv)
}

func _AdminSync_SyncUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminSyncServer).SyncUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminSync_SyncUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminSyncServer).SyncUser(ctx, req.(*SyncUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminSync_SyncOrganization_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncOrganizationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminSyncServer).SyncOrganization(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminSync_SyncOrganization_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminSyncServer).SyncOrganization(ctx, req.(*SyncOrganizationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminSync_DeleteOrganization_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteOrganizationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminSyncServer).DeleteOrganization(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminSync_DeleteOrganization_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminSyncServer).DeleteOrganization(ctx, req.(*DeleteOrganizationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminSync_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminSyncServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminSync_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminSyncServer).HealthCheck(ctx, req.(*HealthCheckReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminSync_GetUserSyncStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserSyncStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminSyncServer).GetUserSyncStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminSync_GetUserSyncStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminSyncServer).GetUserSyncStatus(ctx, req.(*GetUserSyncStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminSync_GetOrgSyncStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrgSyncStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminSyncServer).GetOrgSyncStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminSync_GetOrgSyncStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminSyncServer).GetOrgSyncStatus(ctx, req.(*GetOrgSyncStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminSync_BindOrganization_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BindOrganizationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminSyncServer).BindOrganization(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminSync_BindOrganization_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminSyncServer).BindOrganization(ctx, req.(*BindOrganizationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminSync_UnbindOrganization_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnbindOrganizationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminSyncServer).UnbindOrganization(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminSync_UnbindOrganization_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminSyncServer).UnbindOrganization(ctx, req.(*UnbindOrganizationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminSync_BindUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BindUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminSyncServer).BindUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminSync_BindUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminSyncServer).BindUser(ctx, req.(*BindUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminSync_UnbindUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnbindUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminSyncServer).UnbindUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminSync_UnbindUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminSyncServer).UnbindUser(ctx, req.(*UnbindUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminSync_UpdateOrganization_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateOrganizationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminSyncServer).UpdateOrganization(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminSync_UpdateOrganization_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminSyncServer).UpdateOrganization(ctx, req.(*UpdateOrganizationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminSync_AddMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddMemberReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminSyncServer).AddMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminSync_AddMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminSyncServer).AddMember(ctx, req.(*AddMemberReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminSync_RemoveMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveMemberReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminSyncServer).RemoveMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminSync_RemoveMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminSyncServer).RemoveMember(ctx, req.(*RemoveMemberReq))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminSync_ServiceDesc is the grpc.ServiceDesc for AdminSync service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminSync_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "eventsync.AdminSync",
	HandlerType: (*AdminSyncServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SyncUser",
			Handler:    _AdminSync_SyncUser_Handler,
		},
		{
			MethodName: "SyncOrganization",
			Handler:    _AdminSync_SyncOrganization_Handler,
		},
		{
			MethodName: "DeleteOrganization",
			Handler:    _AdminSync_DeleteOrganization_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _AdminSync_HealthCheck_Handler,
		},
		{
			MethodName: "GetUserSyncStatus",
			Handler:    _AdminSync_GetUserSyncStatus_Handler,
		},
		{
			MethodName: "GetOrgSyncStatus",
			Handler:    _AdminSync_GetOrgSyncStatus_Handler,
		},
		{
			MethodName: "BindOrganization",
			Handler:    _AdminSync_BindOrganization_Handler,
		},
		{
			MethodName: "UnbindOrganization",
			Handler:    _AdminSync_UnbindOrganization_Handler,
		},
		{
			MethodName: "BindUser",
			Handler:    _AdminSync_BindUser_Handler,
		},
		{
			MethodName: "UnbindUser",
			Handler:    _AdminSync_UnbindUser_Handler,
		},
		{
			MethodName: "UpdateOrganization",
			Handler:    _AdminSync_UpdateOrganization_Handler,
		},
		{
			MethodName: "AddMember",
			Handler:    _AdminSync_AddMember_Handler,
		},
		{
			MethodName: "RemoveMember",
			Handler:    _AdminSync_RemoveMember_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "eventsync.proto",
}
