// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"
	"time"

	eventconfig "github.com/rezeropoint/nexlyn/restful/eventhandler/internal/handler/eventconfig"
	eventdata "github.com/rezeropoint/nexlyn/restful/eventhandler/internal/handler/eventdata"
	eventstats "github.com/rezeropoint/nexlyn/restful/eventhandler/internal/handler/eventstats"
	flowjourney "github.com/rezeropoint/nexlyn/restful/eventhandler/internal/handler/flowjourney"
	orgmapping "github.com/rezeropoint/nexlyn/restful/eventhandler/internal/handler/orgmapping"
	platform "github.com/rezeropoint/nexlyn/restful/eventhandler/internal/handler/platform"
	userassignments "github.com/rezeropoint/nexlyn/restful/eventhandler/internal/handler/userassignments"
	"github.com/rezeropoint/nexlyn/restful/eventhandler/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 创建事件配置（包含字段，事务保证）
				Method:  http.MethodPost,
				Path:    "/event-configs",
				Handler: eventconfig.CreateEventConfigWithFieldsHandler(serverCtx),
			},
			{
				// 更新事件配置（包含字段，完整替换策略）
				Method:  http.MethodPut,
				Path:    "/event-configs/:id",
				Handler: eventconfig.UpdateEventConfigWithFieldsHandler(serverCtx),
			},
			{
				// 获取事件配置详情（包含字段）
				Method:  http.MethodGet,
				Path:    "/event-configs/:id",
				Handler: eventconfig.GetEventConfigWithFieldsHandler(serverCtx),
			},
			{
				// 删除事件配置
				Method:  http.MethodDelete,
				Path:    "/event-configs/:id",
				Handler: eventconfig.DeleteEventConfigHandler(serverCtx),
			},
			{
				// 获取事件配置列表（包含字段）
				Method:  http.MethodGet,
				Path:    "/event-configs/list",
				Handler: eventconfig.GetEventConfigListWithFieldsHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取事件详情（Journey的所有Assignment，用于详情页展示流转历史）
				Method:  http.MethodGet,
				Path:    "/events/:eventId/data/:journeyId",
				Handler: eventdata.GetEventDetailHandler(serverCtx),
			},
			{
				// 查询事件数据列表（动态字段，Journey聚合，返回最新Assignment）
				Method:  http.MethodPost,
				Path:    "/events/:eventId/data/query",
				Handler: eventdata.QueryEventDataHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
		rest.WithTimeout(5000*time.Millisecond),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取处理时长统计
				Method:  http.MethodGet,
				Path:    "/events/stats/duration",
				Handler: eventstats.GetDurationStatsHandler(serverCtx),
			},
			{
				// 获取节点统计
				Method:  http.MethodGet,
				Path:    "/events/stats/node",
				Handler: eventstats.GetNodeStatsHandler(serverCtx),
			},
			{
				// 获取组织统计
				Method:  http.MethodGet,
				Path:    "/events/stats/org",
				Handler: eventstats.GetOrgStatsHandler(serverCtx),
			},
			{
				// 获取待处理事件统计
				Method:  http.MethodGet,
				Path:    "/events/stats/pending",
				Handler: eventstats.GetPendingStatsHandler(serverCtx),
			},
			{
				// 获取状态统计
				Method:  http.MethodGet,
				Path:    "/events/stats/status",
				Handler: eventstats.GetStatusStatsHandler(serverCtx),
			},
			{
				// 获取趋势统计
				Method:  http.MethodGet,
				Path:    "/events/stats/trend",
				Handler: eventstats.GetTrendStatsHandler(serverCtx),
			},
			{
				// 获取处理人统计
				Method:  http.MethodGet,
				Path:    "/events/stats/user",
				Handler: eventstats.GetUserStatsHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 终止流程
				Method:  http.MethodDelete,
				Path:    "/flows/:flowId/journeys/:journeyId",
				Handler: flowjourney.AbortJourneyHandler(serverCtx),
			},
			{
				// 更新流程Journey状态（审批操作：通过/回退/转交/撤销）
				Method:  http.MethodPost,
				Path:    "/flows/:flowId/journeys/:journeyId/actions",
				Handler: flowjourney.UpdateFlowJourneyStatusHandler(serverCtx),
			},
			{
				// 获取流程完整详情（一站式接口，包含基础信息、审批历史、待处理节点）
				Method:  http.MethodGet,
				Path:    "/flows/:flowId/journeys/:journeyId/full-detail",
				Handler: flowjourney.GetJourneyFullDetailHandler(serverCtx),
			},
			{
				// 高级搜索流程记录
				Method:  http.MethodPost,
				Path:    "/flows/:flowId/journeys/search",
				Handler: flowjourney.SearchJourneysHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 创建组织映射（租户级别）
				Method:  http.MethodPost,
				Path:    "/org-mappings",
				Handler: orgmapping.CreateOrgMappingHandler(serverCtx),
			},
			{
				// 获取单个组织映射
				Method:  http.MethodGet,
				Path:    "/org-mappings/:id",
				Handler: orgmapping.GetOrgMappingHandler(serverCtx),
			},
			{
				// 更新组织映射
				Method:  http.MethodPut,
				Path:    "/org-mappings/:id",
				Handler: orgmapping.UpdateOrgMappingHandler(serverCtx),
			},
			{
				// 删除组织映射
				Method:  http.MethodDelete,
				Path:    "/org-mappings/:id",
				Handler: orgmapping.DeleteOrgMappingHandler(serverCtx),
			},
			{
				// 获取组织映射列表（租户的所有映射）
				Method:  http.MethodGet,
				Path:    "/org-mappings/list",
				Handler: orgmapping.GetOrgMappingListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取Skylark平台配置
				Method:  http.MethodGet,
				Path:    "/skylark-platform/config",
				Handler: platform.GetPlatformConfigHandler(serverCtx),
			},
			{
				// 创建/更新Skylark平台配置
				Method:  http.MethodPost,
				Path:    "/skylark-platform/config",
				Handler: platform.SavePlatformConfigHandler(serverCtx),
			},
			{
				// 获取流程列表
				Method:  http.MethodGet,
				Path:    "/skylark-platform/flows",
				Handler: platform.GetFlowListHandler(serverCtx),
			},
			{
				// 获取流程字段列表
				Method:  http.MethodGet,
				Path:    "/skylark-platform/flows/:flowId/fields",
				Handler: platform.GetFlowFieldsHandler(serverCtx),
			},
			{
				// 测试Skylark平台连接
				Method:  http.MethodPost,
				Path:    "/skylark-platform/test-connection",
				Handler: platform.TestPlatformConnectionHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取用户任务列表（待办、已处理、抄送）
				Method:  http.MethodGet,
				Path:    "/my-assignments",
				Handler: userassignments.GetUserAssignmentsHandler(serverCtx),
			},
			{
				// 获取用户发起的流程
				Method:  http.MethodGet,
				Path:    "/my-proposed-journeys",
				Handler: userassignments.GetProposedJourneysHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)
}
