// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: iotquery.proto

package iotquery

import (
	"context"

	"github.com/rezeropoint/nexlyn/service/iotquery/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	DeviceLatestValues      = pb.DeviceLatestValues
	DeviceStatistics        = pb.DeviceStatistics
	FieldStatistics         = pb.FieldStatistics
	FieldValue              = pb.FieldValue
	GetDeviceStatisticsReq  = pb.GetDeviceStatisticsReq
	GetDeviceStatisticsResp = pb.GetDeviceStatisticsResp
	GetLatestValuesReq      = pb.GetLatestValuesReq
	GetLatestValuesResp     = pb.GetLatestValuesResp
	QueryTimeSeriesReq      = pb.QueryTimeSeriesReq
	QueryTimeSeriesResp     = pb.QueryTimeSeriesResp
	TimeSeriesRecord        = pb.TimeSeriesRecord

	IoTQuery interface {
		// QueryTimeSeries 查询时序数据
		QueryTimeSeries(ctx context.Context, in *QueryTimeSeriesReq, opts ...grpc.CallOption) (*QueryTimeSeriesResp, error)
		// GetLatestValues 获取设备字段最新值
		GetLatestValues(ctx context.Context, in *GetLatestValuesReq, opts ...grpc.CallOption) (*GetLatestValuesResp, error)
		// GetDeviceStatistics 获取设备统计信息
		GetDeviceStatistics(ctx context.Context, in *GetDeviceStatisticsReq, opts ...grpc.CallOption) (*GetDeviceStatisticsResp, error)
	}

	defaultIoTQuery struct {
		cli zrpc.Client
	}
)

func NewIoTQuery(cli zrpc.Client) IoTQuery {
	return &defaultIoTQuery{
		cli: cli,
	}
}

// QueryTimeSeries 查询时序数据
func (m *defaultIoTQuery) QueryTimeSeries(ctx context.Context, in *QueryTimeSeriesReq, opts ...grpc.CallOption) (*QueryTimeSeriesResp, error) {
	client := pb.NewIoTQueryClient(m.cli.Conn())
	return client.QueryTimeSeries(ctx, in, opts...)
}

// GetLatestValues 获取设备字段最新值
func (m *defaultIoTQuery) GetLatestValues(ctx context.Context, in *GetLatestValuesReq, opts ...grpc.CallOption) (*GetLatestValuesResp, error) {
	client := pb.NewIoTQueryClient(m.cli.Conn())
	return client.GetLatestValues(ctx, in, opts...)
}

// GetDeviceStatistics 获取设备统计信息
func (m *defaultIoTQuery) GetDeviceStatistics(ctx context.Context, in *GetDeviceStatisticsReq, opts ...grpc.CallOption) (*GetDeviceStatisticsResp, error) {
	client := pb.NewIoTQueryClient(m.cli.Conn())
	return client.GetDeviceStatistics(ctx, in, opts...)
}
