// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: eventsync.proto

package adminsync

import (
	"context"

	"github.com/rezeropoint/nexlyn/service/eventsync/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddMemberReq           = pb.AddMemberReq
	AddMemberResp          = pb.AddMemberResp
	BindOrganizationReq    = pb.BindOrganizationReq
	BindOrganizationResp   = pb.BindOrganizationResp
	BindUserReq            = pb.BindUserReq
	BindUserResp           = pb.BindUserResp
	DeleteOrganizationReq  = pb.DeleteOrganizationReq
	DeleteOrganizationResp = pb.DeleteOrganizationResp
	GetOrgSyncStatusReq    = pb.GetOrgSyncStatusReq
	GetOrgSyncStatusResp   = pb.GetOrgSyncStatusResp
	GetUserSyncStatusReq   = pb.GetUserSyncStatusReq
	GetUserSyncStatusResp  = pb.GetUserSyncStatusResp
	HealthCheckReq         = pb.HealthCheckReq
	HealthCheckResp        = pb.HealthCheckResp
	RemoveMemberReq        = pb.RemoveMemberReq
	RemoveMemberResp       = pb.RemoveMemberResp
	SyncOrganizationReq    = pb.SyncOrganizationReq
	SyncOrganizationResp   = pb.SyncOrganizationResp
	SyncUserReq            = pb.SyncUserReq
	SyncUserResp           = pb.SyncUserResp
	UnbindOrganizationReq  = pb.UnbindOrganizationReq
	UnbindOrganizationResp = pb.UnbindOrganizationResp
	UnbindUserReq          = pb.UnbindUserReq
	UnbindUserResp         = pb.UnbindUserResp
	UpdateOrganizationReq  = pb.UpdateOrganizationReq
	UpdateOrganizationResp = pb.UpdateOrganizationResp

	AdminSync interface {
		// 同步单个用户到Skylark
		SyncUser(ctx context.Context, in *SyncUserReq, opts ...grpc.CallOption) (*SyncUserResp, error)
		// 同步单个组织到Skylark（自动判断根组织或子组织）
		SyncOrganization(ctx context.Context, in *SyncOrganizationReq, opts ...grpc.CallOption) (*SyncOrganizationResp, error)
		// 删除组织同步
		DeleteOrganization(ctx context.Context, in *DeleteOrganizationReq, opts ...grpc.CallOption) (*DeleteOrganizationResp, error)
		// 健康检查
		HealthCheck(ctx context.Context, in *HealthCheckReq, opts ...grpc.CallOption) (*HealthCheckResp, error)
		// 查询用户同步状态
		GetUserSyncStatus(ctx context.Context, in *GetUserSyncStatusReq, opts ...grpc.CallOption) (*GetUserSyncStatusResp, error)
		// 查询组织同步状态
		GetOrgSyncStatus(ctx context.Context, in *GetOrgSyncStatusReq, opts ...grpc.CallOption) (*GetOrgSyncStatusResp, error)
		// 绑定已存在的远程组织
		BindOrganization(ctx context.Context, in *BindOrganizationReq, opts ...grpc.CallOption) (*BindOrganizationResp, error)
		// 解绑组织映射
		UnbindOrganization(ctx context.Context, in *UnbindOrganizationReq, opts ...grpc.CallOption) (*UnbindOrganizationResp, error)
		// 绑定已存在的远程用户
		BindUser(ctx context.Context, in *BindUserReq, opts ...grpc.CallOption) (*BindUserResp, error)
		// 解绑用户映射
		UnbindUser(ctx context.Context, in *UnbindUserReq, opts ...grpc.CallOption) (*UnbindUserResp, error)
		// 更新组织信息（支持设置管理员）
		UpdateOrganization(ctx context.Context, in *UpdateOrganizationReq, opts ...grpc.CallOption) (*UpdateOrganizationResp, error)
		// 添加成员到组织
		AddMember(ctx context.Context, in *AddMemberReq, opts ...grpc.CallOption) (*AddMemberResp, error)
		// 从组织移除成员
		RemoveMember(ctx context.Context, in *RemoveMemberReq, opts ...grpc.CallOption) (*RemoveMemberResp, error)
	}

	defaultAdminSync struct {
		cli zrpc.Client
	}
)

func NewAdminSync(cli zrpc.Client) AdminSync {
	return &defaultAdminSync{
		cli: cli,
	}
}

// 同步单个用户到Skylark
func (m *defaultAdminSync) SyncUser(ctx context.Context, in *SyncUserReq, opts ...grpc.CallOption) (*SyncUserResp, error) {
	client := pb.NewAdminSyncClient(m.cli.Conn())
	return client.SyncUser(ctx, in, opts...)
}

// 同步单个组织到Skylark（自动判断根组织或子组织）
func (m *defaultAdminSync) SyncOrganization(ctx context.Context, in *SyncOrganizationReq, opts ...grpc.CallOption) (*SyncOrganizationResp, error) {
	client := pb.NewAdminSyncClient(m.cli.Conn())
	return client.SyncOrganization(ctx, in, opts...)
}

// 删除组织同步
func (m *defaultAdminSync) DeleteOrganization(ctx context.Context, in *DeleteOrganizationReq, opts ...grpc.CallOption) (*DeleteOrganizationResp, error) {
	client := pb.NewAdminSyncClient(m.cli.Conn())
	return client.DeleteOrganization(ctx, in, opts...)
}

// 健康检查
func (m *defaultAdminSync) HealthCheck(ctx context.Context, in *HealthCheckReq, opts ...grpc.CallOption) (*HealthCheckResp, error) {
	client := pb.NewAdminSyncClient(m.cli.Conn())
	return client.HealthCheck(ctx, in, opts...)
}

// 查询用户同步状态
func (m *defaultAdminSync) GetUserSyncStatus(ctx context.Context, in *GetUserSyncStatusReq, opts ...grpc.CallOption) (*GetUserSyncStatusResp, error) {
	client := pb.NewAdminSyncClient(m.cli.Conn())
	return client.GetUserSyncStatus(ctx, in, opts...)
}

// 查询组织同步状态
func (m *defaultAdminSync) GetOrgSyncStatus(ctx context.Context, in *GetOrgSyncStatusReq, opts ...grpc.CallOption) (*GetOrgSyncStatusResp, error) {
	client := pb.NewAdminSyncClient(m.cli.Conn())
	return client.GetOrgSyncStatus(ctx, in, opts...)
}

// 绑定已存在的远程组织
func (m *defaultAdminSync) BindOrganization(ctx context.Context, in *BindOrganizationReq, opts ...grpc.CallOption) (*BindOrganizationResp, error) {
	client := pb.NewAdminSyncClient(m.cli.Conn())
	return client.BindOrganization(ctx, in, opts...)
}

// 解绑组织映射
func (m *defaultAdminSync) UnbindOrganization(ctx context.Context, in *UnbindOrganizationReq, opts ...grpc.CallOption) (*UnbindOrganizationResp, error) {
	client := pb.NewAdminSyncClient(m.cli.Conn())
	return client.UnbindOrganization(ctx, in, opts...)
}

// 绑定已存在的远程用户
func (m *defaultAdminSync) BindUser(ctx context.Context, in *BindUserReq, opts ...grpc.CallOption) (*BindUserResp, error) {
	client := pb.NewAdminSyncClient(m.cli.Conn())
	return client.BindUser(ctx, in, opts...)
}

// 解绑用户映射
func (m *defaultAdminSync) UnbindUser(ctx context.Context, in *UnbindUserReq, opts ...grpc.CallOption) (*UnbindUserResp, error) {
	client := pb.NewAdminSyncClient(m.cli.Conn())
	return client.UnbindUser(ctx, in, opts...)
}

// 更新组织信息（支持设置管理员）
func (m *defaultAdminSync) UpdateOrganization(ctx context.Context, in *UpdateOrganizationReq, opts ...grpc.CallOption) (*UpdateOrganizationResp, error) {
	client := pb.NewAdminSyncClient(m.cli.Conn())
	return client.UpdateOrganization(ctx, in, opts...)
}

// 添加成员到组织
func (m *defaultAdminSync) AddMember(ctx context.Context, in *AddMemberReq, opts ...grpc.CallOption) (*AddMemberResp, error) {
	client := pb.NewAdminSyncClient(m.cli.Conn())
	return client.AddMember(ctx, in, opts...)
}

// 从组织移除成员
func (m *defaultAdminSync) RemoveMember(ctx context.Context, in *RemoveMemberReq, opts ...grpc.CallOption) (*RemoveMemberResp, error) {
	client := pb.NewAdminSyncClient(m.cli.Conn())
	return client.RemoveMember(ctx, in, opts...)
}
