// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: lynxengine.proto

package lynxengine

import (
	"context"

	"github.com/rezeropoint/nexlyn/service/lynxengine/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	HealthCheckRequest  = pb.HealthCheckRequest
	HealthCheckResponse = pb.HealthCheckResponse
	InfoAtomRequest     = pb.InfoAtomRequest
	InfoAtomResponse    = pb.InfoAtomResponse

	LynxEngine interface {
		// 接收信息原子
		ReceiveInfoAtom(ctx context.Context, in *InfoAtomRequest, opts ...grpc.CallOption) (*InfoAtomResponse, error)
		// 健康检查
		HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	}

	defaultLynxEngine struct {
		cli zrpc.Client
	}
)

func NewLynxEngine(cli zrpc.Client) LynxEngine {
	return &defaultLynxEngine{
		cli: cli,
	}
}

// 接收信息原子
func (m *defaultLynxEngine) ReceiveInfoAtom(ctx context.Context, in *InfoAtomRequest, opts ...grpc.CallOption) (*InfoAtomResponse, error) {
	client := pb.NewLynxEngineClient(m.cli.Conn())
	return client.ReceiveInfoAtom(ctx, in, opts...)
}

// 健康检查
func (m *defaultLynxEngine) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	client := pb.NewLynxEngineClient(m.cli.Conn())
	return client.HealthCheck(ctx, in, opts...)
}
