// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"
	"time"

	control "github.com/rezeropoint/nexlyn/restful/iotmanager/internal/handler/control"
	device "github.com/rezeropoint/nexlyn/restful/iotmanager/internal/handler/device"
	metadata "github.com/rezeropoint/nexlyn/restful/iotmanager/internal/handler/metadata"
	platform "github.com/rezeropoint/nexlyn/restful/iotmanager/internal/handler/platform"
	query "github.com/rezeropoint/nexlyn/restful/iotmanager/internal/handler/query"
	tag "github.com/rezeropoint/nexlyn/restful/iotmanager/internal/handler/tag"
	template "github.com/rezeropoint/nexlyn/restful/iotmanager/internal/handler/template"
	"github.com/rezeropoint/nexlyn/restful/iotmanager/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 获取AI Box算法能力
				Method:  http.MethodGet,
				Path:    "/device-control/aibox/:deviceId/capabilities",
				Handler: control.GetAIBoxCapabilitiesHandler(serverCtx),
			},
			{
				// 查询AI Box任务列表
				Method:  http.MethodGet,
				Path:    "/device-control/aibox/:deviceId/tasks",
				Handler: control.ListAIBoxTasksHandler(serverCtx),
			},
			{
				// 控制AI Box任务（启动/停止）
				Method:  http.MethodPost,
				Path:    "/device-control/aibox/:deviceId/tasks/:taskId/control",
				Handler: control.ControlAIBoxTaskHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
		rest.WithTimeout(10000*time.Millisecond),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 绑定设备
				Method:  http.MethodPost,
				Path:    "/device-bindings",
				Handler: device.BindDeviceHandler(serverCtx),
			},
			{
				// 获取设备详情
				Method:  http.MethodGet,
				Path:    "/device-bindings/:deviceId",
				Handler: device.GetDeviceHandler(serverCtx),
			},
			{
				// 更新设备信息
				Method:  http.MethodPut,
				Path:    "/device-bindings/:deviceId",
				Handler: device.UpdateDeviceHandler(serverCtx),
			},
			{
				// 解绑设备
				Method:  http.MethodDelete,
				Path:    "/device-bindings/:deviceId",
				Handler: device.UnbindDeviceHandler(serverCtx),
			},
			{
				// 获取设备列表
				Method:  http.MethodGet,
				Path:    "/device-bindings/list",
				Handler: device.ListDevicesHandler(serverCtx),
			},
			{
				// 获取未绑定设备列表
				Method:  http.MethodGet,
				Path:    "/device-bindings/unbound",
				Handler: device.ListUnboundDevicesHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
		rest.WithTimeout(10000*time.Millisecond),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取所有设备类别
				Method:  http.MethodGet,
				Path:    "/device-categories",
				Handler: metadata.GetDeviceCategoriesHandler(serverCtx),
			},
			{
				// 获取指定类别的标准字段列表
				Method:  http.MethodGet,
				Path:    "/device-categories/:category/standard-fields",
				Handler: metadata.GetStandardFieldsHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
		rest.WithTimeout(10000*time.Millisecond),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 创建平台配置
				Method:  http.MethodPost,
				Path:    "/platforms",
				Handler: platform.CreatePlatformHandler(serverCtx),
			},
			{
				// 获取平台配置详情
				Method:  http.MethodGet,
				Path:    "/platforms/:id",
				Handler: platform.GetPlatformHandler(serverCtx),
			},
			{
				// 更新平台配置
				Method:  http.MethodPut,
				Path:    "/platforms/:id",
				Handler: platform.UpdatePlatformHandler(serverCtx),
			},
			{
				// 删除平台配置
				Method:  http.MethodDelete,
				Path:    "/platforms/:id",
				Handler: platform.DeletePlatformHandler(serverCtx),
			},
			{
				// 获取平台配置列表
				Method:  http.MethodGet,
				Path:    "/platforms/list",
				Handler: platform.GetPlatformListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
		rest.WithTimeout(10000*time.Millisecond),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取设备字段最新值
				Method:  http.MethodPost,
				Path:    "/timeseries/latest-values",
				Handler: query.GetLatestValuesHandler(serverCtx),
			},
			{
				// 查询时序数据
				Method:  http.MethodPost,
				Path:    "/timeseries/query",
				Handler: query.QueryTimeSeriesHandler(serverCtx),
			},
			{
				// 获取设备统计信息
				Method:  http.MethodPost,
				Path:    "/timeseries/statistics",
				Handler: query.GetDeviceStatisticsHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
		rest.WithTimeout(10000*time.Millisecond),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 创建标签
				Method:  http.MethodPost,
				Path:    "/device-tags",
				Handler: tag.CreateTagHandler(serverCtx),
			},
			{
				// 获取标签详情
				Method:  http.MethodGet,
				Path:    "/device-tags/:tagId",
				Handler: tag.GetTagHandler(serverCtx),
			},
			{
				// 更新标签
				Method:  http.MethodPut,
				Path:    "/device-tags/:tagId",
				Handler: tag.UpdateTagHandler(serverCtx),
			},
			{
				// 删除标签
				Method:  http.MethodDelete,
				Path:    "/device-tags/:tagId",
				Handler: tag.DeleteTagHandler(serverCtx),
			},
			{
				// 获取标签列表
				Method:  http.MethodGet,
				Path:    "/device-tags/list",
				Handler: tag.ListTagsHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
		rest.WithTimeout(10000*time.Millisecond),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 创建设备模板
				Method:  http.MethodPost,
				Path:    "/sensor-template",
				Handler: template.CreateSensorTemplateHandler(serverCtx),
			},
			{
				// 获取设备模板详情
				Method:  http.MethodGet,
				Path:    "/sensor-template/:id",
				Handler: template.GetSensorTemplateHandler(serverCtx),
			},
			{
				// 更新设备模板
				Method:  http.MethodPut,
				Path:    "/sensor-template/:id",
				Handler: template.UpdateSensorTemplateHandler(serverCtx),
			},
			{
				// 删除设备模板
				Method:  http.MethodDelete,
				Path:    "/sensor-template/:id",
				Handler: template.DeleteSensorTemplateHandler(serverCtx),
			},
			{
				// 获取设备模板列表
				Method:  http.MethodGet,
				Path:    "/sensor-template/list",
				Handler: template.GetSensorTemplateListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
		rest.WithTimeout(10000*time.Millisecond),
	)
}
